id: arlec_pc191ha_plug
name: Arlec Grid Connect Smart Plug In Socket With Energy Meter (PC191HA or PC191BKHA)
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: wb2s
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Arlec-PC191HA-Plug/Arlec-PC191HA-Plug.jpg
tags:
- relay
- compact
pins:
- gpio: 6
  available: false
  occupied_by: ARLEC PC191HA 1
- gpio: 7
  available: false
  occupied_by: sensor.hlw8012
- gpio: 8
  available: false
  occupied_by: sensor.hlw8012
- gpio: 11
  available: false
  occupied_by: arlec_PC191HA_1 button
- gpio: 24
  available: false
  occupied_by: sensor.hlw8012
- gpio: 26
  available: false
  occupied_by: button_led
docs_url: https://devices.esphome.io/devices/Arlec-PC191HA-Plug/
featured_components:
- id: button
  component_id: binary_sensor.gpio
  fields:
    pin:
      value: 11
      locked: true
    device_class: window
    id: button
    name: arlec_PC191HA_1 button
- id: button_led
  component_id: output.gpio
  fields:
    pin:
      value: 26
      locked: true
    id: button_led
- id: arlec_pc191ha_1_wifi_signal
  component_id: sensor.wifi_signal
  fields:
    update_interval: 30s
    id: arlec_pc191ha_1_wifi_signal
    name: ARLEC PC191HA 1 WiFi Signal
- id: sensor_hlw8012_1
  component_id: sensor.hlw8012
  fields:
    model: BL0937
    sel_pin:
      value:
        inverted: true
        number: 24
      locked: true
    cf_pin:
      value:
        inverted: true
        number: 7
      locked: true
    cf1_pin:
      value:
        inverted: true
        number: 8
      locked: true
    update_interval: 15s
    initial_mode: VOLTAGE
    change_mode_every: 4
    voltage_divider: 775
    current_resistor: 0.0009
    id: sensor_hlw8012_1
- id: arlec_pc191ha_1_uptime
  component_id: sensor.uptime
  fields:
    update_interval: 30s
    id: arlec_pc191ha_1_uptime
    name: ARLEC PC191HA 1 Uptime
- id: relay
  component_id: switch.gpio
  fields:
    pin:
      value: 6
      locked: true
    restore_mode: always off
    icon: mdi:power-socket-au
    id: relay
    name: ARLEC PC191HA 1
source:
  type: esphome-devices
  remote_id: Arlec-PC191HA-Plug
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Arlec-PC191HA-Plug/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 04b21a5e8d0d75f493385749644f65bcc7df350d19d5fcda4745a3c04c4773ae
