id: govee_h601a_6in_recessed_rgbcct_light
name: Govee 6in recessed RGBCCT light
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: rtl87xx
  board: generic-rtl8720cf-2mb-992k
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Govee-H601A-6in-recessed-RGBCCT-light/module.jpeg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Govee-H601A-6in-recessed-RGBCCT-light/full_pcb.png
pins:
- gpio: 2
  available: false
  occupied_by: green_pwm_output
- gpio: 3
  available: false
  occupied_by: red_pwm_output
- gpio: 4
  available: false
  occupied_by: warm_pwm_output
- gpio: 18
  available: false
  occupied_by: blue_pwm_output
- gpio: 19
  available: false
  occupied_by: cool_pwm_output
docs_url: https://devices.esphome.io/devices/Govee-H601A-6in-recessed-RGBCCT-light/
featured_components:
- id: light_rgbww_1
  component_id: light.rgbww
  fields:
    cold_white_color_temperature: 6350 K
    warm_white_color_temperature: 3000 K
    color_interlock: true
    red: red_pwm_output
    green: green_pwm_output
    blue: blue_pwm_output
    cold_white: cool_pwm_output
    warm_white: warm_pwm_output
    id: light_rgbww_1
    name: Light
- id: green_pwm_output
  component_id: output.libretiny_pwm
  fields:
    pin:
      value: 2
      locked: true
    max_power: 80%
    id: green_pwm_output
- id: red_pwm_output
  component_id: output.libretiny_pwm
  fields:
    pin:
      value: 3
      locked: true
    max_power: 80%
    id: red_pwm_output
- id: blue_pwm_output
  component_id: output.libretiny_pwm
  fields:
    pin:
      value: 18
      locked: true
    max_power: 80%
    id: blue_pwm_output
- id: warm_pwm_output
  component_id: output.libretiny_pwm
  fields:
    pin:
      value: 4
      locked: true
    max_power: 80%
    id: warm_pwm_output
- id: cool_pwm_output
  component_id: output.libretiny_pwm
  fields:
    pin:
      value: 19
      locked: true
    max_power: 80%
    id: cool_pwm_output
featured_bundles:
- id: light_rgbww_1_setup
  name: Light (full setup)
  component_ids:
  - red_pwm_output
  - green_pwm_output
  - blue_pwm_output
  - cool_pwm_output
  - warm_pwm_output
  - light_rgbww_1
source:
  type: esphome-devices
  remote_id: Govee-H601A-6in-recessed-RGBCCT-light
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Govee-H601A-6in-recessed-RGBCCT-light/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: c70ae990f8215691610fe554bcbb48131bbbf29743aca283867740674aabfc35
