id: energizer_smart_plug
name: Energizer Smart Plug
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: generic-bk7231n-qfn32-tuya
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Energizer-Smart-Plug/exterior.png
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Energizer-Smart-Plug/test-pads.png
tags:
- relay
- compact
pins:
- gpio: 6
  available: false
  occupied_by: Relay
- gpio: 24
  available: false
  occupied_by: status_light
- gpio: 26
  available: false
  occupied_by: Button
docs_url: https://devices.esphome.io/devices/Energizer-Smart-Plug/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 26
        inverted: true
      locked: true
    id: binary_sensor_gpio_1
    name: Button
- id: status_light
  component_id: light.status_led
  fields:
    pin:
      value:
        number: 24
        inverted: true
      locked: true
    internal: true
    id: status_light
    name: status_light
- id: relay
  component_id: switch.gpio
  fields:
    pin:
      value: 6
      locked: true
    id: relay
    name: Relay
source:
  type: esphome-devices
  remote_id: Energizer-Smart-Plug
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Energizer-Smart-Plug/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 42c1631baacc03a14280849715c969e71a67982a7bff50fb2edf2958d5b3b221
