id: frankever_fk_pw801us
name: FrankEver FK-PW801US
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/FrankEver-FK-PW801US/frankever-fk-pw801us.jpg
tags:
- relay
- compact
pins:
- gpio: 2
  available: false
  occupied_by: led
- gpio: 13
  available: false
  occupied_by: button
- gpio: 15
  available: false
  occupied_by: Relay
docs_url: https://devices.esphome.io/devices/FrankEver-FK-PW801US/
featured_components:
- id: button
  component_id: binary_sensor.gpio
  fields:
    device_class: power
    pin:
      value:
        number: 13
        inverted: true
        mode: INPUT_PULLUP
      locked: true
    id: button
    name: button
- id: led
  component_id: output.gpio
  fields:
    pin:
      value:
        number: 2
        inverted: true
      locked: true
    id: led
- id: relay
  component_id: switch.gpio
  fields:
    pin:
      value: 15
      locked: true
    id: relay
    name: Relay
source:
  type: esphome-devices
  remote_id: FrankEver-FK-PW801US
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/FrankEver-FK-PW801US/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 46a6502999ab9be807e7a12905e6bd186c8a2b31f4929ac893abdeb2219a55d9
