id: anwio_br30_e26_rgb_cct_13w_light_bulb
name: Anwio BR30 E26 RGBWW 13 Watt Light Bulb
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: wb3l
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Anwio-BR30-E26-RGB-CCT-13W-Light-Bulb/anwio-br30-top-down.jpg
pins:
- gpio: 6
  available: false
  occupied_by: output_white_temp
- gpio: 7
  available: false
  occupied_by: output_white_brightness
- gpio: 8
  available: false
  occupied_by: output_red
- gpio: 24
  available: false
  occupied_by: output_green
- gpio: 26
  available: false
  occupied_by: output_blue
docs_url: https://devices.esphome.io/devices/Anwio-BR30-E26-RGB-CCT-13W-Light-Bulb/
featured_components:
- id: bar_pendant_left
  component_id: light.rgbct
  fields:
    color_interlock: true
    cold_white_color_temperature: 6200K
    warm_white_color_temperature: 2000K
    red: output_red
    green: output_green
    blue: output_blue
    color_temperature: output_white_temp
    white_brightness: output_white_brightness
    id: bar_pendant_left
    name: Light
- id: output_red
  component_id: output.libretiny_pwm
  fields:
    pin:
      value: 8
      locked: true
    id: output_red
- id: output_green
  component_id: output.libretiny_pwm
  fields:
    pin:
      value: 24
      locked: true
    id: output_green
- id: output_blue
  component_id: output.libretiny_pwm
  fields:
    pin:
      value: 26
      locked: true
    id: output_blue
- id: output_white_brightness
  component_id: output.libretiny_pwm
  fields:
    pin:
      value: 7
      locked: true
    id: output_white_brightness
- id: output_white_temp
  component_id: output.libretiny_pwm
  fields:
    pin:
      value: 6
      locked: true
    inverted:
      value: true
      locked: true
    id: output_white_temp
- id: sensor_uptime_1
  component_id: sensor.uptime
  fields:
    device_class: duration
    id: sensor_uptime_1
    name: Uptime
featured_bundles:
- id: bar_pendant_left_setup
  name: Light (full setup)
  component_ids:
  - output_red
  - output_green
  - output_blue
  - output_white_temp
  - output_white_brightness
  - bar_pendant_left
source:
  type: esphome-devices
  remote_id: Anwio-BR30-E26-RGB-CCT-13W-Light-Bulb
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Anwio-BR30-E26-RGB-CCT-13W-Light-Bulb/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 89dbba60bad778bf9127cb4d8ffea107591c5c4385def31c65a1ecea1b0ac804
