id: tenstar_robot_esp32_s3_supermini
name: TENSTAR ROBOT ESP32-S3 Supermini
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework: esp-idf
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/TENSTAR-ROBOT-ESP32-S3-SuperMini/Pinouts.webp
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/TENSTAR-ROBOT-ESP32-S3-SuperMini/esp32s3supermini.jpeg
pins:
- gpio: 48
  available: false
  occupied_by: WS2812B Light
docs_url: https://devices.esphome.io/devices/TENSTAR-ROBOT-ESP32-S3-SuperMini/
featured_components:
- id: onboard_psram
  component_id: psram
  name: PSRAM
  fields:
    mode: quad
    speed: 80MHz
- id: status_light
  component_id: light.esp32_rmt_led_strip
  fields:
    chipset: WS2812
    pin:
      value: 48
      locked: true
    num_leds: 1
    rgb_order: GRB
    restore_mode: ALWAYS_ON
    id: status_light
    name: WS2812B Light
  requires:
  - onboard_psram
source:
  type: esphome-devices
  remote_id: TENSTAR-ROBOT-ESP32-S3-SuperMini
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/TENSTAR-ROBOT-ESP32-S3-SuperMini/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: be73ebde450dfb159f65d31908fadcd8897428501aa73427334ec0f6457b7523
