id: gosund_wp6
name: Gosund WP6
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Gosund-WP6/gosund_WP6.jpeg
tags:
- relay
- compact
pins:
- gpio: 1
  available: false
  occupied_by: led
- gpio: 3
  available: false
  occupied_by: Gosund WP6 Button
- gpio: 14
  available: false
  occupied_by: Gosund WP6 Relay
docs_url: https://devices.esphome.io/devices/Gosund-WP6/
featured_components:
- id: gosund_wp6_button
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 3
        mode: INPUT_PULLUP
        inverted: true
      locked: true
    id: gosund_wp6_button
    name: Gosund WP6 Button
- id: led
  component_id: output.gpio
  fields:
    pin:
      value: 1
      locked: true
    inverted:
      value: true
      locked: true
    id: led
- id: gosund_wp6_wifi_signal
  component_id: sensor.wifi_signal
  fields:
    update_interval: 60s
    id: gosund_wp6_wifi_signal
    name: Gosund WP6 WiFi signal
- id: gosund_wp6_uptime
  component_id: sensor.uptime
  fields:
    update_interval: 60s
    id: gosund_wp6_uptime
    name: Gosund WP6 Uptime
- id: gosund_wp6_relay
  component_id: switch.gpio
  fields:
    pin:
      value: 14
      locked: true
    id: gosund_wp6_relay
    name: Gosund WP6 Relay
source:
  type: esphome-devices
  remote_id: Gosund-WP6
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Gosund-WP6/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 4f1bbafd00a79dbee46423f9d427137d2fbdf7d568778febc01bbe4ffd87f80a
