id: athom_smart_plug_tp29
name: Athom Smart Plug TP29
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Athom-Smart-Plug-TP29/Athom-EU-Plug.png
tags:
- relay
- compact
pins:
- gpio: 3
  available: false
  occupied_by: button_1
- gpio: 4
  available: false
  occupied_by: sensor.hlw8012
- gpio: 5
  available: false
  occupied_by: sensor.hlw8012
- gpio: 12
  available: false
  occupied_by: sensor.hlw8012
- gpio: 13
  available: false
  occupied_by: sw_led1
- gpio: 14
  available: false
  occupied_by: Athom Smart Plug Switch
docs_url: https://devices.esphome.io/devices/Athom-Smart-Plug-TP29/
featured_components:
- id: button_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 3
        mode: INPUT_PULLUP
        inverted: true
      locked: true
    id: button_1
    name: button_1
- id: sensor_hlw8012_1
  component_id: sensor.hlw8012
  fields:
    sel_pin:
      value:
        number: 12
        inverted: true
      locked: true
    cf_pin:
      value: 4
      locked: true
    cf1_pin:
      value: 5
      locked: true
    current_resistor: '0.00225'
    voltage_divider: '757'
    change_mode_every: 4
    update_interval: 10s
    id: sensor_hlw8012_1
- id: sensor_uptime_1
  component_id: sensor.uptime
  fields:
    icon: mdi:clock-outline
    id: sensor_uptime_1
    name: Athom Smart Plug Uptime
- id: sensor_wifi_signal_1
  component_id: sensor.wifi_signal
  fields:
    update_interval: 60s
    id: sensor_wifi_signal_1
    name: Athom Smart Plug Wifi Signal
- id: relay_1
  component_id: switch.gpio
  fields:
    icon: mdi:power-socket-uk
    pin:
      value: 14
      locked: true
    id: relay_1
    name: Athom Smart Plug Switch
- id: sw_led1
  component_id: switch.gpio
  fields:
    pin:
      value: 13
      locked: true
    inverted:
      value: true
      locked: true
    id: sw_led1
    name: sw_led1
source:
  type: esphome-devices
  remote_id: Athom-Smart-Plug-TP29
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Athom-Smart-Plug-TP29/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: b805ffec358b3fe6e877a1971b3752b5077a34013ce999b4b7bbff2e54424cba
