id: tuya_wb5_wifi_5in1_led_controller
name: Tuya WB5 WiFi 5 in 1 LED Controller
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: generic-bk7231n-qfn32-tuya
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tuya-WB5-WiFi-5in1-LED-Controller/WB5-WiFi-5IN1-LED-Controller.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tuya-WB5-WiFi-5in1-LED-Controller/WB5-pcb.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tuya-WB5-WiFi-5in1-LED-Controller/usb-serial-adapter.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tuya-WB5-WiFi-5in1-LED-Controller/probe-hook.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tuya-WB5-WiFi-5in1-LED-Controller/Probe-Test-Lead.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tuya-WB5-WiFi-5in1-LED-Controller/pins.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tuya-WB5-WiFi-5in1-LED-Controller/pcbite.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tuya-WB5-WiFi-5in1-LED-Controller/Outout-Mode.jpg
docs_url: https://devices.esphome.io/devices/Tuya-WB5-WiFi-5in1-LED-Controller/
featured_components:
- id: uart_bus
  component_id: uart
  fields:
    rx_pin:
      value: RX1
      locked: true
    tx_pin:
      value: TX1
      locked: true
    baud_rate: 9600
- id: tuya_hub
  component_id: tuya
  fields: {}
  requires:
  - uart_bus
- id: light_tuya_1
  component_id: light.tuya
  fields:
    color_interlock: true
    gamma_correct: 1
    default_transition_length: 0s
    switch_datapoint: 20
    dimmer_datapoint: 22
    min_value: 0
    max_value: 1000
    id: light_tuya_1
    name: WB5 LED Controller
  requires:
  - uart_bus
  - tuya_hub
source:
  type: esphome-devices
  remote_id: Tuya-WB5-WiFi-5in1-LED-Controller
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Tuya-WB5-WiFi-5in1-LED-Controller/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: a9b4695749505ceb4c37940f7bc4400fd7ef7763b0251928bb2069da599717fb
