id: delock_11826_power_plug
name: Delock 11826 Power Smart Plug
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp8285
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Delock-11826-Power-Plug/Delock-11826-Power-Smart-Plug.jpg
tags:
- relay
- compact
pins:
- gpio: 0
  available: false
  occupied_by: delock01 Button
- gpio: 12
  available: false
  occupied_by: delock01 Smart Plug
- gpio: 13
  available: false
  occupied_by: led
docs_url: https://devices.esphome.io/devices/Delock-11826-Power-Plug/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 0
        inverted: true
      locked: true
    id: binary_sensor_gpio_1
    name: delock01 Button
- id: led
  component_id: switch.gpio
  fields:
    pin:
      value: 13
      locked: true
    id: led
    name: led
- id: relay
  component_id: switch.gpio
  fields:
    pin:
      value: 12
      locked: true
    id: relay
    name: delock01 Smart Plug
source:
  type: esphome-devices
  remote_id: Delock-11826-Power-Plug
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Delock-11826-Power-Plug/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: da996ff6223602e2ee0375d5cf1812d360b3f97b9ca5a63c31bb9cdc539b5c55
