id: kincony_ta
name: KinCony-TA (ESP32 Smart Tiny Alarm System)
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework: arduino
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KinCony-TA/TA1.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KinCony-TA/TA2.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KinCony-TA/TA3.jpg
pins:
- gpio: 0
  available: false
  occupied_by: ta-io0
- gpio: 4
  available: false
  occupied_by: ta-io04
- gpio: 5
  available: false
  occupied_by: ta-io05
- gpio: 6
  available: false
  occupied_by: ta-io06
- gpio: 7
  available: false
  occupied_by: ta-io07
- gpio: 8
  available: false
  occupied_by: bus_a
- gpio: 9
  available: false
  occupied_by: ta-io09
- gpio: 11
  available: false
  occupied_by: ta-io11
- gpio: 12
  available: false
  occupied_by: ta-433M-R
- gpio: 13
  available: false
  occupied_by: ta-io13
- gpio: 14
  available: false
  occupied_by: ta-io14
- gpio: 18
  available: false
  occupied_by: bus_a
- gpio: 21
  available: false
  occupied_by: ta-io21
- gpio: 38
  available: false
  occupied_by: uart_1
- gpio: 39
  available: false
  occupied_by: uart_1
- gpio: 40
  available: false
  occupied_by: ta-io40
- gpio: 47
  available: false
  occupied_by: ta-io47
- gpio: 48
  available: false
  occupied_by: ta-io48
docs_url: https://devices.esphome.io/devices/KinCony-TA/
featured_components:
- id: uart_1
  component_id: uart
  fields:
    baud_rate: 9600
    debug:
      value:
        direction: BOTH
        dummy_receiver: true
        after:
          timeout: 10ms
      locked: true
    tx_pin:
      value: 39
      locked: true
    rx_pin:
      value: 38
      locked: true
    id:
      value: uart_1
      locked: true
- id: bus_a
  component_id: i2c
  fields:
    sda:
      value: 8
      locked: true
    scl:
      value: 18
      locked: true
    scan: true
    frequency: 400kHz
    id:
      value: bus_a
      locked: true
- id: pcf8574_hub_out_1
  component_id: pcf8574
  fields:
    address: 34
    pcf8575: true
    id:
      value: pcf8574_hub_out_1
      locked: true
    i2c_id:
      value: bus_a
      locked: true
  requires:
  - bus_a
- id: ta_input01
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 0
        mode: INPUT
        inverted: true
      locked: true
    id: ta_input01
    name: ta-input01
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: ta_input02
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 1
        mode: INPUT
        inverted: true
      locked: true
    id: ta_input02
    name: ta-input02
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: ta_input03
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 2
        mode: INPUT
        inverted: true
      locked: true
    id: ta_input03
    name: ta-input03
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: ta_input04
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 3
        mode: INPUT
        inverted: true
      locked: true
    id: ta_input04
    name: ta-input04
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: ta_input05
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 4
        mode: INPUT
        inverted: true
      locked: true
    id: ta_input05
    name: ta-input05
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: ta_input06
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 5
        mode: INPUT
        inverted: true
      locked: true
    id: ta_input06
    name: ta-input06
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: ta_input07
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 6
        mode: INPUT
        inverted: true
      locked: true
    id: ta_input07
    name: ta-input07
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: ta_input08
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 7
        mode: INPUT
        inverted: true
      locked: true
    id: ta_input08
    name: ta-input08
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: ta_input09
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 8
        mode: INPUT
        inverted: true
      locked: true
    id: ta_input09
    name: ta-input09
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: ta_input10
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 9
        mode: INPUT
        inverted: true
      locked: true
    id: ta_input10
    name: ta-input10
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: ta_input11
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 10
        mode: INPUT
        inverted: true
      locked: true
    id: ta_input11
    name: ta-input11
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: ta_input12
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 11
        mode: INPUT
        inverted: true
      locked: true
    id: ta_input12
    name: ta-input12
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: binary_sensor_gpio_13
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 9
        inverted: true
      locked: true
    id: binary_sensor_gpio_13
    name: ta-io09
- id: binary_sensor_gpio_14
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 11
        inverted: true
      locked: true
    id: binary_sensor_gpio_14
    name: ta-io11
- id: binary_sensor_gpio_15
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 5
        inverted: true
      locked: true
    id: binary_sensor_gpio_15
    name: ta-io05
- id: binary_sensor_gpio_16
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 4
        inverted: true
      locked: true
    id: binary_sensor_gpio_16
    name: ta-io04
- id: binary_sensor_gpio_17
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 7
        inverted: false
      locked: true
    id: binary_sensor_gpio_17
    name: ta-io07
- id: binary_sensor_gpio_18
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 6
        inverted: false
      locked: true
    id: binary_sensor_gpio_18
    name: ta-io06
- id: binary_sensor_gpio_19
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 13
        inverted: false
      locked: true
    id: binary_sensor_gpio_19
    name: ta-io13
- id: binary_sensor_gpio_20
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 40
        inverted: false
      locked: true
    id: binary_sensor_gpio_20
    name: ta-io40
- id: binary_sensor_gpio_21
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 14
        inverted: false
      locked: true
    id: binary_sensor_gpio_21
    name: ta-io14
- id: binary_sensor_gpio_22
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 48
        inverted: false
      locked: true
    id: binary_sensor_gpio_22
    name: ta-io48
- id: binary_sensor_gpio_23
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 21
        inverted: false
      locked: true
    id: binary_sensor_gpio_23
    name: ta-io21
- id: binary_sensor_gpio_24
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 47
        inverted: false
      locked: true
    id: binary_sensor_gpio_24
    name: ta-io47
- id: binary_sensor_gpio_25
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 0
        inverted: false
      locked: true
    id: binary_sensor_gpio_25
    name: ta-io0
- id: binary_sensor_gpio_26
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 12
        inverted: false
      locked: true
    id: binary_sensor_gpio_26
    name: ta-433M-R
- id: switch_uart_1
  component_id: switch.uart
  fields:
    data:
      value:
      - 17
      - 34
      - 51
      - 68
      - 85
      locked: true
    id: switch_uart_1
    name: RS485 Button
    uart_id:
      value: uart_1
      locked: true
  requires:
  - uart_1
- id: ta_output01
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 14
        mode: OUTPUT
        inverted: true
      locked: true
    id: ta_output01
    name: ta-output01
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: ta_output02
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 15
        mode: OUTPUT
        inverted: true
      locked: true
    id: ta_output02
    name: ta-output02
  requires:
  - bus_a
  - pcf8574_hub_out_1
source:
  type: esphome-devices
  remote_id: KinCony-TA
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/KinCony-TA/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 1300f77c5a1d463cc4d7de1cefc5ebd70ab70ee773c7fe040003664e71aacf3b
