id: lutec_origo
name: LUTEC Origo WiZ ceiling/wall lamp
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32dev
  variant: esp32
  framework: arduino
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/LUTEC-Origo/LUTEC-Origo.jpg
pins:
- gpio: 2
  available: false
  occupied_by: output_warm_white
- gpio: 4
  available: false
  occupied_by: output_cool_white
- gpio: 25
  available: false
  occupied_by: output_red
- gpio: 26
  available: false
  occupied_by: output_green
- gpio: 27
  available: false
  occupied_by: output_blue
docs_url: https://devices.esphome.io/devices/LUTEC-Origo/
featured_components:
- id: light_rgbww_1
  component_id: light.rgbww
  fields:
    cold_white_color_temperature: 6500K
    warm_white_color_temperature: 2700K
    constant_brightness: true
    default_transition_length: 1s
    gamma_correct: 2.8
    red: output_red
    green: output_green
    blue: output_blue
    warm_white: output_warm_white
    cold_white: output_cool_white
    id: light_rgbww_1
    name: WC+RGB Light
- id: output_red
  component_id: output.ledc
  fields:
    pin:
      value: 25
      locked: true
    frequency: 24000 Hz
    id: output_red
- id: output_green
  component_id: output.ledc
  fields:
    pin:
      value: 26
      locked: true
    frequency: 24000 Hz
    id: output_green
- id: output_blue
  component_id: output.ledc
  fields:
    pin:
      value: 27
      locked: true
    frequency: 24000 Hz
    id: output_blue
- id: output_warm_white
  component_id: output.ledc
  fields:
    pin:
      value: 2
      locked: true
    frequency: 24000 Hz
    id: output_warm_white
- id: output_cool_white
  component_id: output.ledc
  fields:
    pin:
      value: 4
      locked: true
    frequency: 24000 Hz
    id: output_cool_white
featured_bundles:
- id: light_rgbww_1_setup
  name: WC+RGB Light (full setup)
  component_ids:
  - output_red
  - output_green
  - output_blue
  - output_warm_white
  - output_cool_white
  - light_rgbww_1
source:
  type: esphome-devices
  remote_id: LUTEC-Origo
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/LUTEC-Origo/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 6e00543b296353a46731dbb399887a0a351007bf08f4dee4965f07651b038e9b
