id: blitzwolf_bw_shp8_power_monitoring_wall_outlet
name: BlitzWolf BW-SHP8 Power Monitoring Wall Outlet
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp8285
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/BlitzWolf-BW-SHP8-Power-Monitoring-Wall-Outlet/BlitzWolf-BW-SHP8-Power-Monitoring-Wall-Outlet.jpg
tags:
- relay
- compact
pins:
- gpio: 1
  available: false
  occupied_by: state_led
- gpio: 3
  available: false
  occupied_by: button
- gpio: 4
  available: false
  occupied_by: sensor.hlw8012
- gpio: 5
  available: false
  occupied_by: sensor.hlw8012
- gpio: 12
  available: false
  occupied_by: sensor.hlw8012
- gpio: 14
  available: false
  occupied_by: BW-SHP8 power
docs_url: https://devices.esphome.io/devices/BlitzWolf-BW-SHP8-Power-Monitoring-Wall-Outlet/
featured_components:
- id: button
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 3
        inverted: true
        mode: INPUT_PULLUP
      locked: true
    id: button
    name: button
- id: led
  component_id: light.monochromatic
  fields:
    output: state_led
    id: led
    name: led
- id: state_led
  component_id: output.esp8266_pwm
  fields:
    pin:
      value:
        number: 1
        inverted: true
      locked: true
    id: state_led
- id: sensor_hlw8012_1
  component_id: sensor.hlw8012
  fields:
    model: BL0937
    current_resistor: '0.001'
    voltage_divider: '1727'
    change_mode_every: 2
    update_interval: 2s
    sel_pin:
      value:
        number: 12
        inverted: true
      locked: true
    cf_pin:
      value: 4
      locked: true
    cf1_pin:
      value: 5
      locked: true
    id: sensor_hlw8012_1
- id: relay
  component_id: switch.gpio
  fields:
    pin:
      value: 14
      locked: true
    restore_mode: ALWAYS_ON
    icon: mdi:power-socket-de
    id: relay
    name: BW-SHP8 power
featured_bundles:
- id: led_setup
  name: led (full setup)
  component_ids:
  - state_led
  - led
source:
  type: esphome-devices
  remote_id: BlitzWolf-BW-SHP8-Power-Monitoring-Wall-Outlet
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/BlitzWolf-BW-SHP8-Power-Monitoring-Wall-Outlet/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 73f36aed57c85c8df97441af397c9089df8d287e05d20e8c79766de8c4aa44bc
