id: geeni_4_outlet_surge_strip
name: Geeni 4-Outlet Surge Strip
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: cb2s
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Geeni-4-outlet-surge-strip/geeni4.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Geeni-4-outlet-surge-strip/20251115_163733.jpg
tags:
- relay
- compact
pins:
- gpio: 6
  available: false
  occupied_by: Outlet 1
- gpio: 7
  available: false
  occupied_by: Outlet 2
- gpio: 10
  available: false
  occupied_by: Button
- gpio: 11
  available: false
  occupied_by: Status LED
- gpio: 24
  available: false
  occupied_by: Outlet 4
- gpio: 26
  available: false
  occupied_by: Outlet 3
docs_url: https://devices.esphome.io/devices/Geeni-4-outlet-surge-strip/
featured_components:
- id: bp10
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 10
        inverted: true
      locked: true
    id: bp10
    name: Button
- id: led
  component_id: light.status_led
  fields:
    pin:
      value:
        number: 11
        inverted: true
      locked: true
    id: led
    name: Status LED
- id: switch_1
  component_id: switch.gpio
  fields:
    pin:
      value: 6
      locked: true
    restore_mode: ALWAYS_ON
    id: switch_1
    name: Outlet 1
- id: switch_2
  component_id: switch.gpio
  fields:
    pin:
      value: 7
      locked: true
    restore_mode: ALWAYS_ON
    id: switch_2
    name: Outlet 2
- id: switch_3
  component_id: switch.gpio
  fields:
    pin:
      value: 26
      locked: true
    restore_mode: ALWAYS_ON
    id: switch_3
    name: Outlet 3
- id: switch_4
  component_id: switch.gpio
  fields:
    pin:
      value: 24
      locked: true
    restore_mode: ALWAYS_ON
    id: switch_4
    name: Outlet 4
source:
  type: esphome-devices
  remote_id: Geeni-4-outlet-surge-strip
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Geeni-4-outlet-surge-strip/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 9f305d359bea1c69fd2eef2bb14b0582cf73bdab67f0072b0011397899fc4843
