id: esp32_s3_4_0_inch_smart_display
name: ESP32-S3 4.0 Inch Smart Display
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework: esp-idf
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/ESP32-S3-4.0-Inch-Smart-Display/ESP32-S3-4.0-Inch-Smart-Display.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/ESP32-S3-4.0-Inch-Smart-Display/ESP32-S3-4.0-Inch-Smart-Display_animation.jpg
pins:
- gpio: 0
  available: false
  occupied_by: display.st7701s
- gpio: 1
  available: false
  occupied_by: touchdisplay1 Relay 3
- gpio: 2
  available: false
  occupied_by: touchdisplay1 Relay 2
- gpio: 3
  available: false
  occupied_by: display.st7701s
- gpio: 4
  available: false
  occupied_by: display.st7701s
- gpio: 5
  available: false
  occupied_by: display.st7701s
- gpio: 6
  available: false
  occupied_by: display.st7701s
- gpio: 7
  available: false
  occupied_by: display.st7701s
- gpio: 8
  available: false
  occupied_by: display.st7701s
- gpio: 9
  available: false
  occupied_by: display.st7701s
- gpio: 10
  available: false
  occupied_by: display.st7701s
- gpio: 11
  available: false
  occupied_by: display.st7701s
- gpio: 12
  available: false
  occupied_by: display.st7701s
- gpio: 13
  available: false
  occupied_by: display.st7701s
- gpio: 14
  available: false
  occupied_by: display.st7701s
- gpio: 15
  available: false
  occupied_by: display.st7701s
- gpio: 16
  available: false
  occupied_by: display.st7701s
- gpio: 17
  available: false
  occupied_by: display.st7701s
- gpio: 18
  available: false
  occupied_by: display.st7701s
- gpio: 20
  available: false
  occupied_by: display.st7701s
- gpio: 21
  available: false
  occupied_by: display.st7701s
- gpio: 38
  available: false
  occupied_by: backlight
- gpio: 39
  available: false
  occupied_by: display.st7701s
- gpio: 40
  available: false
  occupied_by: touchdisplay1 Relay 1
- gpio: 46
  available: false
  occupied_by: display.st7701s
- gpio: 47
  available: false
  occupied_by: spi
- gpio: 48
  available: false
  occupied_by: spi
docs_url: https://devices.esphome.io/devices/ESP32-S3-4.0-Inch-Smart-Display/
featured_components:
- id: spi_bus
  component_id: spi
  fields:
    mosi_pin:
      value: 47
      locked: true
    clk_pin:
      value: 48
      locked: true
- id: onboard_psram
  component_id: psram
  name: PSRAM
  fields:
    mode: octal
    speed: 80MHz
- id: display_st7701s_1
  component_id: display.st7701s
  fields:
    color_order: RGB
    dimensions:
      value:
        width: 480
        height: 480
      locked: true
    cs_pin:
      value: 39
      locked: true
    de_pin:
      value: 18
      locked: true
    hsync_pin:
      value: 16
      locked: true
    vsync_pin:
      value: 17
      locked: true
    pclk_pin:
      value: 21
      locked: true
    data_rate: 40MHz
    data_pins:
      value:
      - 46
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 0
      - 4
      - 5
      - 6
      - 7
      - 15
      - 8
      - 20
      - 3
      locked: true
    init_sequence:
      value:
      - - 1
      - - 255
        - 119
        - 1
        - 0
        - 0
        - 16
      - - 192
        - 59
        - 0
      - - 193
        - 13
        - 2
      - - 194
        - 49
        - 5
      - - 205
        - 0
      - - 176
        - 0
        - 17
        - 24
        - 14
        - 17
        - 6
        - 7
        - 8
        - 7
        - 34
        - 4
        - 18
        - 15
        - 170
        - 49
        - 24
      - - 177
        - 0
        - 17
        - 25
        - 14
        - 18
        - 7
        - 8
        - 8
        - 8
        - 34
        - 4
        - 17
        - 17
        - 169
        - 50
        - 24
      - - 255
        - 119
        - 1
        - 0
        - 0
        - 17
      - - 176
        - 96
      - - 177
        - 50
      - - 178
        - 7
      - - 179
        - 128
      - - 181
        - 73
      - - 183
        - 133
      - - 184
        - 33
      - - 193
        - 120
      - - 194
        - 120
      - - 224
        - 0
        - 27
        - 2
      - - 225
        - 8
        - 160
        - 0
        - 0
        - 7
        - 160
        - 0
        - 0
        - 0
        - 68
        - 68
      - - 226
        - 17
        - 17
        - 68
        - 68
        - 237
        - 160
        - 0
        - 0
        - 236
        - 160
        - 0
        - 0
      - - 227
        - 0
        - 0
        - 17
        - 17
      - - 228
        - 68
        - 68
      - - 229
        - 10
        - 233
        - 216
        - 160
        - 12
        - 235
        - 216
        - 160
        - 14
        - 237
        - 216
        - 160
        - 16
        - 239
        - 216
        - 160
      - - 230
        - 0
        - 0
        - 17
        - 17
      - - 231
        - 68
        - 68
      - - 232
        - 9
        - 232
        - 216
        - 160
        - 11
        - 234
        - 216
        - 160
        - 13
        - 236
        - 216
        - 160
        - 15
        - 238
        - 216
        - 160
      - - 235
        - 2
        - 0
        - 228
        - 228
        - 136
        - 0
        - 64
      - - 236
        - 60
        - 0
      - - 237
        - 171
        - 137
        - 118
        - 84
        - 2
        - 255
        - 255
        - 255
        - 255
        - 255
        - 255
        - 32
        - 69
        - 103
        - 152
        - 186
      - - 255
        - 119
        - 1
        - 0
        - 0
        - 19
      - - 229
        - 228
      - - 58
        - 96
      locked: true
    id: display_st7701s_1
  requires:
  - onboard_psram
  - spi_bus
- id: backlight
  component_id: output.ledc
  fields:
    pin:
      value: 38
      locked: true
    id: backlight
- id: sensor_wifi
  component_id: sensor.wifi_signal
  fields:
    update_interval: 60s
    entity_category: diagnostic
    id: sensor_wifi
    name: touchdisplay1 WiFi Signal
- id: uptime_sensor
  component_id: sensor.uptime
  fields:
    update_interval: 15s
    entity_category: diagnostic
    id: uptime_sensor
    name: touchdisplay1 Uptime
- id: relay1
  component_id: switch.gpio
  fields:
    pin:
      value: 40
      locked: true
    id: relay1
    name: touchdisplay1 Relay 1
- id: relay2
  component_id: switch.gpio
  fields:
    pin:
      value: 2
      locked: true
    id: relay2
    name: touchdisplay1 Relay 2
- id: relay3
  component_id: switch.gpio
  fields:
    pin:
      value: 1
      locked: true
    id: relay3
    name: touchdisplay1 Relay 3
source:
  type: esphome-devices
  remote_id: ESP32-S3-4.0-Inch-Smart-Display
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/ESP32-S3-4.0-Inch-Smart-Display/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 197521fbb15e9afc69557a2e7b42ccc2914baa597192d5c45a84468eec041938
