id: arlec_grid_connect_smart_ceiling_fan_dcf4002
name: Arlec DCF4002WHA/DCF4002BHA Ceiling Fan+Light
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Arlec-Grid-Connect-Smart-Ceiling-Fan-DCF4002/DCF4002WHA.jpeg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Arlec-Grid-Connect-Smart-Ceiling-Fan-DCF4002/DCF4002_controller.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Arlec-Grid-Connect-Smart-Ceiling-Fan-DCF4002/DCF4002_daughterboard.jpg
docs_url: https://devices.esphome.io/devices/Arlec-Grid-Connect-Smart-Ceiling-Fan-DCF4002/
featured_components:
- id: uart_bus
  component_id: uart
  fields:
    rx_pin:
      value: RX
      locked: true
    tx_pin:
      value: TX
      locked: true
    baud_rate: 9600
- id: tuya_hub
  component_id: tuya
  fields:
    ignore_mcu_update_on_datapoints:
      value:
      - 102
      - 103
      locked: true
  requires:
  - uart_bus
- id: ceiling_fan
  component_id: fan.tuya
  fields:
    switch_datapoint: 1
    speed_datapoint: 3
    direction_datapoint: 4
    speed_count: 6
    id: ceiling_fan
    name: Ceiling Fan
  requires:
  - uart_bus
  - tuya_hub
- id: ceiling_fan_light
  component_id: light.tuya
  fields:
    switch_datapoint: 9
    dimmer_datapoint: 10
    min_value: 10
    max_value: 100
    color_temperature_datapoint: 11
    color_temperature_max_value: 100
    color_temperature_invert: false
    cold_white_color_temperature: 6493 K
    warm_white_color_temperature: 4065 K
    id: ceiling_fan_light
    name: Light
  requires:
  - uart_bus
  - tuya_hub
source:
  type: esphome-devices
  remote_id: Arlec-Grid-Connect-Smart-Ceiling-Fan-DCF4002
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Arlec-Grid-Connect-Smart-Ceiling-Fan-DCF4002/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 22c9360ff95f368e52cc48076c9c2521b1fdd8cca6dfa3414c5071a123761024
