id: electriq_iqoolsmart12hp_air_conditioner
name: electriQ IQOOL SMART12HP
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Electriq-IQoolsmart12hp-air-conditioner/electriq_IQOOL-SMART12HP.jpg
pins:
- gpio: 13
  available: false
  occupied_by: uart
- gpio: 15
  available: false
  occupied_by: uart
docs_url: https://devices.esphome.io/devices/Electriq-IQoolsmart12hp-air-conditioner/
featured_components:
- id: uart_bus
  component_id: uart
  fields:
    rx_pin:
      value: 13
      locked: true
    tx_pin:
      value: 15
      locked: true
    baud_rate: 9600
- id: tuya_hub
  component_id: tuya
  fields: {}
  requires:
  - uart_bus
- id: climate_tuya_1
  component_id: climate.tuya
  fields:
    supports_heat: true
    supports_cool: true
    switch_datapoint: 1
    target_temperature_datapoint: 2
    current_temperature_datapoint: 3
    id: climate_tuya_1
    name: Electriq air con Climate
  requires:
  - uart_bus
  - tuya_hub
- id: sensor_tuya_1
  component_id: sensor.tuya
  fields:
    sensor_datapoint: 3
    id: sensor_tuya_1
    name: Current Temperature
  requires:
  - uart_bus
  - tuya_hub
- id: switch_tuya_1
  component_id: switch.tuya
  fields:
    switch_datapoint: 101
    id: switch_tuya_1
    name: Electriq air con Sleep Mode
  requires:
  - uart_bus
  - tuya_hub
- id: switch_tuya_2
  component_id: switch.tuya
  fields:
    switch_datapoint: 104
    id: switch_tuya_2
    name: Electriq air con Oscillating air paddle
  requires:
  - uart_bus
  - tuya_hub
source:
  type: esphome-devices
  remote_id: Electriq-IQoolsmart12hp-air-conditioner
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Electriq-IQoolsmart12hp-air-conditioner/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: d9ffd8072434ce2a2743089215cfe12d2677b19517a7b128cc0912c57af3ef7d
