id: zemismart_bulb_br30
name: Zemismart 7W BR30 Bulb
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Zemismart-Bulb-BR30/inside.jpg
pins:
- gpio: 13
  available: false
  occupied_by: my9231
- gpio: 15
  available: false
  occupied_by: my9231
docs_url: https://devices.esphome.io/devices/Zemismart-Bulb-BR30/
featured_components:
- id: my9231_hub
  component_id: my9231
  fields:
    data_pin:
      value: 13
      locked: true
    clock_pin:
      value: 15
      locked: true
    num_channels: 4
    num_chips: 1
- id: light_01
  component_id: light.rgbw
  fields:
    default_transition_length: 0s
    restore_mode: ALWAYS_ON
    red: output_red
    green: output_green
    blue: output_blue
    white: output_white
    id: light_01
    name: zemismart_bulb_br30_001_light
- id: output_white
  component_id: output.my9231
  fields:
    channel: 0
    id: output_white
  requires:
  - my9231_hub
- id: output_blue
  component_id: output.my9231
  fields:
    channel: 1
    id: output_blue
  requires:
  - my9231_hub
- id: output_green
  component_id: output.my9231
  fields:
    channel: 2
    id: output_green
  requires:
  - my9231_hub
- id: output_red
  component_id: output.my9231
  fields:
    channel: 3
    id: output_red
  requires:
  - my9231_hub
- id: sensor_wifi_signal_1
  component_id: sensor.wifi_signal
  fields:
    update_interval: 30s
    id: sensor_wifi_signal_1
    name: zemismart_bulb_br30_001_wifi_signal
- id: sensor_uptime_1
  component_id: sensor.uptime
  fields:
    update_interval: 120s
    id: sensor_uptime_1
    name: zemismart_bulb_br30_001_uptime
featured_bundles:
- id: light_01_setup
  name: zemismart_bulb_br30_001_light (full setup)
  component_ids:
  - my9231_hub
  - output_red
  - output_green
  - output_blue
  - output_white
  - light_01
source:
  type: esphome-devices
  remote_id: Zemismart-Bulb-BR30
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Zemismart-Bulb-BR30/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 0921cffe63546e0658a79783b707cafb5992b2c491a3810b0e7b016541cc0a62
