id: sinilink_xy_wpce
name: Sinilink PCIe Computer Remote (XY-WPCE)
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp8285
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Sinilink-XY-WPCE/sinilink_XY-WPCE.webp
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Sinilink-XY-WPCE/sinilink_XY-WPCE_pinout.webp
pins:
- gpio: 4
  available: false
  occupied_by: My PC WiFi Config Button
- gpio: 5
  available: false
  occupied_by: out_relay
- gpio: 10
  available: false
  occupied_by: My PC Case Button
- gpio: 12
  available: false
  occupied_by: My PC Power Status
docs_url: https://devices.esphome.io/devices/Sinilink-XY-WPCE/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 4
        mode: INPUT_PULLUP
        inverted: true
      locked: true
    id: binary_sensor_gpio_1
    name: My PC WiFi Config Button
- id: inp_power_status
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 12
        mode: INPUT_PULLUP
        inverted: true
      locked: true
    id: inp_power_status
    name: My PC Power Status
- id: binary_sensor_gpio_3
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 10
        mode: INPUT_PULLUP
        inverted: true
      locked: true
    id: binary_sensor_gpio_3
    name: My PC Case Button
- id: out_relay
  component_id: output.gpio
  fields:
    pin:
      value: 5
      locked: true
    id: out_relay
source:
  type: esphome-devices
  remote_id: Sinilink-XY-WPCE
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Sinilink-XY-WPCE/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: abb0dd5d77996a1cbf113c934b899605c183626abd5c9920b1774ce0dc9a6569
