id: homemate_4_gang_touch_switch
name: HomeMate 4 Gang Touch Switch
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: cb3s
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/HomeMate-4-Gang-Touch-Switch/closeup.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/HomeMate-4-Gang-Touch-Switch/connection.jpg
pins:
- gpio: 20
  available: false
  occupied_by: HomeMate 4 Node Touch Button 3
- gpio: 22
  available: false
  occupied_by: HomeMate 4 Node Touch Button 4
- gpio: 24
  available: false
  occupied_by: HomeMate 4 Node Touch Button 2
- gpio: 26
  available: false
  occupied_by: HomeMate 4 Node Touch Button 1
docs_url: https://devices.esphome.io/devices/HomeMate-4-Gang-Touch-Switch/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 26
        mode: INPUT_PULLUP
      locked: true
    entity_category: diagnostic
    disabled_by_default: true
    id: binary_sensor_gpio_1
    name: HomeMate 4 Node Touch Button 1
- id: binary_sensor_gpio_2
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 24
        mode: INPUT_PULLUP
      locked: true
    entity_category: diagnostic
    disabled_by_default: true
    id: binary_sensor_gpio_2
    name: HomeMate 4 Node Touch Button 2
- id: binary_sensor_gpio_3
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 20
        mode: INPUT_PULLUP
      locked: true
    entity_category: diagnostic
    disabled_by_default: true
    id: binary_sensor_gpio_3
    name: HomeMate 4 Node Touch Button 3
- id: binary_sensor_gpio_4
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 22
        mode: INPUT_PULLUP
      locked: true
    entity_category: diagnostic
    disabled_by_default: true
    id: binary_sensor_gpio_4
    name: HomeMate 4 Node Touch Button 4
- id: binary_sensor_status_1
  component_id: binary_sensor.status
  fields:
    entity_category: diagnostic
    id: binary_sensor_status_1
    name: HomeMate 4 Node Touch Status
source:
  type: esphome-devices
  remote_id: HomeMate-4-Gang-Touch-Switch
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/HomeMate-4-Gang-Touch-Switch/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 1f5c8d688bf091c5dd33138c68fb9ad1ee89bb54970c0caca75bf592a8911200
