id: lsps5_tuya_1_2_3_gang_switch
name: LSPS5 Tuya Switch 1-2-3 Gang No Neutral
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: generic-bk7231n-qfn32-tuya
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/LSPS5-Tuya-1-2-3-Gang-Switch/front.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/LSPS5-Tuya-1-2-3-Gang-Switch/back.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/LSPS5-Tuya-1-2-3-Gang-Switch/pcb.jpg
pins:
- gpio: 8
  available: false
  occupied_by: 1gang-switch Switch 1
- gpio: 26
  available: false
  occupied_by: 1gang-switch Button 1
docs_url: https://devices.esphome.io/devices/LSPS5-Tuya-1-2-3-Gang-Switch/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 26
        mode: INPUT_PULLUP
        inverted: true
      locked: true
    id: binary_sensor_gpio_1
    name: 1gang-switch Button 1
- id: sensor_uptime_1
  component_id: sensor.uptime
  fields:
    update_interval: 60s
    id: sensor_uptime_1
    name: 1gang-switch Uptime
- id: relay_1
  component_id: switch.gpio
  fields:
    pin:
      value: 8
      locked: true
    id: relay_1
    name: 1gang-switch Switch 1
source:
  type: esphome-devices
  remote_id: LSPS5-Tuya-1-2-3-Gang-Switch
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/LSPS5-Tuya-1-2-3-Gang-Switch/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: ab45ab9fa63a29c67da18e86329061891ea3d0bc5780fc055d5c8f24ac753a98
