id: holman_4x34mm_spotlight
name: Holman 4x34mm Spotlight
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: generic-bk7231n-qfn32-tuya
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Holman-4x34mm-spotlight/led.jpg
pins:
- gpio: 16
  available: false
  occupied_by: Light
- gpio: 20
  available: false
  occupied_by: LED_button
docs_url: https://devices.esphome.io/devices/Holman-4x34mm-spotlight/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 20
        inverted: true
        mode:
          input: true
          pullup: true
      locked: true
    id: binary_sensor_gpio_1
    name: LED_button
- id: rgb_led
  component_id: light.beken_spi_led_strip
  fields:
    rgb_order: RGB
    pin:
      value: 16
      locked: true
    num_leds: 5
    chipset: ws2812
    is_wrgb: true
    id: rgb_led
    name: Light
source:
  type: esphome-devices
  remote_id: Holman-4x34mm-spotlight
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Holman-4x34mm-spotlight/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: e3ad0b926346fa2057d839e2f276d1a862916d8278d5867484edb2f468e80bc9
