id: guition_esp32_p4_m3_dev
name: Guition ESP32-P4-M3-Dev
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32-p4-evboard
  variant: esp32p4
  framework: esp-idf
  logger_hardware_uart: USB_SERIAL_JTAG
hardware:
  connectivity:
  - ethernet
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Guition-ESP32-P4-M3-Dev/guition_jc_esp32_p4_m3_dev.webp
pins:
- gpio: 31
  available: false
  occupied_by: Ethernet MDC
- gpio: 50
  available: false
  occupied_by: Ethernet CLK
- gpio: 51
  available: false
  occupied_by: Ethernet Power
- gpio: 52
  available: false
  occupied_by: Ethernet MDIO
docs_url: https://devices.esphome.io/devices/Guition-ESP32-P4-M3-Dev/
featured_components:
- id: onboard_ethernet
  component_id: ethernet
  name: Onboard Ethernet
  fields:
    type:
      value: IP101
      locked: true
    mdc_pin:
      value: GPIO31
      locked: true
    mdio_pin:
      value: GPIO52
      locked: true
    power_pin:
      value: GPIO51
      locked: true
    clk:
      value:
        mode: CLK_EXT_IN
        pin: GPIO50
      locked: true
    phy_addr:
      value: 1
      locked: true
source:
  type: esphome-devices
  remote_id: Guition-ESP32-P4-M3-Dev
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Guition-ESP32-P4-M3-Dev/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 060bd95535fb0b0572cf92d3882c34636b45f597097fd4f54500e7e3bfd63869
