id: kincony_b4
name: KinCony-B4 (ESP32-S3 4CH Relay board)
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework: arduino
  logger_hardware_uart: USB_SERIAL_JTAG
hardware:
  connectivity:
  - wifi
  - bluetooth
  - ethernet
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KinCony-B4/B4-1.jpg
tags:
- relay
pins:
- gpio: 0
  available: false
  occupied_by: b4-0
- gpio: 1
  available: false
  occupied_by: Ethernet CLK
- gpio: 2
  available: false
  occupied_by: Ethernet MOSI
- gpio: 8
  available: false
  occupied_by: bus_a
- gpio: 13
  available: false
  occupied_by: b4-13
- gpio: 14
  available: false
  occupied_by: b4-14
- gpio: 17
  available: false
  occupied_by: b4-W1-io17
- gpio: 18
  available: false
  occupied_by: bus_a
- gpio: 21
  available: false
  occupied_by: b4-21
- gpio: 38
  available: false
  occupied_by: uart_1
- gpio: 39
  available: false
  occupied_by: uart_1
- gpio: 40
  available: false
  occupied_by: b4-W1-io40
- gpio: 41
  available: false
  occupied_by: Ethernet MISO
- gpio: 42
  available: false
  occupied_by: Ethernet CS
- gpio: 43
  available: false
  occupied_by: Ethernet INT
- gpio: 44
  available: false
  occupied_by: Ethernet RESET
- gpio: 47
  available: false
  occupied_by: b4-W1-io47
- gpio: 48
  available: false
  occupied_by: b4-W1-io48
docs_url: https://devices.esphome.io/devices/KinCony-B4/
featured_components:
- id: uart_1
  component_id: uart
  fields:
    baud_rate: 9600
    debug:
      value:
        direction: BOTH
        dummy_receiver: true
        after:
          timeout: 10ms
      locked: true
    tx_pin:
      value: 38
      locked: true
    rx_pin:
      value: 39
      locked: true
    id:
      value: uart_1
      locked: true
- id: ads1115_hub
  component_id: ads1115
  fields:
    address: 72
  requires:
  - bus_a
- id: bus_a
  component_id: i2c
  fields:
    sda:
      value: 8
      locked: true
    scl:
      value: 18
      locked: true
    scan: true
    frequency: 400kHz
    id:
      value: bus_a
      locked: true
- id: pcf8574_hub_out_1
  component_id: pcf8574
  fields:
    address: 36
    id:
      value: pcf8574_hub_out_1
      locked: true
    i2c_id:
      value: bus_a
      locked: true
  requires:
  - bus_a
- id: onboard_ethernet
  component_id: ethernet
  name: Onboard Ethernet
  fields:
    type:
      value: W5500
      locked: true
    clk_pin:
      value: GPIO1
      locked: true
    mosi_pin:
      value: GPIO2
      locked: true
    miso_pin:
      value: GPIO41
      locked: true
    cs_pin:
      value: GPIO42
      locked: true
    interrupt_pin:
      value: GPIO43
      locked: true
    reset_pin:
      value: GPIO44
      locked: true
- id: b4_input01
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 0
        mode: INPUT
        inverted: true
      locked: true
    id: b4_input01
    name: b4-input01
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: b4_input02
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 1
        mode: INPUT
        inverted: true
      locked: true
    id: b4_input02
    name: b4-input02
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: b4_input03
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 2
        mode: INPUT
        inverted: true
      locked: true
    id: b4_input03
    name: b4-input03
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: b4_input04
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 3
        mode: INPUT
        inverted: true
      locked: true
    id: b4_input04
    name: b4-input04
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: binary_sensor_gpio_5
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 47
        inverted: true
      locked: true
    id: binary_sensor_gpio_5
    name: b4-W1-io47
- id: binary_sensor_gpio_6
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 48
        inverted: true
      locked: true
    id: binary_sensor_gpio_6
    name: b4-W1-io48
- id: binary_sensor_gpio_7
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 17
        inverted: true
      locked: true
    id: binary_sensor_gpio_7
    name: b4-W1-io17
- id: binary_sensor_gpio_8
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 40
        inverted: true
      locked: true
    id: binary_sensor_gpio_8
    name: b4-W1-io40
- id: binary_sensor_gpio_9
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 13
        inverted: false
      locked: true
    id: binary_sensor_gpio_9
    name: b4-13
- id: binary_sensor_gpio_10
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 14
        inverted: false
      locked: true
    id: binary_sensor_gpio_10
    name: b4-14
- id: binary_sensor_gpio_11
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 21
        inverted: false
      locked: true
    id: binary_sensor_gpio_11
    name: b4-21
- id: binary_sensor_gpio_12
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 0
        inverted: false
      locked: true
    id: binary_sensor_gpio_12
    name: b4-0
- id: sensor_ads1115_1
  component_id: sensor.ads1115
  fields:
    multiplexer: A0_GND
    gain: 6.144
    resolution: 16_BITS
    update_interval: 5s
    id: sensor_ads1115_1
    name: ADS1115 Channel A0-GND
  requires:
  - bus_a
  - ads1115_hub
- id: sensor_ads1115_2
  component_id: sensor.ads1115
  fields:
    multiplexer: A1_GND
    gain: 6.144
    update_interval: 5s
    id: sensor_ads1115_2
    name: ADS1115 Channel A1-GND
  requires:
  - bus_a
  - ads1115_hub
- id: sensor_ads1115_3
  component_id: sensor.ads1115
  fields:
    multiplexer: A2_GND
    gain: 6.144
    update_interval: 5s
    id: sensor_ads1115_3
    name: ADS1115 Channel A2-GND
  requires:
  - bus_a
  - ads1115_hub
- id: sensor_ads1115_4
  component_id: sensor.ads1115
  fields:
    multiplexer: A3_GND
    gain: 6.144
    update_interval: 5s
    id: sensor_ads1115_4
    name: ADS1115 Channel A3-GND
  requires:
  - bus_a
  - ads1115_hub
- id: switch_uart_1
  component_id: switch.uart
  fields:
    data:
      value:
      - 17
      - 34
      - 51
      - 68
      - 85
      locked: true
    id: switch_uart_1
    name: RS485 Button
    uart_id:
      value: uart_1
      locked: true
  requires:
  - uart_1
- id: b4_output01
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 4
        mode: OUTPUT
        inverted: true
      locked: true
    id: b4_output01
    name: b4-output01
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: b4_output02
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 5
        mode: OUTPUT
        inverted: true
      locked: true
    id: b4_output02
    name: b4-output02
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: b4_output03
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 6
        mode: OUTPUT
        inverted: true
      locked: true
    id: b4_output03
    name: b4-output03
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: b4_output04
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 7
        mode: OUTPUT
        inverted: true
      locked: true
    id: b4_output04
    name: b4-output04
  requires:
  - bus_a
  - pcf8574_hub_out_1
source:
  type: esphome-devices
  remote_id: KinCony-B4
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/KinCony-B4/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: b47b7bffb76dd1b87045431ebed676032c9c5bad37fa82d70277c93ad62e9c16
