id: horus_blind_controller
name: Horus - Blind Controller
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Horus-Blind-Controller/module.png
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Horus-Blind-Controller/bottom-top-vew.png
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Horus-Blind-Controller/Wire-diagram.png
pins:
- gpio: 4
  available: false
  occupied_by: button_open_1
- gpio: 5
  available: false
  occupied_by: button_close_1
- gpio: 13
  available: false
  occupied_by: output_cover_close
- gpio: 14
  available: false
  occupied_by: output_cover_open
docs_url: https://devices.esphome.io/devices/Horus-Blind-Controller/
featured_components:
- id: button_open_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 4
        mode: INPUT_PULLUP
        inverted: true
      locked: true
    filters:
      value:
      - delayed_on: 50ms
      - delayed_off: 50ms
      locked: true
    id: button_open_1
    name: button_open_1
- id: button_close_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 5
        mode: INPUT_PULLUP
        inverted: true
      locked: true
    filters:
      value:
      - delayed_on: 50ms
      - delayed_off: 50ms
      locked: true
    id: button_close_1
    name: button_close_1
- id: output_cover_open
  component_id: switch.gpio
  fields:
    pin:
      value:
        number: 14
        mode: OUTPUT
        inverted: false
      locked: true
    id: output_cover_open
    name: output_cover_open
- id: output_cover_close
  component_id: switch.gpio
  fields:
    pin:
      value:
        number: 13
        mode: OUTPUT
        inverted: false
      locked: true
    id: output_cover_close
    name: output_cover_close
source:
  type: esphome-devices
  remote_id: Horus-Blind-Controller
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Horus-Blind-Controller/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 5724028cf005532c2e617d71f3785af67188a6817aea78306d4525b26311afe8
