id: maxcio_rmc020
name: Maxcio RMC020 IT
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Maxcio-RMC020/MaxcioRMC020.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Maxcio-RMC020/MaxcioRMC020retro.jpg
tags:
- relay
- compact
pins:
- gpio: 4
  available: false
  occupied_by: sensor.hlw8012
- gpio: 5
  available: false
  occupied_by: sensor.hlw8012
- gpio: 12
  available: false
  occupied_by: sensor.hlw8012
- gpio: 13
  available: false
  occupied_by: maxcio_red_output
- gpio: 14
  available: false
  occupied_by: Smart Plug Maxcio
docs_url: https://devices.esphome.io/devices/Maxcio-RMC020/
featured_components:
- id: maxcio_red_led
  component_id: light.monochromatic
  fields:
    output: maxcio_red_output
    id: maxcio_red_led
    name: Smart Plug Maxcio Light
- id: maxcio_red_output
  component_id: output.esp8266_pwm
  fields:
    pin:
      value:
        number: 13
        inverted: true
      locked: true
    id: maxcio_red_output
- id: sensor_uptime_1
  component_id: sensor.uptime
  fields:
    filters:
      value:
      - lambda: return x / 60.0;
      locked: true
    unit_of_measurement: minutes
    id: sensor_uptime_1
    name: Smart Plug Maxcio Uptime
- id: sensor_wifi_signal_1
  component_id: sensor.wifi_signal
  fields:
    update_interval: 60s
    id: sensor_wifi_signal_1
    name: Smart Plug Maxcio Wifi Signal
- id: sensor_hlw8012_1
  component_id: sensor.hlw8012
  fields:
    sel_pin:
      value:
        number: 12
        inverted: true
      locked: true
    cf_pin:
      value: 4
      locked: true
    cf1_pin:
      value: 5
      locked: true
    change_mode_every: 8
    update_interval: 10s
    current_resistor: '0.002501592'
    voltage_divider: '803.2'
    id: sensor_hlw8012_1
- id: relay
  component_id: switch.gpio
  fields:
    pin:
      value: 14
      locked: true
    restore_mode: ALWAYS_OFF
    id: relay
    name: Smart Plug Maxcio
featured_bundles:
- id: maxcio_red_led_setup
  name: Smart Plug Maxcio Light (full setup)
  component_ids:
  - maxcio_red_output
  - maxcio_red_led
source:
  type: esphome-devices
  remote_id: Maxcio-RMC020
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Maxcio-RMC020/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 8837481612b75328b64e2949e53e309544546e1971658c2e6bcd3a0fba04193a
