id: sinilink_xy_wfusb_usb_switch_relay
name: Sinilink XY-WFUSB USB Switch Relay
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Sinilink-XY-WFUSB-USB-Switch-Relay/Sinilink.png
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Sinilink-XY-WFUSB-USB-Switch-Relay/Sinilink_bare.png
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Sinilink-XY-WFUSB-USB-Switch-Relay/wfusb_pinout.jpg
tags:
- relay
pins:
- gpio: 4
  available: false
  occupied_by: hardware_button
- gpio: 5
  available: false
  occupied_by: switch_relay
- gpio: 14
  available: false
  occupied_by: green_led
docs_url: https://devices.esphome.io/devices/Sinilink-XY-WFUSB-USB-Switch-Relay/
featured_components:
- id: hardware_button
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 4
        mode: INPUT_PULLUP
        inverted: true
      locked: true
    id: hardware_button
    name: hardware_button
- id: sensor_wifi_signal_1
  component_id: sensor.wifi_signal
  fields:
    update_interval: 60s
    id: sensor_wifi_signal_1
    name: WiFi Status
- id: switch_relay
  component_id: switch.gpio
  fields:
    pin:
      value: 5
      locked: true
    id: switch_relay
    name: switch_relay
- id: green_led
  component_id: switch.gpio
  fields:
    pin:
      value: 14
      locked: true
    inverted:
      value: true
      locked: true
    id: green_led
    name: green_led
source:
  type: esphome-devices
  remote_id: Sinilink-XY-WFUSB-USB-Switch-Relay
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Sinilink-XY-WFUSB-USB-Switch-Relay/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 7df574f2097b9ea9afabd1372f525c4be48aea5d6234453b0c7bde098f13b85a
