id: kogan_smarterhome_smart_plug_energy_meter_5v_24a_usb_ports
name: Kogan SmarterHome Smart Plug With Energy Meter and 5V 2.4A USB Ports
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp8285
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Kogan-Smarterhome-Smart-Plug-Energy-Meter-5v-24a-Usb-Ports/kogan-smarterhome-smart-plug-energy-meter-5v-24a-usb-ports.jpg
tags:
- relay
- compact
pins:
- gpio: 3
  available: false
  occupied_by: kogan_plug_1_button
- gpio: 4
  available: false
  occupied_by: sensor.hlw8012
- gpio: 5
  available: false
  occupied_by: sensor.hlw8012
- gpio: 12
  available: false
  occupied_by: sensor.hlw8012
- gpio: 13
  available: false
  occupied_by: led
- gpio: 14
  available: false
  occupied_by: kogan_plug_1_plug
docs_url: https://devices.esphome.io/devices/Kogan-Smarterhome-Smart-Plug-Energy-Meter-5v-24a-Usb-Ports/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 3
        mode: INPUT_PULLUP
        inverted: true
      locked: true
    id: binary_sensor_gpio_1
    name: kogan_plug_1_button
- id: sensor_hlw8012_1
  component_id: sensor.hlw8012
  fields:
    sel_pin:
      value:
        number: 12
        inverted: true
      locked: true
    cf_pin:
      value: 4
      locked: true
    cf1_pin:
      value: 5
      locked: true
    current_resistor: '0.00225'
    voltage_divider: '805'
    change_mode_every: 8
    update_interval: 15s
    id: sensor_hlw8012_1
- id: led
  component_id: switch.gpio
  fields:
    pin:
      value:
        number: 13
        inverted: true
      locked: true
    id: led
    name: led
- id: relay
  component_id: switch.gpio
  fields:
    pin:
      value: 14
      locked: true
    icon: mdi:power-socket-au
    restore_mode: ALWAYS_ON
    id: relay
    name: kogan_plug_1_plug
source:
  type: esphome-devices
  remote_id: Kogan-Smarterhome-Smart-Plug-Energy-Meter-5v-24a-Usb-Ports
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Kogan-Smarterhome-Smart-Plug-Energy-Meter-5v-24a-Usb-Ports/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 9cfc5931c82f456be50e420afbf722690aeac8d2c37e62b8caa1f2841f4db4cc
