id: kincony_adr
name: KinCony-ADR (AC Dimmer)
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32dev
  variant: esp32
  framework: arduino
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KinCony-ADR/esp32-ac-dimmer-adr-1.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KinCony-ADR/ADR-lamp.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KinCony-ADR/ADR-fan.jpg
pins:
- gpio: 25
  available: false
  occupied_by: dimmer1
- gpio: 33
  available: false
  occupied_by: dimmer1
docs_url: https://devices.esphome.io/devices/KinCony-ADR/
featured_components:
- id: light_monochromatic_1
  component_id: light.monochromatic
  fields:
    default_transition_length: 100ms
    output: dimmer1
    id: light_monochromatic_1
    name: adr_lamp
- id: dimmer1
  component_id: output.ac_dimmer
  fields:
    gate_pin:
      value: 33
      locked: true
    zero_cross_pin:
      value:
        number: 25
        mode:
          input: true
        inverted: false
      locked: true
    min_power: 35%
    id: dimmer1
featured_bundles:
- id: light_monochromatic_1_setup
  name: adr_lamp (full setup)
  component_ids:
  - dimmer1
  - light_monochromatic_1
source:
  type: esphome-devices
  remote_id: KinCony-ADR
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/KinCony-ADR/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 4c3faf789ad481696178569c8c2b4708fb31fadd9a484a1a1261bf8aacbc84f9
