id: sonoff_minir4m
name: Sonoff Mini R4M
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework: arduino
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Sonoff-MINIR4M/sonoff-mini-r4m.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Sonoff-MINIR4M/view_top.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Sonoff-MINIR4M/view_side.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Sonoff-MINIR4M/view_ic.jpg
tags:
- relay
- sonoff
pins:
- gpio: 4
  available: false
  occupied_by: relay_1
- gpio: 5
  available: false
  occupied_by: s1
- gpio: 9
  available: false
  occupied_by: button
- gpio: 19
  available: false
  occupied_by: status_led_output
docs_url: https://devices.esphome.io/devices/Sonoff-MINIR4M/
featured_components:
- id: button
  component_id: binary_sensor.gpio
  fields:
    pin:
      value: 9
      locked: true
    filters:
      value:
      - invert: null
      - delayed_off: 50ms
      locked: true
    id: button
    name: button
- id: s1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value: 5
      locked: true
    filters:
      value:
      - invert: null
      - delayed_off: 50ms
      locked: true
    id: s1
    name: s1
- id: light_1
  component_id: light.binary
  fields:
    icon: mdi:ceiling-light-multiple-outline
    restore_mode: restore_default_off
    output: relay_1
    id: light_1
    name: light_1
- id: relay_1
  component_id: output.gpio
  fields:
    pin:
      value: 4
      locked: true
    id: relay_1
- id: status_led_output
  component_id: output.gpio
  fields:
    pin:
      value: 19
      locked: true
    inverted:
      value: true
      locked: true
    id: status_led_output
featured_bundles:
- id: light_1_setup
  name: light_1 (full setup)
  component_ids:
  - relay_1
  - light_1
source:
  type: esphome-devices
  remote_id: Sonoff-MINIR4M
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Sonoff-MINIR4M/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 65168d49ea9ec9bb1b98bcf8076fac94f6ecf3e343a5532a06c6bd1092cdcc89
