id: arlec_gridconnect_smart_plug_pc190ha
name: Arlec Grid Connect Smart Plug PC190HA
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Arlec-GridConnect-Smart-Plug-PC190HA/PC190HA.png
tags:
- relay
- compact
pins:
- gpio: 4
  available: false
  occupied_by: blue_led
- gpio: 12
  available: false
  occupied_by: Arlec Smart Plug Power
- gpio: 13
  available: false
  occupied_by: red_led
- gpio: 14
  available: false
  occupied_by: Arlec Smart Plug Button
docs_url: https://devices.esphome.io/devices/Arlec-GridConnect-Smart-Plug-PC190HA/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 14
        mode:
          input: true
          pullup: true
        inverted: true
      locked: true
    id: binary_sensor_gpio_1
    name: Arlec Smart Plug Button
- id: blue_led
  component_id: switch.gpio
  fields:
    pin:
      value:
        number: 4
        inverted: true
      locked: true
    id: blue_led
    name: blue_led
- id: red_led
  component_id: switch.gpio
  fields:
    pin:
      value:
        number: 13
        inverted: true
      locked: true
    id: red_led
    name: red_led
- id: relay
  component_id: switch.gpio
  fields:
    pin:
      value: 12
      locked: true
    id: relay
    name: Arlec Smart Plug Power
source:
  type: esphome-devices
  remote_id: Arlec-GridConnect-Smart-Plug-PC190HA
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Arlec-GridConnect-Smart-Plug-PC190HA/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 30ca79595b88edcc40e3a8f2b162f96298d6da82117c543fa0c7c143fdcb45f0
