id: anwio_a19_e26_rgbww_8_5w_light_bulb
name: Anwio A19 E26 RGBWW 8.5 Watt Light Bulb
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: wb3l
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Anwio-A19-E26-RGBWW-8.5W-Light-Bulb/anwio-a19-top-down.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Anwio-A19-E26-RGBWW-8.5W-Light-Bulb/anwio-a19-board-view.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Anwio-A19-E26-RGBWW-8.5W-Light-Bulb/anwio-a19-board-view-2.jpg
pins:
- gpio: 6
  available: false
  occupied_by: sm2135
- gpio: 7
  available: false
  occupied_by: sm2135
docs_url: https://devices.esphome.io/devices/Anwio-A19-E26-RGBWW-8.5W-Light-Bulb/
featured_components:
- id: sm2135_hub
  component_id: sm2135
  fields:
    data_pin:
      value: 6
      locked: true
    clock_pin:
      value: 7
      locked: true
    separate_modes: false
    cw_current: 30mA
    rgb_current: 20mA
- id: bar_pendant_left
  component_id: light.rgbww
  fields:
    color_interlock: true
    cold_white_color_temperature: 6200K
    warm_white_color_temperature: 2000K
    red: output_red
    green: output_green
    blue: output_blue
    warm_white: warm_white
    cold_white: cold_white
    id: bar_pendant_left
    name: Light
- id: output_blue
  component_id: output.sm2135
  fields:
    channel: 0
    id: output_blue
  requires:
  - sm2135_hub
- id: output_green
  component_id: output.sm2135
  fields:
    channel: 1
    id: output_green
  requires:
  - sm2135_hub
- id: output_red
  component_id: output.sm2135
  fields:
    channel: 2
    id: output_red
  requires:
  - sm2135_hub
- id: warm_white
  component_id: output.sm2135
  fields:
    channel: 3
    id: warm_white
  requires:
  - sm2135_hub
- id: cold_white
  component_id: output.sm2135
  fields:
    channel: 4
    id: cold_white
  requires:
  - sm2135_hub
- id: sensor_uptime_1
  component_id: sensor.uptime
  fields:
    device_class: duration
    id: sensor_uptime_1
    name: Uptime
featured_bundles:
- id: bar_pendant_left_setup
  name: Light (full setup)
  component_ids:
  - sm2135_hub
  - output_red
  - output_green
  - output_blue
  - warm_white
  - cold_white
  - bar_pendant_left
source:
  type: esphome-devices
  remote_id: Anwio-A19-E26-RGBWW-8.5W-Light-Bulb
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Anwio-A19-E26-RGBWW-8.5W-Light-Bulb/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 21040773679ebc76ea0483d93b69f502fd5c0a8546364ffd1fcf6d61e520e948
