id: kincony_dm16
name: KinCony-DM16 (ESP32-S3 16CH Dimmer board)
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework: arduino
hardware:
  connectivity:
  - wifi
  - bluetooth
  - ethernet
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KinCony-DM16/DM16-1.jpg
pins:
- gpio: 1
  available: false
  occupied_by: Ethernet CLK
- gpio: 2
  available: false
  occupied_by: Ethernet MOSI
- gpio: 8
  available: false
  occupied_by: bus_a
- gpio: 18
  available: false
  occupied_by: bus_a
- gpio: 41
  available: false
  occupied_by: Ethernet MISO
- gpio: 42
  available: false
  occupied_by: Ethernet CS
- gpio: 43
  available: false
  occupied_by: Ethernet INT
- gpio: 44
  available: false
  occupied_by: Ethernet RESET
docs_url: https://devices.esphome.io/devices/KinCony-DM16/
featured_components:
- id: ads1115_hub
  component_id: ads1115
  fields:
    address: 72
  requires:
  - bus_a
- id: bus_a
  component_id: i2c
  fields:
    sda:
      value: 8
      locked: true
    scl:
      value: 18
      locked: true
    scan: true
    frequency: 400kHz
    id:
      value: bus_a
      locked: true
- id: pcf8574_hub_in_1
  component_id: pcf8574
  fields:
    address: 34
    pcf8575: true
    id:
      value: pcf8574_hub_in_1
      locked: true
    i2c_id:
      value: bus_a
      locked: true
  requires:
  - bus_a
- id: onboard_ethernet
  component_id: ethernet
  name: Onboard Ethernet
  fields:
    type:
      value: W5500
      locked: true
    clk_pin:
      value: GPIO1
      locked: true
    mosi_pin:
      value: GPIO2
      locked: true
    miso_pin:
      value: GPIO41
      locked: true
    cs_pin:
      value: GPIO42
      locked: true
    interrupt_pin:
      value: GPIO43
      locked: true
    reset_pin:
      value: GPIO44
      locked: true
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 8
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_1
    name: dm16-input01
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_2
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 9
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_2
    name: dm16-input02
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_3
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 10
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_3
    name: dm16-input03
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_4
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 11
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_4
    name: dm16-input04
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_5
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 12
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_5
    name: dm16-input05
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_6
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 13
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_6
    name: dm16-input06
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_7
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 14
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_7
    name: dm16-input07
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_8
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 15
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_8
    name: dm16-input08
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_9
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 0
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_9
    name: dm16-input09
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_10
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 1
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_10
    name: dm16-input10
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_11
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 2
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_11
    name: dm16-input11
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_12
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 3
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_12
    name: dm16-input12
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_13
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 4
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_13
    name: dm16-input13
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_14
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 5
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_14
    name: dm16-input14
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_15
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 6
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_15
    name: dm16-input15
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_16
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 7
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_16
    name: dm16-input16
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: sensor_ads1115_1
  component_id: sensor.ads1115
  fields:
    multiplexer: A0_GND
    gain: 6.144
    resolution: 16_BITS
    update_interval: 5s
    id: sensor_ads1115_1
    name: ADS1115 Channel A0-GND
  requires:
  - bus_a
  - ads1115_hub
- id: sensor_ads1115_2
  component_id: sensor.ads1115
  fields:
    multiplexer: A1_GND
    gain: 6.144
    update_interval: 5s
    id: sensor_ads1115_2
    name: ADS1115 Channel A1-GND
  requires:
  - bus_a
  - ads1115_hub
- id: sensor_ads1115_3
  component_id: sensor.ads1115
  fields:
    multiplexer: A2_GND
    gain: 6.144
    update_interval: 5s
    id: sensor_ads1115_3
    name: ADS1115 Channel A2-GND
  requires:
  - bus_a
  - ads1115_hub
- id: sensor_ads1115_4
  component_id: sensor.ads1115
  fields:
    multiplexer: A3_GND
    gain: 6.144
    update_interval: 5s
    id: sensor_ads1115_4
    name: ADS1115 Channel A3-GND
  requires:
  - bus_a
  - ads1115_hub
source:
  type: esphome-devices
  remote_id: KinCony-DM16
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/KinCony-DM16/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 716181281df1844805aa6fb878c0f92ed5c9f87865cffbe8de4a643b3caf2f57
