id: smartpoint_wifi_smart_remote_controller
name: Smartpoint Wifi Smart Remote Controller
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Smartpoint-Wifi-Smart-Remote-Controller/smartpoint_wifi_smart_remote_controller.jpeg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Smartpoint-Wifi-Smart-Remote-Controller/top-removed.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Smartpoint-Wifi-Smart-Remote-Controller/underside.jpg
pins:
- gpio: 13
  available: false
  occupied_by: Underside Button
docs_url: https://devices.esphome.io/devices/Smartpoint-Wifi-Smart-Remote-Controller/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 13
        inverted: true
      locked: true
    id: binary_sensor_gpio_1
    name: Underside Button
source:
  type: esphome-devices
  remote_id: Smartpoint-Wifi-Smart-Remote-Controller
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Smartpoint-Wifi-Smart-Remote-Controller/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 402ce4b30eb47119c2c5072294f9c346762e40c4a030647f0b4976b255e89623
