id: deta_10w_940lm_grid_connect_smart_led_downlight
name: Deta 10W 940lm Grid Connect Smart LED RGB CWWW Downlight (DET902HA)
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Deta-10W-940lm-Grid-Connect-Smart-LED-Downlight/Deta-10W-940lm-Grid-Connect-Smart-LED-Downlight.jpg
pins:
- gpio: 4
  available: false
  occupied_by: output_g
- gpio: 5
  available: false
  occupied_by: output_r
- gpio: 12
  available: false
  occupied_by: output_ww
- gpio: 13
  available: false
  occupied_by: output_b
- gpio: 14
  available: false
  occupied_by: output_cw
docs_url: https://devices.esphome.io/devices/Deta-10W-940lm-Grid-Connect-Smart-LED-Downlight/
featured_components:
- id: light_rgbww_1
  component_id: light.rgbww
  fields:
    color_interlock: true
    cold_white_color_temperature: 5700 K
    warm_white_color_temperature: 3000 K
    red: output_r
    green: output_g
    blue: output_b
    warm_white: output_ww
    cold_white: output_cw
    id: light_rgbww_1
    name: Master Bedroom Light 1
- id: output_g
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 4
      locked: true
    id: output_g
- id: output_r
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 5
      locked: true
    id: output_r
- id: output_ww
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 12
      locked: true
    id: output_ww
- id: output_b
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 13
      locked: true
    id: output_b
- id: output_cw
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 14
      locked: true
    id: output_cw
featured_bundles:
- id: light_rgbww_1_setup
  name: Master Bedroom Light 1 (full setup)
  component_ids:
  - output_r
  - output_g
  - output_b
  - output_ww
  - output_cw
  - light_rgbww_1
source:
  type: esphome-devices
  remote_id: Deta-10W-940lm-Grid-Connect-Smart-LED-Downlight
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Deta-10W-940lm-Grid-Connect-Smart-LED-Downlight/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: b56c80588b47b334a06aa5925bf67ef7be7b99336e28cd338e9bc0a4fcd48ff5
