id: blitzwolf_bw_shp6
name: Blitzwolf BW-SHP6 Socket with powermonitoring
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp8285
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/BlitzWolf-BW-SHP6/BlitzWolf-BW-SHP6.jpg
tags:
- relay
- compact
pins:
- gpio: 0
  available: false
  occupied_by: led
- gpio: 5
  available: false
  occupied_by: sensor.hlw8012
- gpio: 12
  available: false
  occupied_by: sensor.hlw8012
- gpio: 13
  available: false
  occupied_by: shp6 button
- gpio: 14
  available: false
  occupied_by: sensor.hlw8012
- gpio: 15
  available: false
  occupied_by: shp6 Relay
docs_url: https://devices.esphome.io/devices/BlitzWolf-BW-SHP6/
featured_components:
- id: button
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 13
        inverted: true
      locked: true
    id: button
    name: shp6 button
- id: led
  component_id: output.gpio
  fields:
    pin:
      value: 0
      locked: true
    inverted:
      value: true
      locked: true
    id: led
- id: sensor_hlw8012_1
  component_id: sensor.hlw8012
  fields:
    sel_pin:
      value:
        number: 12
        inverted: true
      locked: true
    cf_pin:
      value: 5
      locked: true
    cf1_pin:
      value: 14
      locked: true
    current_resistor: '0.00290'
    voltage_divider: '940'
    change_mode_every: 4
    update_interval: 10s
    id: sensor_hlw8012_1
- id: relay
  component_id: switch.gpio
  fields:
    pin:
      value: 15
      locked: true
    restore_mode: RESTORE_DEFAULT_OFF
    id: relay
    name: shp6 Relay
source:
  type: esphome-devices
  remote_id: BlitzWolf-BW-SHP6
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/BlitzWolf-BW-SHP6/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 4e9549c9b58ad5fbdbef3544e86906895707867d206e55265d5dfec595ed7b20
