id: ktnnkg_wifi_kg2201_w
name: KTNNKG Wifi-KG2201-W
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KTNNKG-Wifi-KG2201-W/top.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KTNNKG-Wifi-KG2201-W/inside-top.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KTNNKG-Wifi-KG2201-W/inside-bottom.jpg
tags:
- relay
pins:
- gpio: 4
  available: false
  occupied_by: KTNNKG
- gpio: 12
  available: false
  occupied_by: KTNNKG Button
- gpio: 13
  available: false
  occupied_by: redLED
docs_url: https://devices.esphome.io/devices/KTNNKG-Wifi-KG2201-W/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 12
        inverted: true
      locked: true
    internal: true
    id: binary_sensor_gpio_1
    name: KTNNKG Button
- id: relay
  component_id: switch.gpio
  fields:
    pin:
      value: 4
      locked: true
    id: relay
    name: KTNNKG
- id: redled
  component_id: switch.gpio
  fields:
    internal: true
    pin:
      value: 13
      locked: true
    inverted:
      value: true
      locked: true
    id: redled
    name: redLED
source:
  type: esphome-devices
  remote_id: KTNNKG-Wifi-KG2201-W
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/KTNNKG-Wifi-KG2201-W/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 7bf8cb899b1bf2372360fa3d6bf4373150545cc306159f34e8a16ddc25c3215e
