id: ekf_rcs_2_wf
name: EKF Сonnect PRO Wi-Fi (RCS-2-WF) Smart Plug
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: cb2s
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/EKF-RCS-2-WF/0.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/EKF-RCS-2-WF/1.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/EKF-RCS-2-WF/3.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/EKF-RCS-2-WF/4.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/EKF-RCS-2-WF/5.jpg
tags:
- relay
- compact
pins:
- gpio: 6
  available: false
  occupied_by: sensor.hlw8012
- gpio: 7
  available: false
  occupied_by: Relay
- gpio: 8
  available: false
  occupied_by: sensor.hlw8012
- gpio: 10
  available: false
  occupied_by: Button
- gpio: 11
  available: false
  occupied_by: status
- gpio: 26
  available: false
  occupied_by: sensor.hlw8012
docs_url: https://devices.esphome.io/devices/EKF-RCS-2-WF/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 10
        inverted: true
      locked: true
    icon: mdi:gesture-tap-button
    id: binary_sensor_gpio_1
    name: Button
- id: status
  component_id: light.status_led
  fields:
    pin:
      value:
        number: 11
        inverted: true
      locked: true
    id: status
    name: status
- id: sensor_hlw8012_1
  component_id: sensor.hlw8012
  fields:
    model: BL0937
    cf_pin:
      value:
        number: 8
        inverted: true
      locked: true
    cf1_pin:
      value:
        number: 6
        inverted: true
      locked: true
    sel_pin:
      value:
        number: 26
        inverted: true
      locked: true
    update_interval: 10s
    voltage_divider: 800
    change_mode_every: 1
    current_resistor: 0.001 Ohm
    id: sensor_hlw8012_1
- id: relay
  component_id: switch.gpio
  fields:
    pin:
      value: 7
      locked: true
    icon: mdi:electric-switch
    id: relay
    name: Relay
source:
  type: esphome-devices
  remote_id: EKF-RCS-2-WF
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/EKF-RCS-2-WF/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 3019789105f2900d6086843ae567f8e66aea2c6088558ac1874b024e33729701
