id: umax_u_smart_wifi_plug_duo
name: UMAX U-Smart Wifi Plug Duo
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp8285
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/UMAX-U-Smart-Wifi-Plug-Duo/umax-wifi-plug-duo.jpeg
tags:
- relay
- compact
pins:
- gpio: 0
  available: false
  occupied_by: button2
- gpio: 4
  available: false
  occupied_by: sensor.hlw8012
- gpio: 5
  available: false
  occupied_by: sensor.hlw8012
- gpio: 12
  available: false
  occupied_by: sensor.hlw8012
- gpio: 14
  available: false
  occupied_by: umax - Switch1
- gpio: 15
  available: false
  occupied_by: umax - Switch2
docs_url: https://devices.esphome.io/devices/UMAX-U-Smart-Wifi-Plug-Duo/
featured_components:
- id: button2
  component_id: binary_sensor.gpio
  fields:
    internal: true
    pin:
      value:
        number: 0
        mode: INPUT_PULLUP
        inverted: true
      locked: true
    id: button2
    name: button2
- id: sensor_wifi_signal_1
  component_id: sensor.wifi_signal
  fields:
    update_interval: 60s
    id: sensor_wifi_signal_1
    name: umax - WiFi Signal
- id: sensor_uptime_1
  component_id: sensor.uptime
  fields:
    icon: mdi:clock-outline
    update_interval: 60s
    id: sensor_uptime_1
    name: umax - Uptime
- id: sensor_hlw8012_1
  component_id: sensor.hlw8012
  fields:
    sel_pin:
      value:
        number: 12
        inverted: true
      locked: true
    cf_pin:
      value: 4
      locked: true
    cf1_pin:
      value: 5
      locked: true
    current_resistor: '0.05'
    voltage_divider: '720'
    change_mode_every: 4
    update_interval: 3s
    id: sensor_hlw8012_1
- id: relay1
  component_id: switch.gpio
  fields:
    pin:
      value: 14
      locked: true
    restore_mode: RESTORE_DEFAULT_OFF
    icon: mdi:power-socket-eu
    id: relay1
    name: umax - Switch1
- id: relay2
  component_id: switch.gpio
  fields:
    pin:
      value: 15
      locked: true
    restore_mode: RESTORE_DEFAULT_OFF
    icon: mdi:power-socket-eu
    id: relay2
    name: umax - Switch2
source:
  type: esphome-devices
  remote_id: UMAX-U-Smart-Wifi-Plug-Duo
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/UMAX-U-Smart-Wifi-Plug-Duo/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: ec49befff6c591386d4fbfffc0204edf6bb93fb676aa929dea8302f5fcf748ab
