id: zemismart_moonlamp
name: Zemismart Moonlamp
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01-1m
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Zemismart-Moonlamp/Moonlamp.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Zemismart-Moonlamp/BottomView.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Zemismart-Moonlamp/LEDLayout.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Zemismart-Moonlamp/SolderingPoints.png
pins:
- gpio: 4
  available: false
  occupied_by: output_red
- gpio: 5
  available: false
  occupied_by: output_cold_white
- gpio: 12
  available: false
  occupied_by: output_green
- gpio: 13
  available: false
  occupied_by: output_warm_white
- gpio: 14
  available: false
  occupied_by: output_blue
docs_url: https://devices.esphome.io/devices/Zemismart-Moonlamp/
featured_components:
- id: moonlamp
  component_id: light.rgbww
  fields:
    color_interlock: true
    warm_white_color_temperature: 2800 K
    cold_white_color_temperature: 6200 K
    red: output_red
    green: output_green
    blue: output_blue
    warm_white: output_warm_white
    cold_white: output_cold_white
    id: moonlamp
    name: moonlamp
- id: output_red
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 4
      locked: true
    id: output_red
- id: output_green
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 12
      locked: true
    id: output_green
- id: output_blue
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 14
      locked: true
    id: output_blue
- id: output_warm_white
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 13
      locked: true
    id: output_warm_white
- id: output_cold_white
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 5
      locked: true
    id: output_cold_white
featured_bundles:
- id: moonlamp_setup
  name: moonlamp (full setup)
  component_ids:
  - output_red
  - output_green
  - output_blue
  - output_warm_white
  - output_cold_white
  - moonlamp
source:
  type: esphome-devices
  remote_id: Zemismart-Moonlamp
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Zemismart-Moonlamp/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: a7a8d569d53d05c23f81ef9d2c262c56c93d1c6ef82f4445f6704aa9e1776bad
