id: sonoff_dual_r3
name: Sonoff Dual R3 & Lite
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32dev
  variant: esp32
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Sonoff-Dual-R3/Sonoff-DualR3-Lite-PCB.jpg
tags:
- relay
- sonoff
pins:
- gpio: 0
  available: false
  occupied_by: Button
- gpio: 13
  available: false
  occupied_by: LED
- gpio: 14
  available: false
  occupied_by: '2'
- gpio: 27
  available: false
  occupied_by: '1'
- gpio: 32
  available: false
  occupied_by: '1'
- gpio: 33
  available: false
  occupied_by: '2'
docs_url: https://devices.esphome.io/devices/Sonoff-Dual-R3/
featured_components:
- id: sensor_button
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 0
        mode:
          input: true
          pullup: true
        inverted: true
      locked: true
    disabled_by_default: true
    icon: mdi:radiobox-blank
    filters:
      value:
      - delayed_on: 50ms
      locked: true
    id: sensor_button
    name: Button
- id: binary_sensor_gpio_2
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 32
        mode:
          input: true
          pullup: true
        inverted: true
      locked: true
    filters:
      value:
      - delayed_on_off: 50ms
      locked: true
    id: binary_sensor_gpio_2
    name: '1'
- id: binary_sensor_gpio_3
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 33
        mode:
          input: true
          pullup: true
        inverted: true
      locked: true
    filters:
      value:
      - delayed_on_off: 50ms
      locked: true
    id: binary_sensor_gpio_3
    name: '2'
- id: led_status
  component_id: light.status_led
  fields:
    pin:
      value:
        number: 13
        inverted: true
      locked: true
    internal: true
    id: led_status
    name: LED
- id: sensor_rssi
  component_id: sensor.wifi_signal
  fields:
    update_interval: 90s
    entity_category: diagnostic
    id: sensor_rssi
    name: RSSI
- id: sensor_uptime
  component_id: sensor.uptime
  fields:
    update_interval: 300s
    entity_category: diagnostic
    id: sensor_uptime
    name: Uptime
- id: relay_1
  component_id: switch.gpio
  fields:
    pin:
      value: 27
      locked: true
    id: relay_1
    name: '1'
- id: relay_2
  component_id: switch.gpio
  fields:
    pin:
      value: 14
      locked: true
    id: relay_2
    name: '2'
source:
  type: esphome-devices
  remote_id: Sonoff-Dual-R3
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Sonoff-Dual-R3/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: d779d48d30fda6b2739cf7928d00072656f29317e1341c994ee33cf6d9afc8da
