id: lilygo_tdisplay_s3
name: Lilygo TDisplay S3
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework: esp-idf
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Lilygo-TDisplay-S3/tdisplay-s3.webp
pins:
- gpio: 0
  available: false
  occupied_by: Button 1
- gpio: 8
  available: false
  occupied_by: spi
- gpio: 14
  available: false
  occupied_by: Button 2
- gpio: 38
  available: false
  occupied_by: backlight_output
- gpio: 39
  available: false
  occupied_by: spi
- gpio: 40
  available: false
  occupied_by: spi
- gpio: 41
  available: false
  occupied_by: spi
- gpio: 42
  available: false
  occupied_by: spi
- gpio: 45
  available: false
  occupied_by: spi
- gpio: 46
  available: false
  occupied_by: spi
- gpio: 47
  available: false
  occupied_by: spi
- gpio: 48
  available: false
  occupied_by: spi
docs_url: https://devices.esphome.io/devices/Lilygo-TDisplay-S3/
product_url: https://www.lilygo.cc/en-ca/products/t-display-s3
featured_components:
- id: spi_bus
  component_id: spi
  fields:
    type: octal
    clk_pin:
      value: 8
      locked: true
    data_pins:
      value:
      - 39
      - 40
      - 41
      - 42
      - ignore_strapping_warning: true
        number: 45
      - ignore_strapping_warning: true
        number: 46
      - 47
      - 48
      locked: true
- id: onboard_psram
  component_id: psram
  name: PSRAM
  fields:
    speed: 80MHz
    mode: octal
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 0
        inverted: true
      locked: true
    id: binary_sensor_gpio_1
    name: Button 1
- id: binary_sensor_gpio_2
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 14
        inverted: true
      locked: true
    id: binary_sensor_gpio_2
    name: Button 2
- id: display_mipi_spi_1
  component_id: display.mipi_spi
  fields:
    model: t-display-s3
    rotation: 270
    show_test_card: true
    id: display_mipi_spi_1
  requires:
  - onboard_psram
  - spi_bus
- id: led
  component_id: light.monochromatic
  fields:
    restore_mode: ALWAYS_ON
    default_transition_length: 0s
    output: backlight_output
    id: led
    name: LCD Backlight
- id: backlight_output
  component_id: output.ledc
  fields:
    frequency: 2000
    pin:
      value: 38
      locked: true
    id: backlight_output
featured_bundles:
- id: led_setup
  name: LCD Backlight (full setup)
  component_ids:
  - backlight_output
  - led
source:
  type: esphome-devices
  remote_id: Lilygo-TDisplay-S3
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Lilygo-TDisplay-S3/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 30e395b09ce6722634889c46c24aab5877aeef8a3a1acd64a69a04fb6786c405
