id: sonoff_minir4_extreme
name: Sonoff Mini R4 Extreme
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32dev
  variant: esp32
  framework: arduino
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Sonoff-MiniR4-Extreme/sonoff-mini-r4.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Sonoff-MiniR4-Extreme/view_top.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Sonoff-MiniR4-Extreme/view_side.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Sonoff-MiniR4-Extreme/wires_angle.jpg
tags:
- relay
- sonoff
pins:
- gpio: 0
  available: false
  occupied_by: button
- gpio: 26
  available: false
  occupied_by: relay_1
- gpio: 27
  available: false
  occupied_by: s1
docs_url: https://devices.esphome.io/devices/Sonoff-MiniR4-Extreme/
featured_components:
- id: button
  component_id: binary_sensor.gpio
  fields:
    pin:
      value: 0
      locked: true
    filters:
      value:
      - invert: null
      - delayed_off: 50ms
      locked: true
    id: button
    name: button
- id: s1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value: 27
      locked: true
    filters:
      value:
      - invert: null
      - delayed_off: 50ms
      locked: true
    id: s1
    name: s1
- id: light_1
  component_id: light.binary
  fields:
    icon: mdi:ceiling-light-multiple-outline
    restore_mode: restore_default_off
    output: relay_1
    id: light_1
    name: minir4-extreme
- id: relay_1
  component_id: output.gpio
  fields:
    pin:
      value: 26
      locked: true
    id: relay_1
- id: sensor_wifi_signal_1
  component_id: sensor.wifi_signal
  fields:
    update_interval: 90s
    entity_category: diagnostic
    id: sensor_wifi_signal_1
    name: minir4-extreme Wifi Signal Strength
- id: sensor_uptime_1
  component_id: sensor.uptime
  fields:
    update_interval: 300s
    entity_category: diagnostic
    id: sensor_uptime_1
    name: minir4-extreme Uptime
featured_bundles:
- id: light_1_setup
  name: minir4-extreme (full setup)
  component_ids:
  - relay_1
  - light_1
source:
  type: esphome-devices
  remote_id: Sonoff-MiniR4-Extreme
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Sonoff-MiniR4-Extreme/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 9ebc08643a47ad0225a16b30064706c7c909e386752298324e7fb30b41314e45
