id: magichome_zj_wfmn_a_rgbw
name: MagicHome RGBW ZJ-WFMN-A V1.1 LED Controller
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/MagicHome-ZJ-WFMN-A-RGBW/MagicHome-ZJ-WFMN-A-RGBW.png
pins:
- gpio: 5
  available: false
  occupied_by: green_channel
- gpio: 12
  available: false
  occupied_by: red_channel
- gpio: 13
  available: false
  occupied_by: blue_channel
- gpio: 15
  available: false
  occupied_by: white_channel
docs_url: https://devices.esphome.io/devices/MagicHome-ZJ-WFMN-A-RGBW/
featured_components:
- id: device_name
  component_id: light.rgbw
  fields:
    red: red_channel
    green: green_channel
    blue: blue_channel
    white: white_channel
    id: device_name
    name: Rgbw 1
- id: red_channel
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 12
      locked: true
    id: red_channel
- id: green_channel
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 5
      locked: true
    id: green_channel
- id: blue_channel
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 13
      locked: true
    id: blue_channel
- id: white_channel
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 15
      locked: true
    id: white_channel
featured_bundles:
- id: device_name_setup
  name: Rgbw (full setup)
  component_ids:
  - red_channel
  - green_channel
  - blue_channel
  - white_channel
  - device_name
source:
  type: esphome-devices
  remote_id: MagicHome-ZJ-WFMN-A-RGBW
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/MagicHome-ZJ-WFMN-A-RGBW/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: c161f92d049a0a213b0a1c9f8d2258fed5174c4ffc4345c277e4fb5503181ecb
