id: tongou_to_q_sys_jwt_power_meter
name: Tongou TO-Q-SYS-JWT DIN Rail Switch and Meter
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: cbu
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tongou-TO-Q-SYS-JWT-power-meter/product-image.webp
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tongou-TO-Q-SYS-JWT-power-meter/device-disassembled.webp
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tongou-TO-Q-SYS-JWT-power-meter/internal-mains-attachments.webp
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tongou-TO-Q-SYS-JWT-power-meter/mcu.webp
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tongou-TO-Q-SYS-JWT-power-meter/CBU-board.webp
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tongou-TO-Q-SYS-JWT-power-meter/CBU-board-2.webp
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tongou-TO-Q-SYS-JWT-power-meter/TO-Q-SYS-JWT-1.png
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tongou-TO-Q-SYS-JWT-power-meter/TO-Q-SYS-JWT-2.png
docs_url: https://devices.esphome.io/devices/Tongou-TO-Q-SYS-JWT-power-meter/
product_url: https://github.com/dshcherb/TO-Q-SYS-JWT-meter-esphome
featured_components:
- id: uart_bus
  component_id: uart
  fields:
    rx_pin:
      value: RX1
      locked: true
    tx_pin:
      value: TX1
      locked: true
    baud_rate: 115200
    rx_buffer_size: 512
- id: tuya_component
  component_id: tuya
  fields:
    id:
      value: tuya_component
      locked: true
  requires:
  - uart_bus
- id: number_tuya_1
  component_id: number.tuya
  fields:
    number_datapoint: 116
    device_class: voltage
    unit_of_measurement: V
    min_value: 100
    max_value: 280
    step: 1
    id: number_tuya_1
    name: Under-voltage Threshold
  requires:
  - uart_bus
  - tuya_component
- id: number_tuya_2
  component_id: number.tuya
  fields:
    number_datapoint: 115
    device_class: voltage
    unit_of_measurement: V
    min_value: 100
    max_value: 280
    step: 1
    id: number_tuya_2
    name: Over-voltage Threshold
  requires:
  - uart_bus
  - tuya_component
- id: number_tuya_3
  component_id: number.tuya
  fields:
    number_datapoint: 114
    device_class: current
    unit_of_measurement: A
    min_value: 1
    max_value: 50
    step: 0.1
    id: number_tuya_3
    name: Over-current Threshold
  requires:
  - uart_bus
  - tuya_component
- id: number_tuya_4
  component_id: number.tuya
  fields:
    number_datapoint: 118
    unit_of_measurement: °C
    device_class: temperature
    min_value: -25
    max_value: 100
    multiply: 10.0
    step: 0.1
    id: number_tuya_4
    name: Temperature Threshold
  requires:
  - uart_bus
  - tuya_component
- id: number_tuya_5
  component_id: number.tuya
  fields:
    number_datapoint: 119
    device_class: power
    unit_of_measurement: W
    min_value: 5
    max_value: 12000
    step: 1
    id: number_tuya_5
    name: Over-Power Threshold
  requires:
  - uart_bus
  - tuya_component
- id: number_tuya_6
  component_id: number.tuya
  fields:
    number_datapoint: 140
    min_value: 1
    max_value: 5
    step: 1
    id: number_tuya_6
    name: Screen Brightness
  requires:
  - uart_bus
  - tuya_component
- id: number_tuya_7
  component_id: number.tuya
  fields:
    number_datapoint: 137
    unit_of_measurement: S
    min_value: 5
    max_value: 600
    step: 1
    id: number_tuya_7
    name: Reporting Interval
  requires:
  - uart_bus
  - tuya_component
- id: number_tuya_8
  component_id: number.tuya
  fields:
    device_class: energy
    number_datapoint: 120
    unit_of_measurement: kW·h
    min_value: 1
    max_value: 500
    step: 1
    id: number_tuya_8
    name: Balance Shortage Threshold
  requires:
  - uart_bus
  - tuya_component
- id: charge_electricity
  component_id: number.tuya
  fields:
    number_datapoint: 14
    device_class: energy_storage
    unit_of_measurement: kW·h
    min_value: 0
    max_value: 9999
    datapoint_hidden:
      value:
        datapoint_type: int
        initial_value: 0
        restore_value: false
      locked: true
    step: 0.1
    multiply: 100
    id: charge_electricity
    name: Charge Electricity
  requires:
  - uart_bus
  - tuya_component
- id: sensor_tuya_1
  component_id: sensor.tuya
  fields:
    sensor_datapoint: 1
    device_class: energy
    unit_of_measurement: kW·h
    state_class: measurement
    filters:
      value:
      - multiply: 0.01
      locked: true
    accuracy_decimals: 2
    id: sensor_tuya_1
    name: Total Electricity Consumption
  requires:
  - uart_bus
  - tuya_component
- id: sensor_tuya_2
  component_id: sensor.tuya
  fields:
    sensor_datapoint: 125
    device_class: energy
    unit_of_measurement: kW·h
    state_class: measurement
    icon: mdi:meter-electric-outline
    accuracy_decimals: 2
    filters:
      value:
      - multiply: 0.01
      locked: true
    id: sensor_tuya_2
    name: Forward Electricity
  requires:
  - uart_bus
  - tuya_component
- id: sensor_tuya_3
  component_id: sensor.tuya
  fields:
    sensor_datapoint: 131
    state_class: measurement
    unit_of_measurement: °C
    device_class: temperature
    accuracy_decimals: 1
    filters:
      value:
      - multiply: 0.1
      locked: true
    icon: mdi:temperature-celcius
    id: sensor_tuya_3
    name: Real-time Temperature
  requires:
  - uart_bus
  - tuya_component
- id: sensor_tuya_4
  component_id: sensor.tuya
  fields:
    sensor_datapoint: 13
    state_class: measurement
    unit_of_measurement: kW·h
    device_class: energy
    accuracy_decimals: 2
    filters:
      value:
      - multiply: 0.01
      locked: true
    icon: mdi:home-battery-outline
    id: sensor_tuya_4
    name: Electricity Balance
  requires:
  - uart_bus
  - tuya_component
- id: switch_tuya_1
  component_id: switch.tuya
  fields:
    switch_datapoint: 16
    icon: mdi:restart
    device_class: outlet
    id: switch_tuya_1
    name: Circuit Breaker Switch
  requires:
  - uart_bus
  - tuya_component
- id: switch_tuya_2
  component_id: switch.tuya
  fields:
    switch_datapoint: 112
    restore_mode: DISABLED
    id: switch_tuya_2
    name: Automatic Closing
  requires:
  - uart_bus
  - tuya_component
- id: switch_tuya_3
  component_id: switch.tuya
  fields:
    switch_datapoint: 113
    id: switch_tuya_3
    name: Reset MCU to Defaults
  requires:
  - uart_bus
  - tuya_component
- id: switch_tuya_4
  component_id: switch.tuya
  fields:
    switch_datapoint: 111
    restore_mode: DISABLED
    id: switch_tuya_4
    name: Report State Changes
  requires:
  - uart_bus
  - tuya_component
- id: switch_tuya_5
  component_id: switch.tuya
  fields:
    switch_datapoint: 11
    id: switch_tuya_5
    name: Prepayment Switch Mode
  requires:
  - uart_bus
  - tuya_component
- id: clear_electricity_switch
  component_id: switch.tuya
  fields:
    switch_datapoint: 12
    internal: true
    id: clear_electricity_switch
    name: Clear Remaining Electricity
  requires:
  - uart_bus
  - tuya_component
- id: switch_tuya_7
  component_id: switch.tuya
  fields:
    switch_datapoint: 141
    inverted:
      value: true
      locked: true
    id: switch_tuya_7
    name: Screen On
  requires:
  - uart_bus
  - tuya_component
- id: text_sensor_tuya_1
  component_id: text_sensor.tuya
  fields:
    sensor_datapoint: 109
    filters:
      value:
      - map:
        - 1 -> Offline
        - 0 -> Online
      locked: true
    id: text_sensor_tuya_1
    name: Online Status
  requires:
  - uart_bus
  - tuya_component
- id: text_sensor_tuya_2
  component_id: text_sensor.tuya
  fields:
    sensor_datapoint: 110
    filters:
      value:
      - map:
        - 0 -> Normal
        - 1 -> Over Current Trip
        - 2 -> Over Power Trip
        - 3 -> High Temp Trip
        - 4 -> Over Voltage Trip
        - 5 -> Under Voltage Trip
        - 6 -> Over Current Alarm
        - 7 -> Over Power Alarm
        - 8 -> High Temp Alarm
        - 9 -> Over Voltage Alarm
        - 10 -> Under Voltage Alarm
        - 11 -> Remote ON
        - 12 -> Remote OFF
        - 13 -> Manual ON
        - 14 -> Manual OFF
        - 15 -> Leakage Trip
        - 16 -> Leakage Alarm
        - 17 -> Restore Default
        - 18 -> Automatic Closing
        - 19 -> Electricity Shortage
        - 20 -> Electricity Shortage Alarm
      locked: true
    id: text_sensor_tuya_2
    name: Last MCU Event
  requires:
  - uart_bus
  - tuya_component
source:
  type: esphome-devices
  remote_id: Tongou-TO-Q-SYS-JWT-power-meter
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Tongou-TO-Q-SYS-JWT-power-meter/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: b3018ca01f36ed4c2b996e896840ac31a73c44528265215665f82f57705fda3a
