id: wyze_light_strip_pro_wlpstpr_10
name: WYZE Light Strip Pro (WLPSTPR-10)
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32dev
  variant: esp32
  framework: arduino
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/WYZE-Light-Strip-Pro-WLPSTPR-10/wlpstpr_pads.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/WYZE-Light-Strip-Pro-WLPSTPR-10/wlpstpr_io.jpg
pins:
- gpio: 2
  available: false
  occupied_by: side button
- gpio: 19
  available: false
  occupied_by: top button
- gpio: 25
  available: false
  occupied_by: light1
- gpio: 26
  available: false
  occupied_by: light2
docs_url: https://devices.esphome.io/devices/WYZE-Light-Strip-Pro-WLPSTPR-10/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value: 2
      locked: true
    id: binary_sensor_gpio_1
    name: side button
- id: binary_sensor_gpio_2
  component_id: binary_sensor.gpio
  fields:
    pin:
      value: 19
      locked: true
    id: binary_sensor_gpio_2
    name: top button
- id: light_esp32_rmt_led_strip_1
  component_id: light.esp32_rmt_led_strip
  fields:
    chipset: ws2812
    pin:
      value: 25
      locked: true
    num_leds: 50
    rgb_order: BRG
    effects:
      value:
      - random: null
      - pulse: null
      - strobe: null
      - flicker: null
      - addressable_rainbow: null
      - addressable_color_wipe: null
      - addressable_scan: null
      - addressable_twinkle: null
      - addressable_random_twinkle: null
      - addressable_fireworks: null
      - addressable_flicker: null
      locked: true
    id: light_esp32_rmt_led_strip_1
    name: light1
- id: light_esp32_rmt_led_strip_2
  component_id: light.esp32_rmt_led_strip
  fields:
    chipset: ws2812
    pin:
      value: 26
      locked: true
    num_leds: 50
    rgb_order: BRG
    effects:
      value:
      - random: null
      - pulse: null
      - strobe: null
      - flicker: null
      - addressable_rainbow: null
      - addressable_color_wipe: null
      - addressable_scan: null
      - addressable_twinkle: null
      - addressable_random_twinkle: null
      - addressable_fireworks: null
      - addressable_flicker: null
      locked: true
    id: light_esp32_rmt_led_strip_2
    name: light2
source:
  type: esphome-devices
  remote_id: WYZE-Light-Strip-Pro-WLPSTPR-10
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/WYZE-Light-Strip-Pro-WLPSTPR-10/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: cb175743751847e14ff9acfdac3f1ed434695743a9f6e525875637910f51ff5c
