id: kmp_prodino_esp32ex
name: KMP PRODINo ESP32EX
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32dev
  variant: esp32
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KMP-PRODINo-ESP32EX/ProDinoESP32Ex_2.jpg
pins:
- gpio: 0
  available: false
  occupied_by: LED WS2812B
- gpio: 18
  available: false
  occupied_by: spi
- gpio: 19
  available: false
  occupied_by: spi
- gpio: 21
  available: false
  occupied_by: sensor.dht
- gpio: 22
  available: false
  occupied_by: sensor.dht
- gpio: 23
  available: false
  occupied_by: spi
- gpio: 32
  available: false
  occupied_by: mcp23s08_hub
docs_url: https://devices.esphome.io/devices/KMP-PRODINo-ESP32EX/
featured_components:
- id: spi_bus
  component_id: spi
  fields:
    clk_pin:
      value: 18
      locked: true
    mosi_pin:
      value: 23
      locked: true
    miso_pin:
      value: 19
      locked: true
- id: mcp23s08_hub
  component_id: mcp23s08
  fields:
    cs_pin:
      value: 32
      locked: true
    deviceaddress: 0
    id:
      value: mcp23s08_hub
      locked: true
  requires:
  - spi_bus
- id: light_esp32_rmt_led_strip_1
  component_id: light.esp32_rmt_led_strip
  fields:
    chipset: ws2812
    pin:
      value: 0
      locked: true
    num_leds: 1
    rgb_order: GRB
    id: light_esp32_rmt_led_strip_1
    name: LED WS2812B
- id: sensor_dht_1
  component_id: sensor.dht
  fields:
    model: AM2302
    pin:
      value: 21
      locked: true
    update_interval: 30s
    id: sensor_dht_1
- id: sensor_dht_2
  component_id: sensor.dht
  fields:
    model: AM2302
    pin:
      value: 22
      locked: true
    update_interval: 30s
    id: sensor_dht_2
source:
  type: esphome-devices
  remote_id: KMP-PRODINo-ESP32EX
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/KMP-PRODINo-ESP32EX/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: cd682661c9a8a4d33b0b5ed58b6bb8699ec5b44152c25ecaac2dce259f0dd7ca
