id: shelly_ht_gen3
name: Shelly H&T Gen3
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework: esp-idf
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Shelly-HT-Gen3/product.png
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Shelly-HT-Gen3/PCB_Pinout.png
tags:
- shelly
pins:
- gpio: 1
  available: false
  occupied_by: i2c
- gpio: 3
  available: false
  occupied_by: i2c
- gpio: 4
  available: false
  occupied_by: batt_adc
- gpio: 5
  available: false
  occupied_by: batt_presence
- gpio: 18
  available: false
  occupied_by: batt_power_en
docs_url: https://devices.esphome.io/devices/Shelly-HT-Gen3/
featured_components:
- id: i2c_bus
  component_id: i2c
  fields:
    sda:
      value: 1
      locked: true
    scl:
      value: 3
      locked: true
    scan: false
    frequency: 100kHz
- id: batt_presence
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 5
        inverted: true
      locked: true
    internal: true
    id: batt_presence
    name: batt_presence
- id: batt_power_en
  component_id: output.gpio
  fields:
    pin:
      value: 18
      locked: true
    id: batt_power_en
- id: sensor_sht3xd_1
  component_id: sensor.sht3xd
  fields:
    address: 68
    update_interval: 60s
    id: sensor_sht3xd_1
  requires:
  - i2c_bus
- id: wifi_rssi
  component_id: sensor.wifi_signal
  fields:
    update_interval: 120s
    id: wifi_rssi
    name: WiFi Signal
- id: batt_adc
  component_id: sensor.adc
  fields:
    pin:
      value: 4
      locked: true
    attenuation: 12db
    update_interval: never
    internal: true
    samples: 15
    id: batt_adc
    name: batt_adc
source:
  type: esphome-devices
  remote_id: Shelly-HT-Gen3
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Shelly-HT-Gen3/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 8030ca40273ce51659f2fb8f2df3311022b7d2f5b5da3d64ac54133f89da5291
