id: kincony_kc868_uair
name: KinCony KC868-Uair
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32dev
  variant: esp32
  framework: arduino
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KinCony-KC868-Uair/kc868-uair.jpg
pins:
- gpio: 4
  available: false
  occupied_by: bus_a
- gpio: 16
  available: false
  occupied_by: bus_a
- gpio: 27
  available: false
  occupied_by: one_wire.gpio
- gpio: 32
  available: false
  occupied_by: Uair-Bottom-LED
- gpio: 33
  available: false
  occupied_by: Uair-VVertical-LED
docs_url: https://devices.esphome.io/devices/KinCony-KC868-Uair/
featured_components:
- id: one_wire_bus
  component_id: one_wire.gpio
  fields:
    pin:
      value: 27
      locked: true
- id: bus_a
  component_id: i2c
  fields:
    sda:
      value: 4
      locked: true
    scl:
      value: 16
      locked: true
    scan: true
    id:
      value: bus_a
      locked: true
- id: light_esp32_rmt_led_strip_1
  component_id: light.esp32_rmt_led_strip
  fields:
    chipset: ws2812
    pin:
      value: 32
      locked: true
    num_leds: 4
    rgb_order: GRB
    effects:
      value:
      - addressable_rainbow: null
      - addressable_color_wipe: null
      - addressable_scan: null
      - addressable_twinkle: null
      - addressable_random_twinkle: null
      - addressable_fireworks: null
      - addressable_flicker: null
      locked: true
    id: light_esp32_rmt_led_strip_1
    name: Uair-Bottom-LED
- id: light_esp32_rmt_led_strip_2
  component_id: light.esp32_rmt_led_strip
  fields:
    chipset: ws2812
    pin:
      value: 33
      locked: true
    num_leds: 1
    rgb_order: RGB
    effects:
      value:
      - addressable_rainbow: null
      - addressable_color_wipe: null
      - addressable_scan: null
      - addressable_twinkle: null
      - addressable_random_twinkle: null
      - addressable_fireworks: null
      - addressable_flicker: null
      locked: true
    id: light_esp32_rmt_led_strip_2
    name: Uair-VVertical-LED
- id: sensor_dallas_temp_1
  component_id: sensor.dallas_temp
  fields:
    address: 13835058055363433768
    id: sensor_dallas_temp_1
    name: internal Temperature
  requires:
  - one_wire_bus
- id: sensor_sht3xd_1
  component_id: sensor.sht3xd
  fields:
    address: 68
    update_interval: 15s
    id: sensor_sht3xd_1
  requires:
  - bus_a
source:
  type: esphome-devices
  remote_id: KinCony-KC868-Uair
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/KinCony-KC868-Uair/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 2ef361ba63f8c1ee72ce3a6fe2e2114d0149ca6d0bfc03553aee5cc68b73dc3f
