id: athom_smart_plug_pg05v2_au10a
name: Athom Smart Plug AU V2 (PG05V2-AU10A)
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp8285
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Athom-Smart-Plug-PG05V2-AU10A/athom-plug-au-v2.webp
tags:
- relay
- compact
pins:
- gpio: 5
  available: false
  occupied_by: Athom Smart Plug V2 Power Button
- gpio: 12
  available: false
  occupied_by: Athom Smart Plug V2
- gpio: 13
  available: false
  occupied_by: Athom Smart Plug V2 Status LED
docs_url: https://devices.esphome.io/devices/Athom-Smart-Plug-PG05V2-AU10A/
product_url: https://github.com/athom-tech/athom-configs/blob/main/athom-smart-plug-v2.yaml
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 5
        mode: INPUT_PULLUP
        inverted: true
      locked: true
    disabled_by_default: true
    id: binary_sensor_gpio_1
    name: Athom Smart Plug V2 Power Button
- id: button_safe_mode_1
  component_id: button.safe_mode
  fields:
    internal: false
    id: button_safe_mode_1
    name: Safe Mode
- id: blue_led
  component_id: light.status_led
  fields:
    disabled_by_default: true
    pin:
      value:
        inverted: true
        number: 13
      locked: true
    id: blue_led
    name: Athom Smart Plug V2 Status LED
- id: relay
  component_id: switch.gpio
  fields:
    pin:
      value: 12
      locked: true
    restore_mode: RESTORE_DEFAULT_OFF
    id: relay
    name: Athom Smart Plug V2
source:
  type: esphome-devices
  remote_id: Athom-Smart-Plug-PG05V2-AU10A
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Athom-Smart-Plug-PG05V2-AU10A/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: ab2a90726f20706244b3a16386a2cff0948fe142a5288fd54fdc2c432756f071
