id: ledvance_e27_dim
name: LEDVANCE E27 DIM Light 806lm
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: generic-bk7231t-qfn32-tuya
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/LEDVANCE-E27-DIM/ledvance-e27-dim.jpg
pins:
- gpio: 9
  available: false
  occupied_by: output_brightness
docs_url: https://devices.esphome.io/devices/LEDVANCE-E27-DIM/
featured_components:
- id: light_monochromatic_1
  component_id: light.monochromatic
  fields:
    effects:
      value:
      - flicker:
          name: Flicker
      - pulse:
          name: Pulse
      locked: true
    output: output_brightness
    id: light_monochromatic_1
    name: None
- id: output_brightness
  component_id: output.libretiny_pwm
  fields:
    pin:
      value: 9
      locked: true
    id: output_brightness
featured_bundles:
- id: light_monochromatic_1_setup
  name: Monochromatic (full setup)
  component_ids:
  - output_brightness
  - light_monochromatic_1
source:
  type: esphome-devices
  remote_id: LEDVANCE-E27-DIM
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/LEDVANCE-E27-DIM/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 038327e2a4e718e1dc78aa5223e15c793584ce08bd63b317e518ce7b654a7c18
