id: generic_usb_wifi_switch
name: Generic USB Wifi Switch
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: cbu
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Generic-USB-Wifi-Switch/generic-usb-switch-cbu.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Generic-USB-Wifi-Switch/generic-usb-switch-3out.jpg
tags:
- relay
pins:
- gpio: 6
  available: false
  occupied_by: led
- gpio: 7
  available: false
  occupied_by: Relay 1
- gpio: 8
  available: false
  occupied_by: Side button
- gpio: 24
  available: false
  occupied_by: Relay 3
- gpio: 26
  available: false
  occupied_by: Relay 2
docs_url: https://devices.esphome.io/devices/Generic-USB-Wifi-Switch/
featured_components:
- id: button
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 8
        inverted: true
        mode: input_pullup
      locked: true
    id: button
    name: Side button
- id: light_monochromatic_1
  component_id: light.monochromatic
  fields:
    output: led
    id: light_monochromatic_1
    name: LED
- id: led
  component_id: output.libretiny_pwm
  fields:
    pin:
      value: 6
      locked: true
    id: led
- id: relay1
  component_id: switch.gpio
  fields:
    pin:
      value: 7
      locked: true
    id: relay1
    name: Relay 1
- id: relay2
  component_id: switch.gpio
  fields:
    pin:
      value: 26
      locked: true
    id: relay2
    name: Relay 2
- id: relay3
  component_id: switch.gpio
  fields:
    pin:
      value: 24
      locked: true
    id: relay3
    name: Relay 3
featured_bundles:
- id: light_monochromatic_1_setup
  name: LED (full setup)
  component_ids:
  - led
  - light_monochromatic_1
source:
  type: esphome-devices
  remote_id: Generic-USB-Wifi-Switch
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Generic-USB-Wifi-Switch/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: e3b7ff961e2bd1f5266843600a8d52ae350ba0f3f47fadd0fb18099f24c29354
