id: kogan_rgb_cool_warm_white_2m_led_strip
name: Kogan RGB + Cool & Warm White 2m LED Strip
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Kogan-RGB-Cool-Warm-White-2m-LED-Strip/Kogan-RGB-Cool-Warm-White-2m-LED-Strip.jpg
pins:
- gpio: 3
  available: false
  occupied_by: kogan_RGBWWSTRIP_1_button
- gpio: 4
  available: false
  occupied_by: output_red
- gpio: 5
  available: false
  occupied_by: output_coldwhite
- gpio: 12
  available: false
  occupied_by: output_green
- gpio: 13
  available: false
  occupied_by: output_warmwhite
- gpio: 14
  available: false
  occupied_by: output_blue
docs_url: https://devices.esphome.io/devices/Kogan-RGB-Cool-Warm-White-2m-LED-Strip/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 3
        mode: INPUT_PULLUP
        inverted: true
      locked: true
    id: binary_sensor_gpio_1
    name: kogan_RGBWWSTRIP_1_button
- id: kogan_rgbwwstrip_1
  component_id: light.rgbww
  fields:
    default_transition_length: 0s
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_coldwhite
    warm_white: output_warmwhite
    id: kogan_rgbwwstrip_1
    name: kogan_RGBWWSTRIP_1
- id: output_blue
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 14
      locked: true
    id: output_blue
- id: output_green
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 12
      locked: true
    id: output_green
- id: output_red
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 4
      locked: true
    id: output_red
- id: output_coldwhite
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 5
      locked: true
    id: output_coldwhite
- id: output_warmwhite
  component_id: output.esp8266_pwm
  fields:
    pin:
      value: 13
      locked: true
    id: output_warmwhite
featured_bundles:
- id: kogan_rgbwwstrip_1_setup
  name: kogan_RGBWWSTRIP_1 (full setup)
  component_ids:
  - output_red
  - output_green
  - output_blue
  - output_coldwhite
  - output_warmwhite
  - kogan_rgbwwstrip_1
source:
  type: esphome-devices
  remote_id: Kogan-RGB-Cool-Warm-White-2m-LED-Strip
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Kogan-RGB-Cool-Warm-White-2m-LED-Strip/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 72af818b20d19a96e1132af9a7677e8246395a248b0560e2c8a26073a8d1ef98
