id: ezaiot_xyzoo_thermostat
name: EZAIOT/XYZOO Thermostat (Tuya MCU)
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: generic-bk7231n-qfn32-tuya
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/EZAIOT-XYZOO-Thermostat/dq6nlukkifyawj9n.png
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/EZAIOT-XYZOO-Thermostat/board_with_holes.png
docs_url: https://devices.esphome.io/devices/EZAIOT-XYZOO-Thermostat/
featured_components:
- id: ha_weather_temp
  component_id: sensor.homeassistant
  fields:
    entity_id: weather.forecast_casa
    attribute: temperature
    internal: true
    id: ha_weather_temp
    name: ha_weather_temp
- id: ha_weather_humidity
  component_id: sensor.homeassistant
  fields:
    entity_id: weather.forecast_casa
    attribute: humidity
    internal: true
    id: ha_weather_humidity
    name: ha_weather_humidity
- id: ha_weather_state
  component_id: text_sensor.homeassistant
  fields:
    entity_id: weather.forecast_casa
    internal: true
    id: ha_weather_state
    name: ha_weather_state
source:
  type: esphome-devices
  remote_id: EZAIOT-XYZOO-Thermostat
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/EZAIOT-XYZOO-Thermostat/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 87eb7b9ed1472daf6475ed1463e87ae99679c6bd01a90dd7f3a2596cc3d22529
