id: globe_electric_wi_fi_smart_plug_50329
name: Globe Electric Wi-Fi Smart Plug 50359
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: wb2s
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Globe-Electric-Wi-Fi-Smart-Plug-50329/globe1.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Globe-Electric-Wi-Fi-Smart-Plug-50329/globe2.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Globe-Electric-Wi-Fi-Smart-Plug-50329/globe3.jpg
tags:
- relay
- compact
pins:
- gpio: 7
  available: false
  occupied_by: led
- gpio: 24
  available: false
  occupied_by: Globe Plug 1 Outlet
- gpio: 26
  available: false
  occupied_by: button1
docs_url: https://devices.esphome.io/devices/Globe-Electric-Wi-Fi-Smart-Plug-50329/
featured_components:
- id: button1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 26
        inverted: true
      locked: true
    filters:
      value:
      - delayed_on: 10ms
      - delayed_off: 10ms
      locked: true
    id: button1
    name: button1
- id: led
  component_id: light.status_led
  fields:
    internal: true
    pin:
      value:
        number: 7
        inverted: true
      locked: true
    id: led
    name: led
- id: sensor_uptime_1
  component_id: sensor.uptime
  fields:
    unit_of_measurement: minutes
    filters:
      value:
      - lambda: return x / 60.0;
      locked: true
    id: sensor_uptime_1
    name: Globe Plug 1 Uptime
- id: sensor_wifi_signal_1
  component_id: sensor.wifi_signal
  fields:
    update_interval: 60s
    id: sensor_wifi_signal_1
    name: Globe Plug 1 Signal
- id: outlet
  component_id: switch.gpio
  fields:
    pin:
      value: 24
      locked: true
    icon: mdi:power-socket-us
    id: outlet
    name: Globe Plug 1 Outlet
source:
  type: esphome-devices
  remote_id: Globe-Electric-Wi-Fi-Smart-Plug-50329
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Globe-Electric-Wi-Fi-Smart-Plug-50329/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 1253d49929d20ed426586cbdcb92cdf105070a83deda19d5c2c17757fed33df1
