id: kincony_kc868_ap
name: KinCony KC868-AP
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32dev
  variant: esp32
  framework: arduino
hardware:
  connectivity:
  - wifi
  - bluetooth
  - ethernet
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KinCony-KC868-AP/kc868-ap.jpg
pins:
- gpio: 2
  available: false
  occupied_by: ap-light2
- gpio: 4
  available: false
  occupied_by: bus_a
- gpio: 13
  available: false
  occupied_by: ap-light1
- gpio: 16
  available: false
  occupied_by: bus_a
- gpio: 17
  available: false
  occupied_by: Ethernet CLK
- gpio: 18
  available: false
  occupied_by: Ethernet MDIO
- gpio: 23
  available: false
  occupied_by: Ethernet MDC
- gpio: 34
  available: false
  occupied_by: ap-input17
- gpio: 35
  available: false
  occupied_by: ap-input18
docs_url: https://devices.esphome.io/devices/KinCony-KC868-AP/
featured_components:
- id: pca9685_hub
  component_id: pca9685
  fields:
    frequency: 500
    id:
      value: pca9685_hub
      locked: true
  requires:
  - bus_a
- id: bus_a
  component_id: i2c
  fields:
    sda:
      value: 4
      locked: true
    scl:
      value: 16
      locked: true
    scan: true
    id:
      value: bus_a
      locked: true
- id: pcf8574_hub_in_1
  component_id: pcf8574
  fields:
    address: 58
    id:
      value: pcf8574_hub_in_1
      locked: true
  requires:
  - bus_a
- id: pcf8574_hub_in_2
  component_id: pcf8574
  fields:
    address: 33
    id:
      value: pcf8574_hub_in_2
      locked: true
  requires:
  - bus_a
- id: onboard_ethernet
  component_id: ethernet
  name: Onboard Ethernet
  fields:
    type:
      value: LAN8720
      locked: true
    mdc_pin:
      value: GPIO23
      locked: true
    mdio_pin:
      value: GPIO18
      locked: true
    phy_addr:
      value: 0
      locked: true
    clk:
      value:
        pin: GPIO17
        mode: CLK_OUT
      locked: true
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 0
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_1
    name: ap-input1
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_2
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 1
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_2
    name: ap-input2
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_3
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 2
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_3
    name: ap-input3
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_4
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 3
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_4
    name: ap-input4
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_5
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 4
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_5
    name: ap-input5
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_6
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 5
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_6
    name: ap-input6
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_7
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 6
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_7
    name: ap-input7
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_8
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 7
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_8
    name: ap-input8
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_9
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 0
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_9
    name: ap-input9
  requires:
  - bus_a
  - pcf8574_hub_in_2
- id: binary_sensor_gpio_10
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 1
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_10
    name: ap-input10
  requires:
  - bus_a
  - pcf8574_hub_in_2
- id: binary_sensor_gpio_11
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 2
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_11
    name: ap-input11
  requires:
  - bus_a
  - pcf8574_hub_in_2
- id: binary_sensor_gpio_12
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 3
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_12
    name: ap-input12
  requires:
  - bus_a
  - pcf8574_hub_in_2
- id: binary_sensor_gpio_13
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 4
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_13
    name: ap-input13
  requires:
  - bus_a
  - pcf8574_hub_in_2
- id: binary_sensor_gpio_14
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 5
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_14
    name: ap-input14
  requires:
  - bus_a
  - pcf8574_hub_in_2
- id: binary_sensor_gpio_15
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 6
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_15
    name: ap-input15
  requires:
  - bus_a
  - pcf8574_hub_in_2
- id: binary_sensor_gpio_16
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 7
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_16
    name: ap-input16
  requires:
  - bus_a
  - pcf8574_hub_in_2
- id: binary_sensor_gpio_17
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 34
        inverted: true
      locked: true
    id: binary_sensor_gpio_17
    name: ap-input17
- id: binary_sensor_gpio_18
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 35
        inverted: true
      locked: true
    id: binary_sensor_gpio_18
    name: ap-input18
- id: light_monochromatic_1
  component_id: light.monochromatic
  fields:
    output: pwm0
    id: light_monochromatic_1
    name: Color-LED-1
- id: light_monochromatic_2
  component_id: light.monochromatic
  fields:
    output: pwm1
    id: light_monochromatic_2
    name: Color-LED-2
- id: light_monochromatic_3
  component_id: light.monochromatic
  fields:
    output: pwm2
    id: light_monochromatic_3
    name: Color-LED-3
- id: light_monochromatic_4
  component_id: light.monochromatic
  fields:
    output: pwm3
    id: light_monochromatic_4
    name: Color-LED-4
- id: light_monochromatic_5
  component_id: light.monochromatic
  fields:
    output: pwm4
    id: light_monochromatic_5
    name: Color-LED-5
- id: light_monochromatic_6
  component_id: light.monochromatic
  fields:
    output: pwm5
    id: light_monochromatic_6
    name: Color-LED-6
- id: light_monochromatic_7
  component_id: light.monochromatic
  fields:
    output: pwm6
    id: light_monochromatic_7
    name: Color-LED-7
- id: light_monochromatic_8
  component_id: light.monochromatic
  fields:
    output: pwm7
    id: light_monochromatic_8
    name: Color-LED-8
- id: light_monochromatic_9
  component_id: light.monochromatic
  fields:
    output: pwm8
    id: light_monochromatic_9
    name: Color-LED-9
- id: light_monochromatic_10
  component_id: light.monochromatic
  fields:
    output: pwm9
    id: light_monochromatic_10
    name: Color-LED-10
- id: light_monochromatic_11
  component_id: light.monochromatic
  fields:
    output: pwm10
    id: light_monochromatic_11
    name: Color-LED-11
- id: light_monochromatic_12
  component_id: light.monochromatic
  fields:
    output: pwm11
    id: light_monochromatic_12
    name: Color-LED-12
- id: light_monochromatic_13
  component_id: light.monochromatic
  fields:
    output: pwm12
    id: light_monochromatic_13
    name: Color-LED-13
- id: light_monochromatic_14
  component_id: light.monochromatic
  fields:
    output: pwm13
    id: light_monochromatic_14
    name: Color-LED-14
- id: light_monochromatic_15
  component_id: light.monochromatic
  fields:
    output: pwm14
    id: light_monochromatic_15
    name: Color-LED-15
- id: light_monochromatic_16
  component_id: light.monochromatic
  fields:
    output: pwm15
    id: light_monochromatic_16
    name: Color-LED-16
- id: light_rgbw_1
  component_id: light.rgbw
  fields:
    red: pwm1
    green: pwm2
    blue: pwm3
    white: pwm4
    id: light_rgbw_1
    name: ap-rgbw
- id: pwm0
  component_id: output.pca9685
  fields:
    channel: 0
    id: pwm0
  requires:
  - bus_a
  - pca9685_hub
- id: pwm1
  component_id: output.pca9685
  fields:
    channel: 1
    id: pwm1
  requires:
  - bus_a
  - pca9685_hub
- id: pwm2
  component_id: output.pca9685
  fields:
    channel: 2
    id: pwm2
  requires:
  - bus_a
  - pca9685_hub
- id: pwm3
  component_id: output.pca9685
  fields:
    channel: 3
    id: pwm3
  requires:
  - bus_a
  - pca9685_hub
- id: pwm4
  component_id: output.pca9685
  fields:
    channel: 4
    id: pwm4
  requires:
  - bus_a
  - pca9685_hub
- id: pwm5
  component_id: output.pca9685
  fields:
    channel: 5
    id: pwm5
  requires:
  - bus_a
  - pca9685_hub
- id: pwm6
  component_id: output.pca9685
  fields:
    channel: 6
    id: pwm6
  requires:
  - bus_a
  - pca9685_hub
- id: pwm7
  component_id: output.pca9685
  fields:
    channel: 7
    id: pwm7
  requires:
  - bus_a
  - pca9685_hub
- id: pwm8
  component_id: output.pca9685
  fields:
    channel: 8
    id: pwm8
  requires:
  - bus_a
  - pca9685_hub
- id: pwm9
  component_id: output.pca9685
  fields:
    channel: 9
    id: pwm9
  requires:
  - bus_a
  - pca9685_hub
- id: pwm10
  component_id: output.pca9685
  fields:
    channel: 10
    id: pwm10
  requires:
  - bus_a
  - pca9685_hub
- id: pwm11
  component_id: output.pca9685
  fields:
    channel: 11
    id: pwm11
  requires:
  - bus_a
  - pca9685_hub
- id: pwm12
  component_id: output.pca9685
  fields:
    channel: 12
    id: pwm12
  requires:
  - bus_a
  - pca9685_hub
- id: pwm13
  component_id: output.pca9685
  fields:
    channel: 13
    id: pwm13
  requires:
  - bus_a
  - pca9685_hub
- id: pwm14
  component_id: output.pca9685
  fields:
    channel: 14
    id: pwm14
  requires:
  - bus_a
  - pca9685_hub
- id: pwm15
  component_id: output.pca9685
  fields:
    channel: 15
    id: pwm15
  requires:
  - bus_a
  - pca9685_hub
- id: switch_gpio_1
  component_id: switch.gpio
  fields:
    pin:
      value: 13
      locked: true
    inverted:
      value: false
      locked: true
    id: switch_gpio_1
    name: ap-light1
- id: switch_gpio_2
  component_id: switch.gpio
  fields:
    pin:
      value: 2
      locked: true
    inverted:
      value: false
      locked: true
    id: switch_gpio_2
    name: ap-light2
featured_bundles:
- id: light_monochromatic_1_setup
  name: Color-LED-1 (full setup)
  component_ids:
  - bus_a
  - pca9685_hub
  - pwm0
  - light_monochromatic_1
- id: light_monochromatic_2_setup
  name: Color-LED-2 (full setup)
  component_ids:
  - bus_a
  - pca9685_hub
  - pwm1
  - light_monochromatic_2
- id: light_monochromatic_3_setup
  name: Color-LED-3 (full setup)
  component_ids:
  - bus_a
  - pca9685_hub
  - pwm2
  - light_monochromatic_3
- id: light_monochromatic_4_setup
  name: Color-LED-4 (full setup)
  component_ids:
  - bus_a
  - pca9685_hub
  - pwm3
  - light_monochromatic_4
- id: light_monochromatic_5_setup
  name: Color-LED-5 (full setup)
  component_ids:
  - bus_a
  - pca9685_hub
  - pwm4
  - light_monochromatic_5
- id: light_monochromatic_6_setup
  name: Color-LED-6 (full setup)
  component_ids:
  - bus_a
  - pca9685_hub
  - pwm5
  - light_monochromatic_6
- id: light_monochromatic_7_setup
  name: Color-LED-7 (full setup)
  component_ids:
  - bus_a
  - pca9685_hub
  - pwm6
  - light_monochromatic_7
- id: light_monochromatic_8_setup
  name: Color-LED-8 (full setup)
  component_ids:
  - bus_a
  - pca9685_hub
  - pwm7
  - light_monochromatic_8
- id: light_monochromatic_9_setup
  name: Color-LED-9 (full setup)
  component_ids:
  - bus_a
  - pca9685_hub
  - pwm8
  - light_monochromatic_9
- id: light_monochromatic_10_setup
  name: Color-LED-10 (full setup)
  component_ids:
  - bus_a
  - pca9685_hub
  - pwm9
  - light_monochromatic_10
- id: light_monochromatic_11_setup
  name: Color-LED-11 (full setup)
  component_ids:
  - bus_a
  - pca9685_hub
  - pwm10
  - light_monochromatic_11
- id: light_monochromatic_12_setup
  name: Color-LED-12 (full setup)
  component_ids:
  - bus_a
  - pca9685_hub
  - pwm11
  - light_monochromatic_12
- id: light_monochromatic_13_setup
  name: Color-LED-13 (full setup)
  component_ids:
  - bus_a
  - pca9685_hub
  - pwm12
  - light_monochromatic_13
- id: light_monochromatic_14_setup
  name: Color-LED-14 (full setup)
  component_ids:
  - bus_a
  - pca9685_hub
  - pwm13
  - light_monochromatic_14
- id: light_monochromatic_15_setup
  name: Color-LED-15 (full setup)
  component_ids:
  - bus_a
  - pca9685_hub
  - pwm14
  - light_monochromatic_15
- id: light_monochromatic_16_setup
  name: Color-LED-16 (full setup)
  component_ids:
  - bus_a
  - pca9685_hub
  - pwm15
  - light_monochromatic_16
- id: light_rgbw_1_setup
  name: ap-rgbw (full setup)
  component_ids:
  - bus_a
  - pca9685_hub
  - pwm1
  - pwm2
  - pwm3
  - pwm4
  - light_rgbw_1
source:
  type: esphome-devices
  remote_id: KinCony-KC868-AP
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/KinCony-KC868-AP/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: ca26d1245c004ef0b1a973110b52e3b1cef98c55bf6ce765a3505d756832364a
