id: unexpectedmaker_feathers3d
name: Unexpected Maker FeatherS3D
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32-s3-devkitc-1
  variant: esp32s3
  logger_hardware_uart: USB_CDC
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/UnexpectedMaker-FeatherS3D/main_features_feathers3d.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/UnexpectedMaker-FeatherS3D/pins_feathers3d.jpg
pins:
- gpio: 4
  available: false
  occupied_by: ambient_light
- gpio: 13
  available: false
  occupied_by: output_gpio_1
- gpio: 39
  available: false
  occupied_by: LDO2
- gpio: 40
  available: false
  occupied_by: NeoPixel Light
docs_url: https://devices.esphome.io/devices/UnexpectedMaker-FeatherS3D/
featured_components:
- id: onboard_psram
  component_id: psram
  name: PSRAM
  fields:
    mode: quad
    speed: 80MHz
- id: led_rgb
  component_id: light.esp32_rmt_led_strip
  fields:
    rgb_order: GRB
    chipset: ws2812
    pin:
      value: 40
      locked: true
    num_leds: 1
    id: led_rgb
    name: NeoPixel Light
  requires:
  - onboard_psram
- id: output_gpio_1
  component_id: output.gpio
  fields:
    pin:
      value: 13
      locked: true
    id: output_gpio_1
- id: ambient_light
  component_id: sensor.adc
  fields:
    pin:
      value: 4
      locked: true
    id: ambient_light
    name: ambient_light
- id: ldo2_switch
  component_id: switch.gpio
  fields:
    pin:
      value: 39
      locked: true
    restore_mode: ALWAYS_ON
    id: ldo2_switch
    name: LDO2
source:
  type: esphome-devices
  remote_id: UnexpectedMaker-FeatherS3D
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/UnexpectedMaker-FeatherS3D/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 97df3f4c8bbc734c8049403f0ae641f89475ad42b08b8deaff7253f62e0e1460
