id: kincony_b16
name: KinCony-B16 (ESP32-S3 16CH Relay board)
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework: arduino
hardware:
  connectivity:
  - wifi
  - bluetooth
  - ethernet
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KinCony-B16/B16_diagram-1.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KinCony-B16/B16_diagram-2.jpg
tags:
- relay
pins:
- gpio: 0
  available: false
  occupied_by: b16-0
- gpio: 1
  available: false
  occupied_by: Ethernet CLK
- gpio: 2
  available: false
  occupied_by: Ethernet MOSI
- gpio: 7
  available: false
  occupied_by: b16-W1-io7
- gpio: 8
  available: false
  occupied_by: bus_a
- gpio: 13
  available: false
  occupied_by: b16-io13
- gpio: 14
  available: false
  occupied_by: b16-io14
- gpio: 18
  available: false
  occupied_by: bus_a
- gpio: 21
  available: false
  occupied_by: b16-21
- gpio: 38
  available: false
  occupied_by: uart_1
- gpio: 39
  available: false
  occupied_by: uart_1
- gpio: 40
  available: false
  occupied_by: b16-W1-io40
- gpio: 41
  available: false
  occupied_by: Ethernet MISO
- gpio: 42
  available: false
  occupied_by: Ethernet CS
- gpio: 43
  available: false
  occupied_by: Ethernet INT
- gpio: 44
  available: false
  occupied_by: Ethernet RESET
- gpio: 47
  available: false
  occupied_by: b16-W1-io47
- gpio: 48
  available: false
  occupied_by: b16-W1-io48
docs_url: https://devices.esphome.io/devices/KinCony-B16/
featured_components:
- id: uart_1
  component_id: uart
  fields:
    baud_rate: 9600
    debug:
      value:
        direction: BOTH
        dummy_receiver: true
        after:
          timeout: 10ms
      locked: true
    tx_pin:
      value: 39
      locked: true
    rx_pin:
      value: 38
      locked: true
    id:
      value: uart_1
      locked: true
- id: ads1115_hub
  component_id: ads1115
  fields:
    address: 72
  requires:
  - bus_a
- id: bus_a
  component_id: i2c
  fields:
    sda:
      value: 8
      locked: true
    scl:
      value: 18
      locked: true
    scan: true
    frequency: 400kHz
    id:
      value: bus_a
      locked: true
- id: pcf8574_hub_in_1
  component_id: pcf8574
  fields:
    address: 36
    pcf8575: true
    id:
      value: pcf8574_hub_in_1
      locked: true
    i2c_id:
      value: bus_a
      locked: true
  requires:
  - bus_a
- id: pcf8574_hub_out_1
  component_id: pcf8574
  fields:
    address: 34
    pcf8575: true
    id:
      value: pcf8574_hub_out_1
      locked: true
    i2c_id:
      value: bus_a
      locked: true
  requires:
  - bus_a
- id: onboard_ethernet
  component_id: ethernet
  name: Onboard Ethernet
  fields:
    type:
      value: W5500
      locked: true
    clk_pin:
      value: GPIO1
      locked: true
    mosi_pin:
      value: GPIO2
      locked: true
    miso_pin:
      value: GPIO41
      locked: true
    cs_pin:
      value: GPIO42
      locked: true
    interrupt_pin:
      value: GPIO43
      locked: true
    reset_pin:
      value: GPIO44
      locked: true
- id: b16_input01
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 0
        mode: INPUT
        inverted: true
      locked: true
    id: b16_input01
    name: b16-input01
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: b16_input02
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 1
        mode: INPUT
        inverted: true
      locked: true
    id: b16_input02
    name: b16-input02
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: b16_input03
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 2
        mode: INPUT
        inverted: true
      locked: true
    id: b16_input03
    name: b16-input03
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: b16_input04
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 3
        mode: INPUT
        inverted: true
      locked: true
    id: b16_input04
    name: b16-input04
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: b16_input05
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 4
        mode: INPUT
        inverted: true
      locked: true
    id: b16_input05
    name: b16-input05
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: b16_input06
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 5
        mode: INPUT
        inverted: true
      locked: true
    id: b16_input06
    name: b16-input06
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: b16_input07
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 6
        mode: INPUT
        inverted: true
      locked: true
    id: b16_input07
    name: b16-input07
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: b16_input08
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 7
        mode: INPUT
        inverted: true
      locked: true
    id: b16_input08
    name: b16-input08
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: b16_input09
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 8
        mode: INPUT
        inverted: true
      locked: true
    id: b16_input09
    name: b16-input09
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: b16_input10
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 9
        mode: INPUT
        inverted: true
      locked: true
    id: b16_input10
    name: b16-input10
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: b16_input11
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 10
        mode: INPUT
        inverted: true
      locked: true
    id: b16_input11
    name: b16-input11
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: b16_input12
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 11
        mode: INPUT
        inverted: true
      locked: true
    id: b16_input12
    name: b16-input12
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: b16_input13
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 12
        mode: INPUT
        inverted: true
      locked: true
    id: b16_input13
    name: b16-input13
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: b16_input14
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 13
        mode: INPUT
        inverted: true
      locked: true
    id: b16_input14
    name: b16-input14
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: b16_input15
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 14
        mode: INPUT
        inverted: true
      locked: true
    id: b16_input15
    name: b16-input15
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: b16_input16
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 15
        mode: INPUT
        inverted: true
      locked: true
    id: b16_input16
    name: b16-input16
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_17
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 48
        inverted: true
      locked: true
    id: binary_sensor_gpio_17
    name: b16-W1-io48
- id: binary_sensor_gpio_18
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 47
        inverted: true
      locked: true
    id: binary_sensor_gpio_18
    name: b16-W1-io47
- id: binary_sensor_gpio_19
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 40
        inverted: true
      locked: true
    id: binary_sensor_gpio_19
    name: b16-W1-io40
- id: binary_sensor_gpio_20
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 7
        inverted: true
      locked: true
    id: binary_sensor_gpio_20
    name: b16-W1-io7
- id: binary_sensor_gpio_21
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 13
        inverted: false
      locked: true
    id: binary_sensor_gpio_21
    name: b16-io13
- id: binary_sensor_gpio_22
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 14
        inverted: false
      locked: true
    id: binary_sensor_gpio_22
    name: b16-io14
- id: binary_sensor_gpio_23
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 21
        inverted: false
      locked: true
    id: binary_sensor_gpio_23
    name: b16-21
- id: binary_sensor_gpio_24
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 0
        inverted: false
      locked: true
    id: binary_sensor_gpio_24
    name: b16-0
- id: sensor_ads1115_1
  component_id: sensor.ads1115
  fields:
    multiplexer: A0_GND
    gain: 6.144
    resolution: 16_BITS
    update_interval: 5s
    id: sensor_ads1115_1
    name: ADS1115 Channel A0-GND
  requires:
  - bus_a
  - ads1115_hub
- id: sensor_ads1115_2
  component_id: sensor.ads1115
  fields:
    multiplexer: A1_GND
    gain: 6.144
    update_interval: 5s
    id: sensor_ads1115_2
    name: ADS1115 Channel A1-GND
  requires:
  - bus_a
  - ads1115_hub
- id: sensor_ads1115_3
  component_id: sensor.ads1115
  fields:
    multiplexer: A2_GND
    gain: 6.144
    update_interval: 5s
    id: sensor_ads1115_3
    name: ADS1115 Channel A2-GND
  requires:
  - bus_a
  - ads1115_hub
- id: sensor_ads1115_4
  component_id: sensor.ads1115
  fields:
    multiplexer: A3_GND
    gain: 6.144
    update_interval: 5s
    id: sensor_ads1115_4
    name: ADS1115 Channel A3-GND
  requires:
  - bus_a
  - ads1115_hub
- id: switch_uart_1
  component_id: switch.uart
  fields:
    data:
      value:
      - 17
      - 34
      - 51
      - 68
      - 85
      locked: true
    id: switch_uart_1
    name: RS485 Button
    uart_id:
      value: uart_1
      locked: true
  requires:
  - uart_1
- id: b16_output01
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 0
        mode: OUTPUT
        inverted: true
      locked: true
    id: b16_output01
    name: b16-output01
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: b16_output02
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 1
        mode: OUTPUT
        inverted: true
      locked: true
    id: b16_output02
    name: b16-output02
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: b16_output03
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 2
        mode: OUTPUT
        inverted: true
      locked: true
    id: b16_output03
    name: b16-output03
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: b16_output04
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 3
        mode: OUTPUT
        inverted: true
      locked: true
    id: b16_output04
    name: b16-output04
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: b16_output05
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 4
        mode: OUTPUT
        inverted: true
      locked: true
    id: b16_output05
    name: b16-output05
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: b16_output06
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 5
        mode: OUTPUT
        inverted: true
      locked: true
    id: b16_output06
    name: b16-output06
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: b16_output07
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 6
        mode: OUTPUT
        inverted: true
      locked: true
    id: b16_output07
    name: b16-output07
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: b16_output08
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 7
        mode: OUTPUT
        inverted: true
      locked: true
    id: b16_output08
    name: b16-output08
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: b16_output09
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 8
        mode: OUTPUT
        inverted: true
      locked: true
    id: b16_output09
    name: b16-output09
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: b16_output10
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 9
        mode: OUTPUT
        inverted: true
      locked: true
    id: b16_output10
    name: b16-output10
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: b16_output11
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 10
        mode: OUTPUT
        inverted: true
      locked: true
    id: b16_output11
    name: b16-output11
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: b16_output12
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 11
        mode: OUTPUT
        inverted: true
      locked: true
    id: b16_output12
    name: b16-output12
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: b16_output13
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 12
        mode: OUTPUT
        inverted: true
      locked: true
    id: b16_output13
    name: b16-output13
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: b16_output14
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 13
        mode: OUTPUT
        inverted: true
      locked: true
    id: b16_output14
    name: b16-output14
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: b16_output15
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 14
        mode: OUTPUT
        inverted: true
      locked: true
    id: b16_output15
    name: b16-output15
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: b16_output16
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 15
        mode: OUTPUT
        inverted: true
      locked: true
    id: b16_output16
    name: b16-output16
  requires:
  - bus_a
  - pcf8574_hub_out_1
source:
  type: esphome-devices
  remote_id: KinCony-B16
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/KinCony-B16/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 77444d67995ea74287dbfbd9a92b3cb894eeaf4be45b0bd0818cb7b930fcd5c5
