id: aubess_wifi_smart_switch_with_power_monitoring
name: Aubess WiFi Smart Switch with Power Monitoring
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: generic-bk7231n-qfn32-tuya
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Aubess-WiFi-Smart-Switch-with-Power-Monitoring/Aubess-WiFi-Smart-Switch-with-Power-Monitoring.jpg
pins:
- gpio: 23
  available: false
  occupied_by: AubessPM01_button
- gpio: 24
  available: false
  occupied_by: AubessPM01_switch
- gpio: 26
  available: false
  occupied_by: Geyser
docs_url: https://devices.esphome.io/devices/Aubess-WiFi-Smart-Switch-with-Power-Monitoring/
featured_components:
- id: aubesspm01_button
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 23
        mode:
          input: true
          pullup: true
      locked: true
    id: aubesspm01_button
    name: AubessPM01_button
- id: aubesspm01_switch
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 24
        mode:
          input: true
          pullup: true
      locked: true
    id: aubesspm01_switch
    name: AubessPM01_switch
- id: wifi_signal_db
  component_id: sensor.wifi_signal
  fields:
    update_interval: 10s
    id: wifi_signal_db
    name: wifi_signal_db
- id: aubespm01
  component_id: switch.gpio
  fields:
    pin:
      value: 26
      locked: true
    icon: mdi:water-boiler
    restore_mode: RESTORE_DEFAULT_OFF
    id: aubespm01
    name: Geyser
source:
  type: esphome-devices
  remote_id: Aubess-WiFi-Smart-Switch-with-Power-Monitoring
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Aubess-WiFi-Smart-Switch-with-Power-Monitoring/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 463e62b339c7696d2f1c1e7258a42e1fea3f1437055b9329a41291644fda52d0
