id: sonoff_sv
name: Sonoff SV
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Sonoff-SV/Sonoff_SV.jpg
tags:
- relay
- sonoff
pins:
- gpio: 0
  available: false
  occupied_by: Button
- gpio: 12
  available: false
  occupied_by: Outlet
docs_url: https://devices.esphome.io/devices/Sonoff-SV/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 0
        mode: INPUT_PULLUP
        inverted: true
      locked: true
    id: binary_sensor_gpio_1
    name: Button
- id: relay
  component_id: switch.gpio
  fields:
    icon: mdi:power-socket-au
    pin:
      value: 12
      locked: true
    id: relay
    name: Outlet
source:
  type: esphome-devices
  remote_id: Sonoff-SV
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Sonoff-SV/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: bb63e4f13e39091d409b12f25a8da874d96bdc0a382136e8de2b542be2bb648e
