id: xtendlan_ip66_dual
name: XtendLan chytrá venkovní zásuvka/ IP66/ dvojitá
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp8285
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/XtendLan-IP66-Dual/Whole.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/XtendLan-IP66-Dual/ESP-Pinout.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/XtendLan-IP66-Dual/ESP-Pinout2.jpg
tags:
- relay
- compact
pins:
- gpio: 0
  available: false
  occupied_by: Socket 1 Button 1
- gpio: 5
  available: false
  occupied_by: Socket 1 rele 2
- gpio: 9
  available: false
  occupied_by: Socket 1 Button 2
- gpio: 12
  available: false
  occupied_by: Socket 1 rele 1
docs_url: https://devices.esphome.io/devices/XtendLan-IP66-Dual/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 0
        mode:
          input: true
          pullup: true
        inverted: true
      locked: true
    id: binary_sensor_gpio_1
    name: Socket 1 Button 1
- id: binary_sensor_gpio_2
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 9
        mode:
          input: true
          pullup: true
        inverted: true
      locked: true
    id: binary_sensor_gpio_2
    name: Socket 1 Button 2
- id: sensor_wifi_signal_1
  component_id: sensor.wifi_signal
  fields:
    update_interval: 60s
    id: sensor_wifi_signal_1
    name: Socket 1 WiFi Signal Sensor
- id: relay1
  component_id: switch.gpio
  fields:
    pin:
      value: 12
      locked: true
    id: relay1
    name: Socket 1 rele 1
- id: relay2
  component_id: switch.gpio
  fields:
    pin:
      value: 5
      locked: true
    id: relay2
    name: Socket 1 rele 2
source:
  type: esphome-devices
  remote_id: XtendLan-IP66-Dual
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/XtendLan-IP66-Dual/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 7fe0eb898bad0019b05055bc90ed3183722e014ed1331b3594c27233dd171bf0
