id: waveshare_epaper_cloud_module
name: Waveshare E-Paper Cloud module
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32dev
  variant: esp32
  framework: arduino
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Waveshare-epaper-cloud-module/waveshare213_front.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Waveshare-epaper-cloud-module/waveshare213_back.jpg
pins:
- gpio: 12
  available: false
  occupied_by: waveshare button
- gpio: 36
  available: false
  occupied_by: waveshare Battery voltage
docs_url: https://devices.esphome.io/devices/Waveshare-epaper-cloud-module/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 12
        inverted: true
        mode:
          input: true
          pullup: true
      locked: true
    filters:
      value:
      - delayed_on: 50ms
      locked: true
    id: binary_sensor_gpio_1
    name: waveshare button
- id: battery_voltage
  component_id: sensor.adc
  fields:
    pin:
      value: 36
      locked: true
    icon: mdi:battery
    device_class: voltage
    attenuation: auto
    filters:
      value:
      - multiply: 3
      locked: true
    update_interval: 60s
    id: battery_voltage
    name: waveshare Battery voltage
source:
  type: esphome-devices
  remote_id: Waveshare-epaper-cloud-module
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Waveshare-epaper-cloud-module/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 27caa0edd34b5bf5c8fe82760625fe8462304b6e451336811555a837e1b0346d
