id: nous_b3t
name: NOUS B3T
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32dev
  variant: esp32
  framework: esp-idf
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Nous-B3T/B3T_mockup.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Nous-B3T/pinout.png
tags:
- relay
pins:
- gpio: 0
  available: false
  occupied_by: Status LED
- gpio: 4
  available: false
  occupied_by: button
- gpio: 5
  available: false
  occupied_by: Switch 1 (external)
- gpio: 12
  available: false
  occupied_by: Switch 1
- gpio: 13
  available: false
  occupied_by: Switch 2
- gpio: 18
  available: false
  occupied_by: Switch 2 (external)
docs_url: https://devices.esphome.io/devices/Nous-B3T/
featured_components:
- id: button
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 4
        mode:
          input: true
          pullup: true
        inverted: true
      locked: true
    internal: true
    filters:
      value:
      - invert: null
      - delayed_off: 50ms
      locked: true
    id: button
    name: button
- id: switch_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 5
        mode: INPUT_PULLUP
        inverted: true
        ignore_strapping_warning: true
      locked: true
    icon: mdi:light-switch
    entity_category: diagnostic
    filters:
      value:
      - delayed_on_off: 50ms
      locked: true
    id: switch_1
    name: Switch 1 (external)
- id: switch_2
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 18
        mode: INPUT_PULLUP
        inverted: true
      locked: true
    icon: mdi:light-switch
    entity_category: diagnostic
    filters:
      value:
      - delayed_on_off: 50ms
      locked: true
    id: switch_2
    name: Switch 2 (external)
- id: default_status_led
  component_id: light.status_led
  fields:
    pin:
      value:
        number: 0
        inverted: true
        ignore_strapping_warning: true
      locked: true
    entity_category: config
    id: default_status_led
    name: Status LED
- id: relay_1
  component_id: switch.gpio
  fields:
    pin:
      value:
        number: 12
        ignore_strapping_warning: true
      locked: true
    device_class: switch
    restore_mode: restore_default_on
    id: relay_1
    name: Switch 1
- id: relay_2
  component_id: switch.gpio
  fields:
    pin:
      value: 13
      locked: true
    device_class: switch
    restore_mode: restore_default_on
    id: relay_2
    name: Switch 2
source:
  type: esphome-devices
  remote_id: Nous-B3T
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Nous-B3T/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: a4605e782cd37ecf47e5db4b0f3ffa7c92073b27f6ad6e941ddd9589ab8a6836
