id: kincony_kc868_a16
name: KinCony KC868-A16
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32dev
  variant: esp32
  framework: esp-idf
hardware:
  connectivity:
  - wifi
  - bluetooth
  - ethernet
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KinCony-KC868-A16/kc868-a16.jpg
tags:
- relay
pins:
- gpio: 4
  available: false
  occupied_by: i2c
- gpio: 5
  available: false
  occupied_by: i2c
- gpio: 14
  available: false
  occupied_by: KC868-A16-HT3
- gpio: 17
  available: false
  occupied_by: Ethernet CLK
- gpio: 18
  available: false
  occupied_by: Ethernet MDIO
- gpio: 23
  available: false
  occupied_by: Ethernet MDC
- gpio: 32
  available: false
  occupied_by: KC868-A16-HT1
- gpio: 33
  available: false
  occupied_by: KC868-A16-HT2
docs_url: https://devices.esphome.io/devices/KinCony-KC868-A16/
featured_components:
- id: i2c_bus
  component_id: i2c
  fields:
    sda:
      value: 4
      locked: true
    scl:
      value:
        number: 5
        ignore_strapping_warning: true
      locked: true
- id: inputs_1_8
  component_id: pcf8574
  fields:
    address: 34
    pcf8575: false
    id:
      value: inputs_1_8
      locked: true
  requires:
  - i2c_bus
- id: inputs_9_16
  component_id: pcf8574
  fields:
    address: 33
    pcf8575: false
    id:
      value: inputs_9_16
      locked: true
  requires:
  - i2c_bus
- id: outputs_1_8
  component_id: pcf8574
  fields:
    address: 36
    pcf8575: false
    id:
      value: outputs_1_8
      locked: true
  requires:
  - i2c_bus
- id: outputs_9_16
  component_id: pcf8574
  fields:
    address: 37
    pcf8575: false
    id:
      value: outputs_9_16
      locked: true
  requires:
  - i2c_bus
- id: onboard_ethernet
  component_id: ethernet
  name: Onboard Ethernet
  fields:
    type:
      value: LAN8720
      locked: true
    mdc_pin:
      value: GPIO23
      locked: true
    mdio_pin:
      value: GPIO18
      locked: true
    clk:
      value:
        pin: GPIO17
        mode: CLK_OUT
      locked: true
    phy_addr:
      value: 0
      locked: true
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 32
        inverted: true
      locked: true
    id: binary_sensor_gpio_1
    name: KC868-A16-HT1
- id: binary_sensor_gpio_2
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 33
        inverted: true
      locked: true
    id: binary_sensor_gpio_2
    name: KC868-A16-HT2
- id: binary_sensor_gpio_3
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 14
        inverted: true
      locked: true
    id: binary_sensor_gpio_3
    name: KC868-A16-HT3
- id: binary_sensor_gpio_4
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: inputs_1_8
        number: 0
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_4
    name: KC868-A16-X01
  requires:
  - i2c_bus
  - inputs_1_8
- id: binary_sensor_gpio_5
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: inputs_1_8
        number: 1
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_5
    name: KC868-A16-X02
  requires:
  - i2c_bus
  - inputs_1_8
- id: binary_sensor_gpio_6
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: inputs_1_8
        number: 2
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_6
    name: KC868-A16-X03
  requires:
  - i2c_bus
  - inputs_1_8
- id: binary_sensor_gpio_7
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: inputs_1_8
        number: 3
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_7
    name: KC868-A16-X04
  requires:
  - i2c_bus
  - inputs_1_8
- id: binary_sensor_gpio_8
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: inputs_1_8
        number: 4
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_8
    name: KC868-A16-X05
  requires:
  - i2c_bus
  - inputs_1_8
- id: binary_sensor_gpio_9
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: inputs_1_8
        number: 5
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_9
    name: KC868-A16-X06
  requires:
  - i2c_bus
  - inputs_1_8
- id: binary_sensor_gpio_10
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: inputs_1_8
        number: 6
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_10
    name: KC868-A16-X07
  requires:
  - i2c_bus
  - inputs_1_8
- id: binary_sensor_gpio_11
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: inputs_1_8
        number: 7
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_11
    name: KC868-A16-X08
  requires:
  - i2c_bus
  - inputs_1_8
- id: binary_sensor_gpio_12
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: inputs_9_16
        number: 0
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_12
    name: KC868-A16-X09
  requires:
  - i2c_bus
  - inputs_9_16
- id: binary_sensor_gpio_13
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: inputs_9_16
        number: 1
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_13
    name: KC868-A16-X10
  requires:
  - i2c_bus
  - inputs_9_16
- id: binary_sensor_gpio_14
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: inputs_9_16
        number: 2
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_14
    name: KC868-A16-X11
  requires:
  - i2c_bus
  - inputs_9_16
- id: binary_sensor_gpio_15
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: inputs_9_16
        number: 3
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_15
    name: KC868-A16-X12
  requires:
  - i2c_bus
  - inputs_9_16
- id: binary_sensor_gpio_16
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: inputs_9_16
        number: 4
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_16
    name: KC868-A16-X13
  requires:
  - i2c_bus
  - inputs_9_16
- id: binary_sensor_gpio_17
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: inputs_9_16
        number: 5
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_17
    name: KC868-A16-X14
  requires:
  - i2c_bus
  - inputs_9_16
- id: binary_sensor_gpio_18
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: inputs_9_16
        number: 6
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_18
    name: KC868-A16-X15
  requires:
  - i2c_bus
  - inputs_9_16
- id: binary_sensor_gpio_19
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: inputs_9_16
        number: 7
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_19
    name: KC868-A16-X16
  requires:
  - i2c_bus
  - inputs_9_16
- id: out_y01
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: outputs_1_8
        number: 0
        mode: OUTPUT
        inverted: true
      locked: true
    id: out_y01
    name: KC868-A16-Y01
  requires:
  - i2c_bus
  - outputs_1_8
- id: out_y02
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: outputs_1_8
        number: 1
        mode: OUTPUT
        inverted: true
      locked: true
    id: out_y02
    name: KC868-A16-Y02
  requires:
  - i2c_bus
  - outputs_1_8
- id: out_y03
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: outputs_1_8
        number: 2
        mode: OUTPUT
        inverted: true
      locked: true
    id: out_y03
    name: KC868-A16-Y03
  requires:
  - i2c_bus
  - outputs_1_8
- id: out_y04
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: outputs_1_8
        number: 3
        mode: OUTPUT
        inverted: true
      locked: true
    id: out_y04
    name: KC868-A16-Y04
  requires:
  - i2c_bus
  - outputs_1_8
- id: out_y05
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: outputs_1_8
        number: 4
        mode: OUTPUT
        inverted: true
      locked: true
    id: out_y05
    name: KC868-A16-Y05
  requires:
  - i2c_bus
  - outputs_1_8
- id: out_y06
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: outputs_1_8
        number: 5
        mode: OUTPUT
        inverted: true
      locked: true
    id: out_y06
    name: KC868-A16-Y06
  requires:
  - i2c_bus
  - outputs_1_8
- id: out_y07
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: outputs_1_8
        number: 6
        mode: OUTPUT
        inverted: true
      locked: true
    id: out_y07
    name: KC868-A16-Y07
  requires:
  - i2c_bus
  - outputs_1_8
- id: out_y08
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: outputs_1_8
        number: 7
        mode: OUTPUT
        inverted: true
      locked: true
    id: out_y08
    name: KC868-A16-Y08
  requires:
  - i2c_bus
  - outputs_1_8
- id: out_y09
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: outputs_9_16
        number: 0
        mode: OUTPUT
        inverted: true
      locked: true
    id: out_y09
    name: KC868-A16-Y09
  requires:
  - i2c_bus
  - outputs_9_16
- id: out_y10
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: outputs_9_16
        number: 1
        mode: OUTPUT
        inverted: true
      locked: true
    id: out_y10
    name: KC868-A16-Y10
  requires:
  - i2c_bus
  - outputs_9_16
- id: out_y11
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: outputs_9_16
        number: 2
        mode: OUTPUT
        inverted: true
      locked: true
    id: out_y11
    name: KC868-A16-Y11
  requires:
  - i2c_bus
  - outputs_9_16
- id: out_y12
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: outputs_9_16
        number: 3
        mode: OUTPUT
        inverted: true
      locked: true
    id: out_y12
    name: KC868-A16-Y12
  requires:
  - i2c_bus
  - outputs_9_16
- id: out_y13
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: outputs_9_16
        number: 4
        mode: OUTPUT
        inverted: true
      locked: true
    id: out_y13
    name: KC868-A16-Y13
  requires:
  - i2c_bus
  - outputs_9_16
- id: out_y14
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: outputs_9_16
        number: 5
        mode: OUTPUT
        inverted: true
      locked: true
    id: out_y14
    name: KC868-A16-Y14
  requires:
  - i2c_bus
  - outputs_9_16
- id: out_y15
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: outputs_9_16
        number: 6
        mode: OUTPUT
        inverted: true
      locked: true
    id: out_y15
    name: KC868-A16-Y15
  requires:
  - i2c_bus
  - outputs_9_16
- id: out_y16
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: outputs_9_16
        number: 7
        mode: OUTPUT
        inverted: true
      locked: true
    id: out_y16
    name: KC868-A16-Y16
  requires:
  - i2c_bus
  - outputs_9_16
source:
  type: esphome-devices
  remote_id: KinCony-KC868-A16
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/KinCony-KC868-A16/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: aa7e216737518ffa1dbe9bffc6bacb5c9024cc5afe3f3448231cc479f7db2449
