id: tuya_dy_ck400a_garage_door_opener
name: Tuya DY-CK400A Garage Door Opener
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp_wroom_02
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tuya-DY-CK400A-Garage-Door-Opener/device.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tuya-DY-CK400A-Garage-Door-Opener/board.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tuya-DY-CK400A-Garage-Door-Opener/programming-pins.png
pins:
- gpio: 13
  available: false
  occupied_by: uart
- gpio: 15
  available: false
  occupied_by: uart
docs_url: https://devices.esphome.io/devices/Tuya-DY-CK400A-Garage-Door-Opener/
featured_components:
- id: uart_bus
  component_id: uart
  fields:
    rx_pin:
      value: 13
      locked: true
    tx_pin:
      value: 15
      locked: true
    baud_rate: 9600
- id: tuya_hub
  component_id: tuya
  fields: {}
  requires:
  - uart_bus
- id: contact
  component_id: binary_sensor.tuya
  fields:
    sensor_datapoint: 101
    id: contact
    name: contact
  requires:
  - uart_bus
  - tuya_hub
- id: mcu_cover
  component_id: switch.tuya
  fields:
    switch_datapoint: 1
    id: mcu_cover
    name: mcu_cover
  requires:
  - uart_bus
  - tuya_hub
source:
  type: esphome-devices
  remote_id: Tuya-DY-CK400A-Garage-Door-Opener
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Tuya-DY-CK400A-Garage-Door-Opener/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: f727dbfaed5cfbcded5446442a59ef31ed3c45ef182dcb2bd65bf4cdbfbaf7ee
