id: homemaster_microplc
name: Homemaster-MicroPLC
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32dev
  variant: esp32
  framework: esp-idf
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Homemaster-MicroPLC/MicroPLC.png
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Homemaster-MicroPLC/pinout_MicroPLC.png
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Homemaster-MicroPLC/diagram.png
tags:
- relay
pins:
- gpio: 26
  available: false
  occupied_by: Relay
docs_url: https://devices.esphome.io/devices/Homemaster-MicroPLC/
product_url: https://github.com/isystemsautomation/HOMEMASTER/tree/main/MicroPLC
featured_components:
- id: relay1
  component_id: switch.gpio
  fields:
    pin:
      value: 26
      locked: true
    id: relay1
    name: Relay
source:
  type: esphome-devices
  remote_id: Homemaster-MicroPLC
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Homemaster-MicroPLC/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: c1dcdfb24f96200915da88f97c8514ed44d81689e912cad9769f99a2a1c45504
