id: milfra_smart_dimmer_switch
name: Milfra Smart Dimmer Switch
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: cbu
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Milfra-Smart-Dimmer-Switch/Milfra-Dimmer-Front.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Milfra-Smart-Dimmer-Switch/Milfra-Dimmer-Back.jpg
pins:
- gpio: 10
  available: false
  occupied_by: uart
- gpio: 11
  available: false
  occupied_by: uart
docs_url: https://devices.esphome.io/devices/Milfra-Smart-Dimmer-Switch/
featured_components:
- id: uart_bus
  component_id: uart
  fields:
    rx_pin:
      value: 10
      locked: true
    tx_pin:
      value: 11
      locked: true
    baud_rate: 115200
- id: tuya_hub
  component_id: tuya
  fields: {}
  requires:
  - uart_bus
- id: light_tuya_1
  component_id: light.tuya
  fields:
    dimmer_datapoint: 2
    min_value_datapoint: 3
    switch_datapoint: 1
    min_value: 200
    max_value: 1000
    id: light_tuya_1
    name: dimmer
  requires:
  - uart_bus
  - tuya_hub
source:
  type: esphome-devices
  remote_id: Milfra-Smart-Dimmer-Switch
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Milfra-Smart-Dimmer-Switch/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 8bde9ff4144fabce6e310922909196d6c39d538abba9584945a3c75f5c875cd6
