id: genvex_nibe_alphainnotec_heat_recovery_ventilation
name: Genvex ECO 375, Nibe ERS 10-500, Alpha-Innotec LG 300 ECO B(E) ventilation
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32dev
  variant: esp32
hardware:
  connectivity:
  - wifi
  - bluetooth
  - ethernet
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Genvex-Nibe-AlphaInnotec-heat-recovery-ventilation/ECO-375-mark2-lukket.jpg
pins:
- gpio: 0
  available: false
  occupied_by: Ethernet CLK
- gpio: 4
  available: false
  occupied_by: mbus
- gpio: 14
  available: false
  occupied_by: modbus1
- gpio: 18
  available: false
  occupied_by: Ethernet MDIO
- gpio: 23
  available: false
  occupied_by: Ethernet MDC
- gpio: 36
  available: false
  occupied_by: mbus
docs_url: https://devices.esphome.io/devices/Genvex-Nibe-AlphaInnotec-heat-recovery-ventilation/
featured_components:
- id: modbus1
  component_id: modbus
  fields:
    flow_control_pin:
      value: 14
      locked: true
    id:
      value: modbus1
      locked: true
    uart_id:
      value: mbus
      locked: true
  requires:
  - mbus
- id: mbus
  component_id: uart
  fields:
    tx_pin:
      value: 4
      locked: true
    rx_pin:
      value: 36
      locked: true
    baud_rate: 19600
    parity: EVEN
    id:
      value: mbus
      locked: true
- id: genvex_modbus
  component_id: modbus_controller
  fields:
    address: 1
    setup_priority: -10
    command_throttle: 20ms
    update_interval: 5s
    id:
      value: genvex_modbus
      locked: true
    modbus_id:
      value: modbus1
      locked: true
  requires:
  - modbus1
  - mbus
- id: onboard_ethernet
  component_id: ethernet
  name: Onboard Ethernet
  fields:
    type:
      value: LAN8720
      locked: true
    mdc_pin:
      value: GPIO23
      locked: true
    mdio_pin:
      value: GPIO18
      locked: true
    phy_addr:
      value: 0
      locked: true
    clk:
      value:
        pin: GPIO0
        mode: CLK_EXT_IN
      locked: true
- id: binary_sensor_modbus_controller_1
  component_id: binary_sensor.modbus_controller
  fields:
    device_class: problem
    register_type: read
    entity_category: diagnostic
    address: 15
    bitmask: 1
    id: binary_sensor_modbus_controller_1
    name: Alarm General Error
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: binary_sensor_modbus_controller_2
  component_id: binary_sensor.modbus_controller
  fields:
    device_class: opening
    register_type: read
    entity_category: diagnostic
    address: 15
    bitmask: 2
    id: binary_sensor_modbus_controller_2
    name: Bypass1
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: binary_sensor_modbus_controller_3
  component_id: binary_sensor.modbus_controller
  fields:
    register_type: read
    entity_category: diagnostic
    address: 15
    bitmask: 4
    id: binary_sensor_modbus_controller_3
    name: Relay R9
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: binary_sensor_modbus_controller_4
  component_id: binary_sensor.modbus_controller
  fields:
    device_class: problem
    register_type: read
    entity_category: diagnostic
    address: 15
    bitmask: 8
    id: binary_sensor_modbus_controller_4
    name: Alarm Filter
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: binary_sensor_modbus_controller_5
  component_id: binary_sensor.modbus_controller
  fields:
    device_class: problem
    register_type: read
    entity_category: diagnostic
    address: 15
    bitmask: 16
    id: binary_sensor_modbus_controller_5
    name: Alarm Frost
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: binary_sensor_modbus_controller_6
  component_id: binary_sensor.modbus_controller
  fields:
    device_class: problem
    register_type: read
    entity_category: diagnostic
    address: 15
    bitmask: 64
    id: binary_sensor_modbus_controller_6
    name: Alarm Hygrostat
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: binary_sensor_modbus_controller_7
  component_id: binary_sensor.modbus_controller
  fields:
    device_class: problem
    register_type: read
    entity_category: diagnostic
    address: 15
    bitmask: 128
    id: binary_sensor_modbus_controller_7
    name: Alarm Device Stopped
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: binary_sensor_modbus_controller_8
  component_id: binary_sensor.modbus_controller
  fields:
    device_class: opening
    register_type: read
    entity_category: diagnostic
    address: 15
    bitmask: 1024
    id: binary_sensor_modbus_controller_8
    name: Bypass2
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: binary_sensor_modbus_controller_9
  component_id: binary_sensor.modbus_controller
  fields:
    register_type: read
    entity_category: diagnostic
    address: 15
    bitmask: 4096
    disabled_by_default: true
    id: binary_sensor_modbus_controller_9
    name: Relay R8
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: binary_sensor_modbus_controller_10
  component_id: binary_sensor.modbus_controller
  fields:
    register_type: read
    entity_category: diagnostic
    address: 15
    bitmask: 8192
    disabled_by_default: true
    id: binary_sensor_modbus_controller_10
    name: Relay R2 Electric Reheating
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: binary_sensor_modbus_controller_11
  component_id: binary_sensor.modbus_controller
  fields:
    register_type: read
    entity_category: diagnostic
    address: 15
    bitmask: 16384
    disabled_by_default: true
    id: binary_sensor_modbus_controller_11
    name: Relay R3 Preheating
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: button_restart_1
  component_id: button.restart
  fields:
    entity_category: diagnostic
    id: button_restart_1
    name: Ventitaltion controller restart
- id: button_safe_mode_1
  component_id: button.safe_mode
  fields:
    entity_category: diagnostic
    id: button_safe_mode_1
    name: Ventitaltion controller safe mode boot
- id: number_modbus_controller_1
  component_id: number.modbus_controller
  fields:
    icon: mdi:timer-sand
    address: 14
    unit_of_measurement: h
    value_type: U_WORD
    entity_category: config
    min_value: 1
    max_value: 9
    step: 1
    mode: box
    id: number_modbus_controller_1
    name: Ventitaltion Max duration for level 3-4
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: genvex_speed_in_1
  component_id: number.modbus_controller
  fields:
    icon: mdi:fan-speed-1
    address: 7
    unit_of_measurement: '%'
    value_type: U_WORD
    entity_category: config
    min_value: 10
    max_value: 45
    step: 1
    mode: box
    id: genvex_speed_in_1
    name: Ventitaltion Level 1 supply
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: genvex_speed_out_1
  component_id: number.modbus_controller
  fields:
    icon: mdi:fan-speed-1
    address: 10
    unit_of_measurement: '%'
    value_type: U_WORD
    entity_category: config
    min_value: 10
    max_value: 45
    step: 1
    mode: box
    id: genvex_speed_out_1
    name: Ventitaltion Level 1 extract
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: genvex_speed_in_2
  component_id: number.modbus_controller
  fields:
    icon: mdi:fan-speed-2
    address: 8
    unit_of_measurement: '%'
    value_type: U_WORD
    entity_category: config
    min_value: 40
    max_value: 75
    step: 1
    mode: box
    id: genvex_speed_in_2
    name: Ventitaltion Level 2 supply
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: genvex_speed_out_2
  component_id: number.modbus_controller
  fields:
    icon: mdi:fan-speed-2
    address: 11
    unit_of_measurement: '%'
    value_type: U_WORD
    entity_category: config
    min_value: 40
    max_value: 75
    step: 1
    mode: box
    id: genvex_speed_out_2
    name: Ventitaltion Level 2 extract
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: genvex_speed_in_3
  component_id: number.modbus_controller
  fields:
    icon: mdi:fan-speed-3
    address: 9
    unit_of_measurement: '%'
    value_type: U_WORD
    entity_category: config
    min_value: 60
    max_value: 85
    step: 1
    mode: box
    id: genvex_speed_in_3
    name: Ventitaltion Level 3 supply
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: genvex_speed_out_3
  component_id: number.modbus_controller
  fields:
    icon: mdi:fan-speed-3
    address: 12
    unit_of_measurement: '%'
    value_type: U_WORD
    entity_category: config
    min_value: 60
    max_value: 85
    step: 1
    mode: box
    id: genvex_speed_out_3
    name: Ventitaltion Level 3 extract
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: number_modbus_controller_8
  component_id: number.modbus_controller
  fields:
    unit_of_measurement: °C
    icon: mdi:cog-outline
    address: 26
    value_type: U_WORD
    entity_category: config
    min_value: 0
    max_value: 20
    step: 1
    mode: box
    id: number_modbus_controller_8
    name: Ventitaltion Bypass close external delta
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: number_modbus_controller_9
  component_id: number.modbus_controller
  fields:
    unit_of_measurement: mo
    icon: mdi:cog-outline
    address: 5
    value_type: U_WORD
    entity_category: config
    min_value: 0
    max_value: 12
    step: 1
    mode: box
    disabled_by_default: true
    id: number_modbus_controller_9
    name: Ventitaltion Filter change period
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: genvex_inlet_fan
  component_id: sensor.modbus_controller
  fields:
    icon: mdi:fan
    register_type: read
    address: 9
    unit_of_measurement: '%'
    value_type: U_WORD
    id: genvex_inlet_fan
    name: Ventitaltion Inlet fan
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: genvex_extract_fan
  component_id: sensor.modbus_controller
  fields:
    icon: mdi:fan
    register_type: read
    address: 10
    unit_of_measurement: '%'
    value_type: U_WORD
    id: genvex_extract_fan
    name: Ventitaltion Extract fan
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: sensor_modbus_controller_3
  component_id: sensor.modbus_controller
  fields:
    device_class: temperature
    register_type: read
    address: 0
    unit_of_measurement: °C
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      value:
      - filter_out: 0
      - heartbeat: 120s
      - offset: -300
      - multiply: 0.1
      locked: true
    id: sensor_modbus_controller_3
    name: Ventitaltion Supply air
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: sensor_modbus_controller_4
  component_id: sensor.modbus_controller
  fields:
    device_class: temperature
    register_type: read
    address: 2
    unit_of_measurement: °C
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      value:
      - filter_out: 0
      - heartbeat: 120s
      - offset: -300
      - multiply: 0.1
      locked: true
    id: sensor_modbus_controller_4
    name: Ventitaltion Fresh air
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: sensor_modbus_controller_5
  component_id: sensor.modbus_controller
  fields:
    device_class: temperature
    register_type: read
    address: 3
    unit_of_measurement: °C
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      value:
      - filter_out: 0
      - heartbeat: 120s
      - offset: -300
      - multiply: 0.1
      locked: true
    id: sensor_modbus_controller_5
    name: Ventitaltion Exhaust air
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: genvex_temp_t7
  component_id: sensor.modbus_controller
  fields:
    device_class: temperature
    register_type: read
    address: 6
    unit_of_measurement: °C
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      value:
      - filter_out: 0
      - heartbeat: 120s
      - offset: -300
      - multiply: 0.1
      locked: true
    id: genvex_temp_t7
    name: Ventitaltion Extract air
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: sensor_modbus_controller_7
  component_id: sensor.modbus_controller
  fields:
    icon: mdi:debug-step-over
    unit_of_measurement: '%'
    register_type: read
    address: 11
    value_type: U_WORD
    id: sensor_modbus_controller_7
    name: Ventitaltion Bypass
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: genvex_hum
  component_id: sensor.modbus_controller
  fields:
    device_class: humidity
    unit_of_measurement: '%'
    register_type: read
    address: 13
    value_type: U_WORD
    filters:
      value:
      - filter_out: 0
      - heartbeat: 120s
      locked: true
    id: genvex_hum
    name: Ventitaltion Humidity
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: genvex_mode
  component_id: sensor.modbus_controller
  fields:
    icon: mdi:speedometer-slow
    register_type: holding
    entity_category: diagnostic
    address: 0
    value_type: U_WORD
    disabled_by_default: true
    bitmask: 2147483647
    id: genvex_mode
    name: Ventitaltion Mode (modbus)
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: sensor_modbus_controller_10
  component_id: sensor.modbus_controller
  fields:
    icon: mdi:alert-circle-outline
    register_type: read
    entity_category: diagnostic
    address: 15
    value_type: U_WORD
    disabled_by_default: true
    bitmask: 2147483647
    id: sensor_modbus_controller_10
    name: Ventitaltion Alarm code (DEC)
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: sensor_modbus_controller_11
  component_id: sensor.modbus_controller
  fields:
    icon: mdi:water-boiler
    register_type: read
    unit_of_measurement: '%'
    address: 5
    value_type: U_WORD
    bitmask: 2147483647
    id: sensor_modbus_controller_11
    name: Ventitaltion Reheating
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: sensor_modbus_controller_12
  component_id: sensor.modbus_controller
  fields:
    icon: mdi:water-boiler
    register_type: read
    unit_of_measurement: '%'
    address: 12
    value_type: U_WORD
    bitmask: 2147483647
    id: sensor_modbus_controller_12
    name: Ventitaltion Reheating control
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: switch_modbus_controller_1
  component_id: switch.modbus_controller
  fields:
    entity_category: config
    icon: mdi:water-boiler
    register_type: holding
    address: 1
    bitmask: 1
    id: switch_modbus_controller_1
    name: Ventitaltion Reheating
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: switch_modbus_controller_2
  component_id: switch.modbus_controller
  fields:
    entity_category: config
    icon: mdi:toggle-switch
    register_type: holding
    address: 4
    bitmask: 1
    id: switch_modbus_controller_2
    name: Ventitaltion Max duration for level 3-4 enable
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: switch_modbus_controller_3
  component_id: switch.modbus_controller
  fields:
    entity_category: config
    icon: mdi:air-humidifier
    register_type: holding
    address: 6
    bitmask: 1
    id: switch_modbus_controller_3
    name: Ventitaltion Humidity control
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: switch_modbus_controller_4
  component_id: switch.modbus_controller
  fields:
    entity_category: config
    icon: mdi:toggle-switch
    disabled_by_default: true
    register_type: holding
    address: 15
    bitmask: 1
    id: switch_modbus_controller_4
    name: Ventitaltion Filter change autostop
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: switch_modbus_controller_5
  component_id: switch.modbus_controller
  fields:
    entity_category: config
    icon: mdi:toggle-switch
    disabled_by_default: true
    register_type: holding
    address: 25
    bitmask: 1
    id: switch_modbus_controller_5
    name: Ventitaltion Device stop enable
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: switch_modbus_controller_6
  component_id: switch.modbus_controller
  fields:
    entity_category: config
    icon: mdi:toggle-switch
    disabled_by_default: true
    register_type: holding
    address: 45
    bitmask: 1
    id: switch_modbus_controller_6
    name: Ventitaltion Calendar mode
  requires:
  - modbus1
  - mbus
  - genvex_modbus
- id: switch_modbus_controller_7
  component_id: switch.modbus_controller
  fields:
    entity_category: config
    icon: mdi:air-filter
    register_type: holding
    address: 47
    bitmask: 1
    id: switch_modbus_controller_7
    name: Ventitaltion Filter reset
  requires:
  - modbus1
  - mbus
  - genvex_modbus
source:
  type: esphome-devices
  remote_id: Genvex-Nibe-AlphaInnotec-heat-recovery-ventilation
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Genvex-Nibe-AlphaInnotec-heat-recovery-ventilation/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 182316d4b3fa783217495e74f5d22020ce3625b89090fe2b8205f403857d99a0
