id: kincony_kc868_m16
name: KinCony KC868-M16
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32dev
  variant: esp32
  framework: arduino
hardware:
  connectivity:
  - wifi
  - bluetooth
  - ethernet
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KinCony-KC868-M16/kc868-m16.jpg
pins:
- gpio: 13
  available: false
  occupied_by: cd74hc4067_1
- gpio: 16
  available: false
  occupied_by: cd74hc4067_1
- gpio: 17
  available: false
  occupied_by: Ethernet CLK
- gpio: 18
  available: false
  occupied_by: Ethernet MDIO
- gpio: 23
  available: false
  occupied_by: Ethernet MDC
- gpio: 32
  available: false
  occupied_by: cd74hc4067_1
- gpio: 33
  available: false
  occupied_by: cd74hc4067_1
- gpio: 34
  available: false
  occupied_by: m16--AI-2
- gpio: 35
  available: false
  occupied_by: adc35
- gpio: 36
  available: false
  occupied_by: m16--AI-1
- gpio: 39
  available: false
  occupied_by: m16--AI-3
docs_url: https://devices.esphome.io/devices/KinCony-KC868-M16/
featured_components:
- id: cd74hc4067_1
  component_id: cd74hc4067
  fields:
    pin_s0:
      value: 32
      locked: true
    pin_s1:
      value: 33
      locked: true
    pin_s2:
      value: 13
      locked: true
    pin_s3:
      value: 16
      locked: true
    id:
      value: cd74hc4067_1
      locked: true
- id: onboard_ethernet
  component_id: ethernet
  name: Onboard Ethernet
  fields:
    type:
      value: LAN8720
      locked: true
    mdc_pin:
      value: GPIO23
      locked: true
    mdio_pin:
      value: GPIO18
      locked: true
    phy_addr:
      value: 0
      locked: true
    clk:
      value:
        pin: GPIO17
        mode: CLK_OUT
      locked: true
- id: adc35
  component_id: sensor.adc
  fields:
    pin:
      value: 35
      locked: true
    update_interval: never
    attenuation: 12db
    id: adc35
    name: adc35
- id: adc36
  component_id: sensor.adc
  fields:
    pin:
      value: 36
      locked: true
    update_interval: 15s
    attenuation: 12db
    id: adc36
    name: m16--AI-1
- id: adc34
  component_id: sensor.adc
  fields:
    pin:
      value: 34
      locked: true
    update_interval: 15s
    attenuation: 12db
    id: adc34
    name: m16--AI-2
- id: adc39
  component_id: sensor.adc
  fields:
    pin:
      value: 39
      locked: true
    update_interval: 15s
    attenuation: 12db
    id: adc39
    name: m16--AI-3
- id: ai1
  component_id: sensor.cd74hc4067
  fields:
    number: 0
    update_interval: 5s
    sensor: adc35
    id: ai1
    name: ai1
  requires:
  - cd74hc4067_1
- id: ai2
  component_id: sensor.cd74hc4067
  fields:
    number: 1
    update_interval: 5s
    sensor: adc35
    id: ai2
    name: ai2
  requires:
  - cd74hc4067_1
- id: ai3
  component_id: sensor.cd74hc4067
  fields:
    number: 2
    update_interval: 5s
    sensor: adc35
    id: ai3
    name: ai3
  requires:
  - cd74hc4067_1
- id: ai4
  component_id: sensor.cd74hc4067
  fields:
    number: 3
    update_interval: 5s
    sensor: adc35
    id: ai4
    name: ai4
  requires:
  - cd74hc4067_1
- id: ai5
  component_id: sensor.cd74hc4067
  fields:
    number: 4
    update_interval: 5s
    sensor: adc35
    id: ai5
    name: ai5
  requires:
  - cd74hc4067_1
- id: ai6
  component_id: sensor.cd74hc4067
  fields:
    number: 5
    update_interval: 5s
    sensor: adc35
    id: ai6
    name: ai6
  requires:
  - cd74hc4067_1
- id: ai7
  component_id: sensor.cd74hc4067
  fields:
    number: 6
    update_interval: 5s
    sensor: adc35
    id: ai7
    name: ai7
  requires:
  - cd74hc4067_1
- id: ai8
  component_id: sensor.cd74hc4067
  fields:
    number: 7
    update_interval: 5s
    sensor: adc35
    id: ai8
    name: ai8
  requires:
  - cd74hc4067_1
- id: ai9
  component_id: sensor.cd74hc4067
  fields:
    number: 8
    update_interval: 5s
    sensor: adc35
    id: ai9
    name: ai9
  requires:
  - cd74hc4067_1
- id: ai10
  component_id: sensor.cd74hc4067
  fields:
    number: 9
    update_interval: 5s
    sensor: adc35
    id: ai10
    name: ai10
  requires:
  - cd74hc4067_1
- id: ai11
  component_id: sensor.cd74hc4067
  fields:
    number: 10
    update_interval: 5s
    sensor: adc35
    id: ai11
    name: ai11
  requires:
  - cd74hc4067_1
- id: ai12
  component_id: sensor.cd74hc4067
  fields:
    number: 11
    update_interval: 5s
    sensor: adc35
    id: ai12
    name: ai12
  requires:
  - cd74hc4067_1
- id: ai13
  component_id: sensor.cd74hc4067
  fields:
    number: 12
    update_interval: 5s
    sensor: adc35
    id: ai13
    name: ai13
  requires:
  - cd74hc4067_1
- id: ai14
  component_id: sensor.cd74hc4067
  fields:
    number: 13
    update_interval: 5s
    sensor: adc35
    id: ai14
    name: ai14
  requires:
  - cd74hc4067_1
- id: ai15
  component_id: sensor.cd74hc4067
  fields:
    number: 14
    update_interval: 5s
    sensor: adc35
    id: ai15
    name: ai15
  requires:
  - cd74hc4067_1
- id: ai16
  component_id: sensor.cd74hc4067
  fields:
    number: 15
    update_interval: 5s
    sensor: adc35
    id: ai16
    name: ai16
  requires:
  - cd74hc4067_1
- id: sensor_ct_clamp_1
  component_id: sensor.ct_clamp
  fields:
    update_interval: 5s
    filters:
      value:
      - calibrate_linear:
        - 0 -> 0
        - 0.31749 -> 8.95608
      locked: true
    sensor: ai1
    id: sensor_ct_clamp_1
    name: Measured Current-1
- id: sensor_ct_clamp_2
  component_id: sensor.ct_clamp
  fields:
    update_interval: 5s
    filters:
      value:
      - calibrate_linear:
        - 0 -> 0
        - 0.31749 -> 8.95608
      locked: true
    sensor: ai2
    id: sensor_ct_clamp_2
    name: Measured Current-2
- id: sensor_ct_clamp_3
  component_id: sensor.ct_clamp
  fields:
    update_interval: 5s
    filters:
      value:
      - calibrate_linear:
        - 0 -> 0
        - 0.31749 -> 8.95608
      locked: true
    sensor: ai3
    id: sensor_ct_clamp_3
    name: Measured Current-3
- id: sensor_ct_clamp_4
  component_id: sensor.ct_clamp
  fields:
    update_interval: 5s
    filters:
      value:
      - calibrate_linear:
        - 0 -> 0
        - 0.31749 -> 8.95608
      locked: true
    sensor: ai4
    id: sensor_ct_clamp_4
    name: Measured Current-4
- id: sensor_ct_clamp_5
  component_id: sensor.ct_clamp
  fields:
    update_interval: 5s
    filters:
      value:
      - calibrate_linear:
        - 0 -> 0
        - 0.31749 -> 8.95608
      locked: true
    sensor: ai5
    id: sensor_ct_clamp_5
    name: Measured Current-5
- id: sensor_ct_clamp_6
  component_id: sensor.ct_clamp
  fields:
    update_interval: 5s
    filters:
      value:
      - calibrate_linear:
        - 0 -> 0
        - 0.31749 -> 8.95608
      locked: true
    sensor: ai6
    id: sensor_ct_clamp_6
    name: Measured Current-6
- id: sensor_ct_clamp_7
  component_id: sensor.ct_clamp
  fields:
    update_interval: 5s
    filters:
      value:
      - calibrate_linear:
        - 0 -> 0
        - 0.31749 -> 8.95608
      locked: true
    sensor: ai7
    id: sensor_ct_clamp_7
    name: Measured Current-7
- id: sensor_ct_clamp_8
  component_id: sensor.ct_clamp
  fields:
    update_interval: 5s
    filters:
      value:
      - calibrate_linear:
        - 0 -> 0
        - 0.31749 -> 8.95608
      locked: true
    sensor: ai8
    id: sensor_ct_clamp_8
    name: Measured Current-8
- id: sensor_ct_clamp_9
  component_id: sensor.ct_clamp
  fields:
    update_interval: 5s
    filters:
      value:
      - calibrate_linear:
        - 0 -> 0
        - 0.31749 -> 8.95608
      locked: true
    sensor: ai9
    id: sensor_ct_clamp_9
    name: Measured Current-9
- id: sensor_ct_clamp_10
  component_id: sensor.ct_clamp
  fields:
    update_interval: 5s
    filters:
      value:
      - calibrate_linear:
        - 0 -> 0
        - 0.31749 -> 8.95608
      locked: true
    sensor: ai10
    id: sensor_ct_clamp_10
    name: Measured Current-10
- id: sensor_ct_clamp_11
  component_id: sensor.ct_clamp
  fields:
    update_interval: 5s
    filters:
      value:
      - calibrate_linear:
        - 0 -> 0
        - 0.31749 -> 8.95608
      locked: true
    sensor: ai11
    id: sensor_ct_clamp_11
    name: Measured Current-11
- id: sensor_ct_clamp_12
  component_id: sensor.ct_clamp
  fields:
    update_interval: 5s
    filters:
      value:
      - calibrate_linear:
        - 0 -> 0
        - 0.31749 -> 8.95608
      locked: true
    sensor: ai12
    id: sensor_ct_clamp_12
    name: Measured Current-12
- id: sensor_ct_clamp_13
  component_id: sensor.ct_clamp
  fields:
    update_interval: 5s
    filters:
      value:
      - calibrate_linear:
        - 0 -> 0
        - 0.31749 -> 8.95608
      locked: true
    sensor: ai13
    id: sensor_ct_clamp_13
    name: Measured Current-13
- id: sensor_ct_clamp_14
  component_id: sensor.ct_clamp
  fields:
    update_interval: 5s
    filters:
      value:
      - calibrate_linear:
        - 0 -> 0
        - 0.31749 -> 8.95608
      locked: true
    sensor: ai14
    id: sensor_ct_clamp_14
    name: Measured Current-14
- id: sensor_ct_clamp_15
  component_id: sensor.ct_clamp
  fields:
    update_interval: 5s
    filters:
      value:
      - calibrate_linear:
        - 0 -> 0
        - 0.31749 -> 8.95608
      locked: true
    sensor: ai15
    id: sensor_ct_clamp_15
    name: Measured Current-15
- id: sensor_ct_clamp_16
  component_id: sensor.ct_clamp
  fields:
    update_interval: 5s
    filters:
      value:
      - calibrate_linear:
        - 0 -> 0
        - 0.31749 -> 8.95608
      locked: true
    sensor: ai16
    id: sensor_ct_clamp_16
    name: Measured Current-16
featured_bundles:
- id: ai1_setup
  name: ai1 (full setup)
  component_ids:
  - cd74hc4067_1
  - adc35
  - ai1
- id: ai2_setup
  name: ai2 (full setup)
  component_ids:
  - cd74hc4067_1
  - adc35
  - ai2
- id: ai3_setup
  name: ai3 (full setup)
  component_ids:
  - cd74hc4067_1
  - adc35
  - ai3
- id: ai4_setup
  name: ai4 (full setup)
  component_ids:
  - cd74hc4067_1
  - adc35
  - ai4
- id: ai5_setup
  name: ai5 (full setup)
  component_ids:
  - cd74hc4067_1
  - adc35
  - ai5
- id: ai6_setup
  name: ai6 (full setup)
  component_ids:
  - cd74hc4067_1
  - adc35
  - ai6
- id: ai7_setup
  name: ai7 (full setup)
  component_ids:
  - cd74hc4067_1
  - adc35
  - ai7
- id: ai8_setup
  name: ai8 (full setup)
  component_ids:
  - cd74hc4067_1
  - adc35
  - ai8
- id: ai9_setup
  name: ai9 (full setup)
  component_ids:
  - cd74hc4067_1
  - adc35
  - ai9
- id: ai10_setup
  name: ai10 (full setup)
  component_ids:
  - cd74hc4067_1
  - adc35
  - ai10
- id: ai11_setup
  name: ai11 (full setup)
  component_ids:
  - cd74hc4067_1
  - adc35
  - ai11
- id: ai12_setup
  name: ai12 (full setup)
  component_ids:
  - cd74hc4067_1
  - adc35
  - ai12
- id: ai13_setup
  name: ai13 (full setup)
  component_ids:
  - cd74hc4067_1
  - adc35
  - ai13
- id: ai14_setup
  name: ai14 (full setup)
  component_ids:
  - cd74hc4067_1
  - adc35
  - ai14
- id: ai15_setup
  name: ai15 (full setup)
  component_ids:
  - cd74hc4067_1
  - adc35
  - ai15
- id: ai16_setup
  name: ai16 (full setup)
  component_ids:
  - cd74hc4067_1
  - adc35
  - ai16
- id: sensor_ct_clamp_1_setup
  name: Measured Current-1 (full setup)
  component_ids:
  - cd74hc4067_1
  - ai1
  - sensor_ct_clamp_1
- id: sensor_ct_clamp_2_setup
  name: Measured Current-2 (full setup)
  component_ids:
  - cd74hc4067_1
  - ai2
  - sensor_ct_clamp_2
- id: sensor_ct_clamp_3_setup
  name: Measured Current-3 (full setup)
  component_ids:
  - cd74hc4067_1
  - ai3
  - sensor_ct_clamp_3
- id: sensor_ct_clamp_4_setup
  name: Measured Current-4 (full setup)
  component_ids:
  - cd74hc4067_1
  - ai4
  - sensor_ct_clamp_4
- id: sensor_ct_clamp_5_setup
  name: Measured Current-5 (full setup)
  component_ids:
  - cd74hc4067_1
  - ai5
  - sensor_ct_clamp_5
- id: sensor_ct_clamp_6_setup
  name: Measured Current-6 (full setup)
  component_ids:
  - cd74hc4067_1
  - ai6
  - sensor_ct_clamp_6
- id: sensor_ct_clamp_7_setup
  name: Measured Current-7 (full setup)
  component_ids:
  - cd74hc4067_1
  - ai7
  - sensor_ct_clamp_7
- id: sensor_ct_clamp_8_setup
  name: Measured Current-8 (full setup)
  component_ids:
  - cd74hc4067_1
  - ai8
  - sensor_ct_clamp_8
- id: sensor_ct_clamp_9_setup
  name: Measured Current-9 (full setup)
  component_ids:
  - cd74hc4067_1
  - ai9
  - sensor_ct_clamp_9
- id: sensor_ct_clamp_10_setup
  name: Measured Current-10 (full setup)
  component_ids:
  - cd74hc4067_1
  - ai10
  - sensor_ct_clamp_10
- id: sensor_ct_clamp_11_setup
  name: Measured Current-11 (full setup)
  component_ids:
  - cd74hc4067_1
  - ai11
  - sensor_ct_clamp_11
- id: sensor_ct_clamp_12_setup
  name: Measured Current-12 (full setup)
  component_ids:
  - cd74hc4067_1
  - ai12
  - sensor_ct_clamp_12
- id: sensor_ct_clamp_13_setup
  name: Measured Current-13 (full setup)
  component_ids:
  - cd74hc4067_1
  - ai13
  - sensor_ct_clamp_13
- id: sensor_ct_clamp_14_setup
  name: Measured Current-14 (full setup)
  component_ids:
  - cd74hc4067_1
  - ai14
  - sensor_ct_clamp_14
- id: sensor_ct_clamp_15_setup
  name: Measured Current-15 (full setup)
  component_ids:
  - cd74hc4067_1
  - ai15
  - sensor_ct_clamp_15
- id: sensor_ct_clamp_16_setup
  name: Measured Current-16 (full setup)
  component_ids:
  - cd74hc4067_1
  - ai16
  - sensor_ct_clamp_16
source:
  type: esphome-devices
  remote_id: KinCony-KC868-M16
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/KinCony-KC868-M16/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: e8d197b4befb24767b1598ed60bfadb7f90b0bc43627cba87ff25443349f887e
