id: shelly_1_gen4
name: Shelly 1 Gen4
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32-c6-devkitm-1
  variant: esp32c6
  framework: esp-idf
  logger_hardware_uart: USB_SERIAL_JTAG
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Shelly-1-Gen4/shelly-1-gen4.webp
tags:
- relay
- shelly
pins:
- gpio: 4
  available: false
  occupied_by: Device Button
- gpio: 5
  available: false
  occupied_by: Relay
- gpio: 10
  available: false
  occupied_by: Switch Input
docs_url: https://devices.esphome.io/devices/Shelly-1-Gen4/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 10
      locked: true
    filters:
      value:
      - delayed_on_off: 50ms
      locked: true
    id: binary_sensor_gpio_1
    name: Switch Input
- id: binary_sensor_gpio_2
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 4
        inverted: true
        mode: INPUT_PULLUP
      locked: true
    id: binary_sensor_gpio_2
    name: Device Button
- id: relay_1
  component_id: switch.gpio
  fields:
    pin:
      value: 5
      locked: true
    restore_mode: RESTORE_DEFAULT_OFF
    id: relay_1
    name: Relay
source:
  type: esphome-devices
  remote_id: Shelly-1-Gen4
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Shelly-1-Gen4/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: e7f4417539cea5a0718fceb2f392f4d0b9efee69ea4eff22d9d4529b85a1cedd
