id: zentec_smart_plug
name: Zentec Smart Plug
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Zentec-Smart-Plug/zentec-outside.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Zentec-Smart-Plug/zentec-inside.jpg
tags:
- relay
- compact
pins:
- gpio: 4
  available: false
  occupied_by: redLED
- gpio: 12
  available: false
  occupied_by: Zentec Plug
- gpio: 13
  available: false
  occupied_by: Zentec Plug Button
docs_url: https://devices.esphome.io/devices/Zentec-Smart-Plug/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 13
        inverted: true
      locked: true
    internal: false
    id: binary_sensor_gpio_1
    name: Zentec Plug Button
- id: relay
  component_id: switch.gpio
  fields:
    pin:
      value: 12
      locked: true
    restore_mode: ALWAYS_OFF
    id: relay
    name: Zentec Plug
- id: redled
  component_id: switch.gpio
  fields:
    pin:
      value: 4
      locked: true
    inverted:
      value: true
      locked: true
    restore_mode: ALWAYS_ON
    internal: true
    id: redled
    name: redLED
source:
  type: esphome-devices
  remote_id: Zentec-Smart-Plug
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Zentec-Smart-Plug/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: de90081da126f6880b34509a8985aff7fca3326175a09c5bccba96312de780d9
