id: awp02l2
name: Avatar AWP02L2
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/AWP02L2/AWP02L2.jpg
tags:
- relay
- compact
pins:
- gpio: 2
  available: false
  occupied_by: led
- gpio: 13
  available: false
  occupied_by: Avatar AWP02L2 Button
- gpio: 15
  available: false
  occupied_by: Avatar AWP02L2 Relay
docs_url: https://devices.esphome.io/devices/AWP02L2/
featured_components:
- id: avatar_awp02l2_button
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 13
        mode: INPUT_PULLUP
        inverted: true
      locked: true
    id: avatar_awp02l2_button
    name: Avatar AWP02L2 Button
- id: led
  component_id: output.gpio
  fields:
    pin:
      value: 2
      locked: true
    inverted:
      value: true
      locked: true
    id: led
- id: avatar_awp02l2_wifi_signal
  component_id: sensor.wifi_signal
  fields:
    update_interval: 60s
    id: avatar_awp02l2_wifi_signal
    name: Avatar AWP02L2 WiFi signal
- id: avatar_awp02l2_uptime
  component_id: sensor.uptime
  fields:
    update_interval: 60s
    id: avatar_awp02l2_uptime
    name: Avatar AWP02L2 Uptime
- id: avatar_awp02l2_relay
  component_id: switch.gpio
  fields:
    pin:
      value: 15
      locked: true
    id: avatar_awp02l2_relay
    name: Avatar AWP02L2 Relay
source:
  type: esphome-devices
  remote_id: AWP02L2
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/AWP02L2/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: ce44524e79727437c948ccacd31dfb0c28e587ee538dbac7c820f455c18f0f02
