id: blitzwolf_bw_shp9
name: Blitzwolf BW-SHP9 Triple powerstrip with dual USB power
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp8285
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/BlitzWolf-BW-SHP9/BlitzWolf-BW-SHP9-Power-strip.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/BlitzWolf-BW-SHP9/BlitzWolf-BW-SHP9-Power-strip-measurement.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/BlitzWolf-BW-SHP9/BlitzWolf-BW-SHP9-Power-strip-outside.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/BlitzWolf-BW-SHP9/BlitzWolf-BW-SHP9-Power-strip-inside.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/BlitzWolf-BW-SHP9/BlitzWolf-BW-SHP9-Power-strip-connector.jpg
tags:
- relay
- compact
pins:
- gpio: 5
  available: false
  occupied_by: livingroomextension-socket3
- gpio: 12
  available: false
  occupied_by: light_relay
- gpio: 13
  available: false
  occupied_by: button
- gpio: 14
  available: false
  occupied_by: livingroomextension-socket2
- gpio: 15
  available: false
  occupied_by: livingroomextension-usb-socket
docs_url: https://devices.esphome.io/devices/BlitzWolf-BW-SHP9/
featured_components:
- id: button
  component_id: binary_sensor.gpio
  fields:
    internal: true
    pin:
      value:
        number: 13
        mode: INPUT_PULLUP
        inverted: true
      locked: true
    id: button
    name: button
- id: relay1
  component_id: light.binary
  fields:
    output: light_relay
    id: relay1
    name: Floorlamp
- id: light_relay
  component_id: output.gpio
  fields:
    pin:
      value: 12
      locked: true
    id: light_relay
- id: relay2
  component_id: switch.gpio
  fields:
    pin:
      value: 14
      locked: true
    id: relay2
    name: livingroomextension-socket2
- id: relay3
  component_id: switch.gpio
  fields:
    pin:
      value: 5
      locked: true
    id: relay3
    name: livingroomextension-socket3
- id: relay4
  component_id: switch.gpio
  fields:
    pin:
      value: 15
      locked: true
    id: relay4
    name: livingroomextension-usb-socket
featured_bundles:
- id: relay1_setup
  name: Floorlamp (full setup)
  component_ids:
  - light_relay
  - relay1
source:
  type: esphome-devices
  remote_id: BlitzWolf-BW-SHP9
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/BlitzWolf-BW-SHP9/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 8b08a3f800eee1b6c9c14bf7dd6afa9504391c6bcfa4aade0ba1162add6a5df8
