id: kincony_kc868_a8v3
name: KinCony KC868-A8v3 (ESP32-S3 Relay)
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework: arduino
hardware:
  connectivity:
  - wifi
  - bluetooth
  - ethernet
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KinCony-KC868-A8v3/A8v3-3.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KinCony-KC868-A8v3/A8v3_diagram-1.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KinCony-KC868-A8v3/A8v3_diagram-2.jpg
tags:
- relay
pins:
- gpio: 0
  available: false
  occupied_by: a8v3-0
- gpio: 1
  available: false
  occupied_by: Ethernet CLK
- gpio: 2
  available: false
  occupied_by: Ethernet MOSI
- gpio: 5
  available: false
  occupied_by: a8v3-5
- gpio: 6
  available: false
  occupied_by: A8v3 A2 Voltage
- gpio: 7
  available: false
  occupied_by: A8v3 A1 Voltage
- gpio: 8
  available: false
  occupied_by: bus_a
- gpio: 13
  available: false
  occupied_by: a8v3-W1-io13
- gpio: 14
  available: false
  occupied_by: a8v3-W1-io14
- gpio: 18
  available: false
  occupied_by: bus_a
- gpio: 38
  available: false
  occupied_by: uart_1
- gpio: 39
  available: false
  occupied_by: uart_1
- gpio: 40
  available: false
  occupied_by: a8v3-W1-io40
- gpio: 41
  available: false
  occupied_by: Ethernet MISO
- gpio: 42
  available: false
  occupied_by: Ethernet CS
- gpio: 43
  available: false
  occupied_by: Ethernet INT
- gpio: 44
  available: false
  occupied_by: Ethernet RESET
- gpio: 48
  available: false
  occupied_by: a8v3-W1-io48
docs_url: https://devices.esphome.io/devices/KinCony-KC868-A8v3/
featured_components:
- id: uart_1
  component_id: uart
  fields:
    baud_rate: 9600
    debug:
      value:
        direction: BOTH
        dummy_receiver: true
        after:
          timeout: 10ms
      locked: true
    tx_pin:
      value: 39
      locked: true
    rx_pin:
      value: 38
      locked: true
    id:
      value: uart_1
      locked: true
- id: bus_a
  component_id: i2c
  fields:
    sda:
      value: 8
      locked: true
    scl:
      value: 18
      locked: true
    scan: true
    frequency: 400kHz
    id:
      value: bus_a
      locked: true
- id: pcf8574_hub_out_1
  component_id: pcf8574
  fields:
    address: 34
    pcf8575: true
    id:
      value: pcf8574_hub_out_1
      locked: true
    i2c_id:
      value: bus_a
      locked: true
  requires:
  - bus_a
- id: onboard_ethernet
  component_id: ethernet
  name: Onboard Ethernet
  fields:
    type:
      value: W5500
      locked: true
    clk_pin:
      value: GPIO1
      locked: true
    mosi_pin:
      value: GPIO2
      locked: true
    miso_pin:
      value: GPIO41
      locked: true
    cs_pin:
      value: GPIO42
      locked: true
    interrupt_pin:
      value: GPIO43
      locked: true
    reset_pin:
      value: GPIO44
      locked: true
- id: a8v3_input01
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 8
        mode: INPUT
        inverted: true
      locked: true
    id: a8v3_input01
    name: a8v3-input01
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: a8v3_input02
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 9
        mode: INPUT
        inverted: true
      locked: true
    id: a8v3_input02
    name: a8v3-input02
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: a8v3_input03
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 10
        mode: INPUT
        inverted: true
      locked: true
    id: a8v3_input03
    name: a8v3-input03
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: a8v3_input04
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 11
        mode: INPUT
        inverted: true
      locked: true
    id: a8v3_input04
    name: a8v3-input04
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: a8v3_input05
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 12
        mode: INPUT
        inverted: true
      locked: true
    id: a8v3_input05
    name: a8v3-input05
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: a8v3_input06
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 13
        mode: INPUT
        inverted: true
      locked: true
    id: a8v3_input06
    name: a8v3-input06
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: a8v3_input07
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 14
        mode: INPUT
        inverted: true
      locked: true
    id: a8v3_input07
    name: a8v3-input07
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: a8v3_input08
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 15
        mode: INPUT
        inverted: true
      locked: true
    id: a8v3_input08
    name: a8v3-input08
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: binary_sensor_gpio_9
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 13
        inverted: true
      locked: true
    id: binary_sensor_gpio_9
    name: a8v3-W1-io13
- id: binary_sensor_gpio_10
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 40
        inverted: true
      locked: true
    id: binary_sensor_gpio_10
    name: a8v3-W1-io40
- id: binary_sensor_gpio_11
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 14
        inverted: true
      locked: true
    id: binary_sensor_gpio_11
    name: a8v3-W1-io14
- id: binary_sensor_gpio_12
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 48
        inverted: true
      locked: true
    id: binary_sensor_gpio_12
    name: a8v3-W1-io48
- id: binary_sensor_gpio_13
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 5
        inverted: false
      locked: true
    id: binary_sensor_gpio_13
    name: a8v3-5
- id: binary_sensor_gpio_14
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 0
        inverted: false
      locked: true
    id: binary_sensor_gpio_14
    name: a8v3-0
- id: sensor_adc_1
  component_id: sensor.adc
  fields:
    pin:
      value: 7
      locked: true
    update_interval: 5s
    attenuation: 11db
    id: sensor_adc_1
    name: A8v3 A1 Voltage
- id: sensor_adc_2
  component_id: sensor.adc
  fields:
    pin:
      value: 6
      locked: true
    update_interval: 5s
    attenuation: 11db
    id: sensor_adc_2
    name: A8v3 A2 Voltage
- id: switch_uart_1
  component_id: switch.uart
  fields:
    data:
      value:
      - 17
      - 34
      - 51
      - 68
      - 85
      locked: true
    id: switch_uart_1
    name: RS485 Button
    uart_id:
      value: uart_1
      locked: true
  requires:
  - uart_1
- id: a8v3_output01
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 0
        mode: OUTPUT
        inverted: true
      locked: true
    id: a8v3_output01
    name: a8v3-output01
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: a8v3_output02
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 1
        mode: OUTPUT
        inverted: true
      locked: true
    id: a8v3_output02
    name: a8v3-output02
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: a8v3_output03
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 2
        mode: OUTPUT
        inverted: true
      locked: true
    id: a8v3_output03
    name: a8v3-output03
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: a8v3_output04
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 3
        mode: OUTPUT
        inverted: true
      locked: true
    id: a8v3_output04
    name: a8v3-output04
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: a8v3_output05
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 4
        mode: OUTPUT
        inverted: true
      locked: true
    id: a8v3_output05
    name: a8v3-output05
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: a8v3_output06
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 5
        mode: OUTPUT
        inverted: true
      locked: true
    id: a8v3_output06
    name: a8v3-output06
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: a8v3_output07
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 6
        mode: OUTPUT
        inverted: true
      locked: true
    id: a8v3_output07
    name: a8v3-output07
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: a8v3_output08
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 7
        mode: OUTPUT
        inverted: true
      locked: true
    id: a8v3_output08
    name: a8v3-output08
  requires:
  - bus_a
  - pcf8574_hub_out_1
source:
  type: esphome-devices
  remote_id: KinCony-KC868-A8v3
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/KinCony-KC868-A8v3/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: fe0efa7c32a9aacdc1e6a3d55923208f9aeade25682398b367ab3f534a894682
