id: kincony_e16p
name: KinCony E16P POE Ethernet Removable Relay Module
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32dev
  variant: esp32
hardware:
  connectivity:
  - wifi
  - bluetooth
  - ethernet
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KinCony-E16P/E16P-1_07.jpg
tags:
- relay
pins:
- gpio: 15
  available: false
  occupied_by: bus_a
- gpio: 16
  available: false
  occupied_by: bus_a
- gpio: 17
  available: false
  occupied_by: Ethernet CLK
- gpio: 18
  available: false
  occupied_by: Ethernet MDIO
- gpio: 23
  available: false
  occupied_by: Ethernet MDC
docs_url: https://devices.esphome.io/devices/KinCony-E16P/
featured_components:
- id: bus_a
  component_id: i2c
  fields:
    sda:
      value: 16
      locked: true
    scl:
      value: 15
      locked: true
    scan: true
    id:
      value: bus_a
      locked: true
- id: pcf8574_hub_in_1
  component_id: pcf8574
  fields:
    address: 34
    id:
      value: pcf8574_hub_in_1
      locked: true
  requires:
  - bus_a
- id: pcf8574_hub_in_2
  component_id: pcf8574
  fields:
    address: 36
    id:
      value: pcf8574_hub_in_2
      locked: true
  requires:
  - bus_a
- id: pcf8574_hub_out_1
  component_id: pcf8574
  fields:
    address: 33
    id:
      value: pcf8574_hub_out_1
      locked: true
  requires:
  - bus_a
- id: pcf8574_hub_out_2
  component_id: pcf8574
  fields:
    address: 37
    id:
      value: pcf8574_hub_out_2
      locked: true
  requires:
  - bus_a
- id: onboard_ethernet
  component_id: ethernet
  name: Onboard Ethernet
  fields:
    type:
      value: LAN8720
      locked: true
    mdc_pin:
      value: GPIO23
      locked: true
    mdio_pin:
      value: GPIO18
      locked: true
    phy_addr:
      value: 0
      locked: true
    clk:
      value:
        pin: GPIO17
        mode: CLK_OUT
      locked: true
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 0
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_1
    name: e16t-input1
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_2
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 1
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_2
    name: e16t-input2
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_3
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 2
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_3
    name: e16t-input3
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_4
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 3
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_4
    name: e16t-input4
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_5
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 4
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_5
    name: e16t-input5
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_6
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 5
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_6
    name: e16t-input6
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_7
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 6
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_7
    name: e16t-input7
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_8
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_1
        number: 7
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_8
    name: e16t-input8
  requires:
  - bus_a
  - pcf8574_hub_in_1
- id: binary_sensor_gpio_9
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 0
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_9
    name: e16t-input9
  requires:
  - bus_a
  - pcf8574_hub_in_2
- id: binary_sensor_gpio_10
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 1
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_10
    name: e16t-input10
  requires:
  - bus_a
  - pcf8574_hub_in_2
- id: binary_sensor_gpio_11
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 2
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_11
    name: e16t-input11
  requires:
  - bus_a
  - pcf8574_hub_in_2
- id: binary_sensor_gpio_12
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 3
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_12
    name: e16t-input12
  requires:
  - bus_a
  - pcf8574_hub_in_2
- id: binary_sensor_gpio_13
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 4
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_13
    name: e16t-input13
  requires:
  - bus_a
  - pcf8574_hub_in_2
- id: binary_sensor_gpio_14
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 5
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_14
    name: e16t-input14
  requires:
  - bus_a
  - pcf8574_hub_in_2
- id: binary_sensor_gpio_15
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 6
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_15
    name: e16t-input15
  requires:
  - bus_a
  - pcf8574_hub_in_2
- id: binary_sensor_gpio_16
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_in_2
        number: 7
        mode: INPUT
        inverted: true
      locked: true
    id: binary_sensor_gpio_16
    name: e16t-input16
  requires:
  - bus_a
  - pcf8574_hub_in_2
- id: switch_gpio_1
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 0
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_1
    name: e16t-output1
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: switch_gpio_2
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 1
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_2
    name: e16t-output2
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: switch_gpio_3
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 2
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_3
    name: e16t-output3
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: switch_gpio_4
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 3
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_4
    name: e16t-output4
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: switch_gpio_5
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 4
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_5
    name: e16t-output5
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: switch_gpio_6
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 5
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_6
    name: e16t-output6
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: switch_gpio_7
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 6
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_7
    name: e16t-output7
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: switch_gpio_8
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_1
        number: 7
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_8
    name: e16t-output8
  requires:
  - bus_a
  - pcf8574_hub_out_1
- id: switch_gpio_9
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_2
        number: 0
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_9
    name: e16t-output9
  requires:
  - bus_a
  - pcf8574_hub_out_2
- id: switch_gpio_10
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_2
        number: 1
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_10
    name: e16t-output10
  requires:
  - bus_a
  - pcf8574_hub_out_2
- id: switch_gpio_11
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_2
        number: 2
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_11
    name: e16t-output11
  requires:
  - bus_a
  - pcf8574_hub_out_2
- id: switch_gpio_12
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_2
        number: 3
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_12
    name: e16t-output12
  requires:
  - bus_a
  - pcf8574_hub_out_2
- id: switch_gpio_13
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_2
        number: 4
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_13
    name: e16t-output13
  requires:
  - bus_a
  - pcf8574_hub_out_2
- id: switch_gpio_14
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_2
        number: 5
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_14
    name: e16t-output14
  requires:
  - bus_a
  - pcf8574_hub_out_2
- id: switch_gpio_15
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_2
        number: 6
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_15
    name: e16t-output15
  requires:
  - bus_a
  - pcf8574_hub_out_2
- id: switch_gpio_16
  component_id: switch.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_out_2
        number: 7
        mode: OUTPUT
        inverted: true
      locked: true
    id: switch_gpio_16
    name: e16t-output16
  requires:
  - bus_a
  - pcf8574_hub_out_2
source:
  type: esphome-devices
  remote_id: KinCony-E16P
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/KinCony-E16P/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 0e49ff2242e8e70e32e58d2b7e37b6d30285e972adad8e1ff5263ce41cde496f
