id: kincony_dm32
name: KinCony-DM32 (ESP32-S3 32CH Dimmer board)
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework: arduino
hardware:
  connectivity:
  - wifi
  - bluetooth
  - ethernet
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/KinCony-DM32/DM32-1.jpg
pins:
- gpio: 1
  available: false
  occupied_by: Ethernet CLK
- gpio: 2
  available: false
  occupied_by: Ethernet MOSI
- gpio: 7
  available: false
  occupied_by: dm32-W1-io7
- gpio: 8
  available: false
  occupied_by: bus_a
- gpio: 13
  available: false
  occupied_by: dm32-W1-io13
- gpio: 14
  available: false
  occupied_by: dm32-W1-io14
- gpio: 18
  available: false
  occupied_by: bus_a
- gpio: 21
  available: false
  occupied_by: dm32-W1-io21
- gpio: 38
  available: false
  occupied_by: uart_1
- gpio: 39
  available: false
  occupied_by: uart_1
- gpio: 40
  available: false
  occupied_by: dm32-W1-io40
- gpio: 41
  available: false
  occupied_by: Ethernet MISO
- gpio: 42
  available: false
  occupied_by: Ethernet CS
- gpio: 43
  available: false
  occupied_by: Ethernet INT
- gpio: 44
  available: false
  occupied_by: Ethernet RESET
- gpio: 47
  available: false
  occupied_by: dm32-W1-io47
- gpio: 48
  available: false
  occupied_by: dm32-W1-io48
docs_url: https://devices.esphome.io/devices/KinCony-DM32/
featured_components:
- id: uart_1
  component_id: uart
  fields:
    baud_rate: 9600
    debug:
      value:
        direction: BOTH
        dummy_receiver: true
        after:
          timeout: 10ms
      locked: true
    tx_pin:
      value: 39
      locked: true
    rx_pin:
      value: 38
      locked: true
    id:
      value: uart_1
      locked: true
- id: ads1115_hub
  component_id: ads1115
  fields:
    address: 72
  requires:
  - bus_a
- id: bus_a
  component_id: i2c
  fields:
    sda:
      value: 8
      locked: true
    scl:
      value: 18
      locked: true
    scan: true
    frequency: 400kHz
    id:
      value: bus_a
      locked: true
- id: pcf8574_hub_1
  component_id: pcf8574
  fields:
    address: 34
    pcf8575: true
    id:
      value: pcf8574_hub_1
      locked: true
    i2c_id:
      value: bus_a
      locked: true
  requires:
  - bus_a
- id: pcf8574_hub_2
  component_id: pcf8574
  fields:
    address: 36
    pcf8575: true
    id:
      value: pcf8574_hub_2
      locked: true
    i2c_id:
      value: bus_a
      locked: true
  requires:
  - bus_a
- id: onboard_ethernet
  component_id: ethernet
  name: Onboard Ethernet
  fields:
    type:
      value: W5500
      locked: true
    clk_pin:
      value: GPIO1
      locked: true
    mosi_pin:
      value: GPIO2
      locked: true
    miso_pin:
      value: GPIO41
      locked: true
    cs_pin:
      value: GPIO42
      locked: true
    interrupt_pin:
      value: GPIO43
      locked: true
    reset_pin:
      value: GPIO44
      locked: true
- id: dm32_input01
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_1
        number: 8
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input01
    name: dm32-input01
  requires:
  - bus_a
  - pcf8574_hub_1
- id: dm32_input02
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_1
        number: 9
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input02
    name: dm32-input02
  requires:
  - bus_a
  - pcf8574_hub_1
- id: dm32_input03
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_1
        number: 10
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input03
    name: dm32-input03
  requires:
  - bus_a
  - pcf8574_hub_1
- id: dm32_input04
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_1
        number: 11
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input04
    name: dm32-input04
  requires:
  - bus_a
  - pcf8574_hub_1
- id: dm32_input05
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_1
        number: 12
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input05
    name: dm32-input05
  requires:
  - bus_a
  - pcf8574_hub_1
- id: dm32_input06
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_1
        number: 13
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input06
    name: dm32-input06
  requires:
  - bus_a
  - pcf8574_hub_1
- id: dm32_input07
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_1
        number: 14
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input07
    name: dm32-input07
  requires:
  - bus_a
  - pcf8574_hub_1
- id: dm32_input08
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_1
        number: 15
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input08
    name: dm32-input08
  requires:
  - bus_a
  - pcf8574_hub_1
- id: dm32_input09
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_1
        number: 0
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input09
    name: dm32-input09
  requires:
  - bus_a
  - pcf8574_hub_1
- id: dm32_input10
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_1
        number: 1
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input10
    name: dm32-input10
  requires:
  - bus_a
  - pcf8574_hub_1
- id: dm32_input11
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_1
        number: 2
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input11
    name: dm32-input11
  requires:
  - bus_a
  - pcf8574_hub_1
- id: dm32_input12
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_1
        number: 3
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input12
    name: dm32-input12
  requires:
  - bus_a
  - pcf8574_hub_1
- id: dm32_input13
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_1
        number: 4
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input13
    name: dm32-input13
  requires:
  - bus_a
  - pcf8574_hub_1
- id: dm32_input14
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_1
        number: 5
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input14
    name: dm32-input14
  requires:
  - bus_a
  - pcf8574_hub_1
- id: dm32_input15
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_1
        number: 6
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input15
    name: dm32-input15
  requires:
  - bus_a
  - pcf8574_hub_1
- id: dm32_input16
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_1
        number: 7
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input16
    name: dm32-input16
  requires:
  - bus_a
  - pcf8574_hub_1
- id: dm32_input17
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_2
        number: 0
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input17
    name: dm32-input17
  requires:
  - bus_a
  - pcf8574_hub_2
- id: dm32_input18
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_2
        number: 1
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input18
    name: dm32-input18
  requires:
  - bus_a
  - pcf8574_hub_2
- id: dm32_input19
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_2
        number: 2
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input19
    name: dm32-input19
  requires:
  - bus_a
  - pcf8574_hub_2
- id: dm32_input20
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_2
        number: 3
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input20
    name: dm32-input20
  requires:
  - bus_a
  - pcf8574_hub_2
- id: dm32_input21
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_2
        number: 4
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input21
    name: dm32-input21
  requires:
  - bus_a
  - pcf8574_hub_2
- id: dm32_input22
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_2
        number: 5
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input22
    name: dm32-input22
  requires:
  - bus_a
  - pcf8574_hub_2
- id: dm32_input23
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_2
        number: 6
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input23
    name: dm32-input23
  requires:
  - bus_a
  - pcf8574_hub_2
- id: dm32_input24
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_2
        number: 7
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input24
    name: dm32-input24
  requires:
  - bus_a
  - pcf8574_hub_2
- id: dm32_input25
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_2
        number: 8
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input25
    name: dm32-input25
  requires:
  - bus_a
  - pcf8574_hub_2
- id: dm32_input26
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_2
        number: 9
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input26
    name: dm32-input26
  requires:
  - bus_a
  - pcf8574_hub_2
- id: dm32_input27
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_2
        number: 10
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input27
    name: dm32-input27
  requires:
  - bus_a
  - pcf8574_hub_2
- id: dm32_input28
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_2
        number: 11
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input28
    name: dm32-input28
  requires:
  - bus_a
  - pcf8574_hub_2
- id: dm32_input29
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_2
        number: 12
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input29
    name: dm32-input29
  requires:
  - bus_a
  - pcf8574_hub_2
- id: dm32_input30
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_2
        number: 13
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input30
    name: dm32-input30
  requires:
  - bus_a
  - pcf8574_hub_2
- id: dm32_input31
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_2
        number: 14
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input31
    name: dm32-input31
  requires:
  - bus_a
  - pcf8574_hub_2
- id: dm32_input32
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        pcf8574: pcf8574_hub_2
        number: 15
        mode: INPUT
        inverted: true
      locked: true
    id: dm32_input32
    name: dm32-input32
  requires:
  - bus_a
  - pcf8574_hub_2
- id: binary_sensor_gpio_33
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 47
        inverted: true
      locked: true
    id: binary_sensor_gpio_33
    name: dm32-W1-io47
- id: binary_sensor_gpio_34
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 48
        inverted: true
      locked: true
    id: binary_sensor_gpio_34
    name: dm32-W1-io48
- id: binary_sensor_gpio_35
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 7
        inverted: true
      locked: true
    id: binary_sensor_gpio_35
    name: dm32-W1-io7
- id: binary_sensor_gpio_36
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 40
        inverted: true
      locked: true
    id: binary_sensor_gpio_36
    name: dm32-W1-io40
- id: binary_sensor_gpio_37
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 13
        inverted: false
      locked: true
    id: binary_sensor_gpio_37
    name: dm32-W1-io13
- id: binary_sensor_gpio_38
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 14
        inverted: false
      locked: true
    id: binary_sensor_gpio_38
    name: dm32-W1-io14
- id: binary_sensor_gpio_39
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 21
        inverted: false
      locked: true
    id: binary_sensor_gpio_39
    name: dm32-W1-io21
- id: sensor_ads1115_1
  component_id: sensor.ads1115
  fields:
    multiplexer: A0_GND
    gain: 6.144
    resolution: 16_BITS
    update_interval: 5s
    id: sensor_ads1115_1
    name: ADS1115 Channel A0-GND
  requires:
  - bus_a
  - ads1115_hub
- id: sensor_ads1115_2
  component_id: sensor.ads1115
  fields:
    multiplexer: A1_GND
    gain: 6.144
    update_interval: 5s
    id: sensor_ads1115_2
    name: ADS1115 Channel A1-GND
  requires:
  - bus_a
  - ads1115_hub
- id: sensor_ads1115_3
  component_id: sensor.ads1115
  fields:
    multiplexer: A2_GND
    gain: 6.144
    update_interval: 5s
    id: sensor_ads1115_3
    name: ADS1115 Channel A2-GND
  requires:
  - bus_a
  - ads1115_hub
- id: sensor_ads1115_4
  component_id: sensor.ads1115
  fields:
    multiplexer: A3_GND
    gain: 6.144
    update_interval: 5s
    id: sensor_ads1115_4
    name: ADS1115 Channel A3-GND
  requires:
  - bus_a
  - ads1115_hub
- id: switch_uart_1
  component_id: switch.uart
  fields:
    data:
      value:
      - 17
      - 34
      - 51
      - 68
      - 85
      locked: true
    id: switch_uart_1
    name: RS485 Button
    uart_id:
      value: uart_1
      locked: true
  requires:
  - uart_1
source:
  type: esphome-devices
  remote_id: KinCony-DM32
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/KinCony-DM32/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 6e3c80de4e40b4dba62c3f5c784ee38a9c457d71d607f5c1d9b89c0ded754ad0
