id: xiaomi_gateway_3
name: Xiaomi Smart Multi Mode Gateway 3
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32dev
  variant: esp32
  framework: esp-idf
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Xiaomi-Gateway-3/image.jpg
pins:
- gpio: 12
  available: false
  occupied_by: zb-gw03-coordinator Zigbee Download Mode
- gpio: 13
  available: false
  occupied_by: zb-gw03-coordinator Zigbee nRST
- gpio: 14
  available: false
  occupied_by: output0
- gpio: 34
  available: false
  occupied_by: zb-gw03-coordinator Enable Pairing Mode
docs_url: https://devices.esphome.io/devices/Xiaomi-Gateway-3/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    internal: true
    pin:
      value:
        number: 34
        inverted: true
      locked: true
    id: binary_sensor_gpio_1
    name: zb-gw03-coordinator Enable Pairing Mode
- id: light_monochromatic_1
  component_id: light.monochromatic
  fields:
    output: output0
    id: light_monochromatic_1
    name: zb-gw03-coordinator green led
- id: output0
  component_id: output.ledc
  fields:
    pin:
      value: 14
      locked: true
    inverted:
      value: true
      locked: true
    id: output0
- id: zigbee_rst
  component_id: switch.gpio
  fields:
    pin:
      value: 13
      locked: true
    inverted:
      value: true
      locked: true
    internal: true
    restore_mode: ALWAYS_OFF
    id: zigbee_rst
    name: zb-gw03-coordinator Zigbee nRST
- id: download_mode
  component_id: switch.gpio
  fields:
    pin:
      value: 12
      locked: true
    inverted:
      value: true
      locked: true
    restore_mode: ALWAYS_OFF
    id: download_mode
    name: zb-gw03-coordinator Zigbee Download Mode
featured_bundles:
- id: light_monochromatic_1_setup
  name: zb-gw03-coordinator green led (full setup)
  component_ids:
  - output0
  - light_monochromatic_1
source:
  type: esphome-devices
  remote_id: Xiaomi-Gateway-3
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Xiaomi-Gateway-3/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 378db1df646e07188fa892708988bde29d28ec107d670625b444c4517f2d1c1f
