id: havells_glamax_9w_b22_wifi_led_rgb_cct_bulb
name: Havells Glamax 9W B22 WiFi LED RGB CCT Bulb
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: cb2l
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Havells-Glamax-9W-B22-WiFi-LED-RGB-CCT-Bulb/Havells-Glamax-Smart-WiFi-RGB-LED-Bulb-Music-Sync-9W-B22-08.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Havells-Glamax-9W-B22-WiFi-LED-RGB-CCT-Bulb/bulb-dismantled.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Havells-Glamax-9W-B22-WiFi-LED-RGB-CCT-Bulb/chip-wired.jpg
pins:
- gpio: 6
  available: false
  occupied_by: bp5758d
- gpio: 7
  available: false
  occupied_by: bp5758d
docs_url: https://devices.esphome.io/devices/Havells-Glamax-9W-B22-WiFi-LED-RGB-CCT-Bulb/
featured_components:
- id: bp5758d_hub
  component_id: bp5758d
  fields:
    data_pin:
      value: 7
      locked: true
    clock_pin:
      value: 6
      locked: true
- id: light_rgbww_1
  component_id: light.rgbww
  fields:
    restore_mode: RESTORE_DEFAULT_ON
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    color_interlock: true
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_cold_white
    warm_white: output_warm_white
    id: light_rgbww_1
    name: Light
- id: output_red
  component_id: output.bp5758d
  fields:
    channel: 3
    current: 40
    id: output_red
  requires:
  - bp5758d_hub
- id: output_green
  component_id: output.bp5758d
  fields:
    channel: 2
    current: 40
    id: output_green
  requires:
  - bp5758d_hub
- id: output_blue
  component_id: output.bp5758d
  fields:
    channel: 1
    current: 40
    id: output_blue
  requires:
  - bp5758d_hub
- id: output_cold_white
  component_id: output.bp5758d
  fields:
    channel: 5
    current: 30
    id: output_cold_white
  requires:
  - bp5758d_hub
- id: output_warm_white
  component_id: output.bp5758d
  fields:
    channel: 4
    current: 30
    id: output_warm_white
  requires:
  - bp5758d_hub
featured_bundles:
- id: light_rgbww_1_setup
  name: Light (full setup)
  component_ids:
  - bp5758d_hub
  - output_red
  - output_green
  - output_blue
  - output_cold_white
  - output_warm_white
  - light_rgbww_1
source:
  type: esphome-devices
  remote_id: Havells-Glamax-9W-B22-WiFi-LED-RGB-CCT-Bulb
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Havells-Glamax-9W-B22-WiFi-LED-RGB-CCT-Bulb/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 3f26fae085108e4a25d0c677e866c2d90b14cc9001e9af68e68cf163a8a4cb43
