id: acenx_sop04_us
name: Acenx SOP04-US
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Acenx-SOP04-US/sop04-us.jpg
tags:
- relay
- compact
pins:
- gpio: 5
  available: false
  occupied_by: led
- gpio: 12
  available: false
  occupied_by: Acenx SOP04-US Relay1
- gpio: 13
  available: false
  occupied_by: Acenx SOP04-US Button
- gpio: 14
  available: false
  occupied_by: Acenx SOP04-US Relay2
docs_url: https://devices.esphome.io/devices/Acenx-SOP04-US/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 13
        mode: INPUT_PULLUP
        inverted: true
      locked: true
    id: binary_sensor_gpio_1
    name: Acenx SOP04-US Button
- id: led
  component_id: output.gpio
  fields:
    pin:
      value: 5
      locked: true
    inverted:
      value: true
      locked: true
    id: led
- id: sensor_wifi_signal_1
  component_id: sensor.wifi_signal
  fields:
    update_interval: 60s
    id: sensor_wifi_signal_1
    name: Acenx SOP04-US WiFi signal
- id: sensor_uptime_1
  component_id: sensor.uptime
  fields:
    update_interval: 60s
    id: sensor_uptime_1
    name: Acenx SOP04-US Uptime
- id: relay1
  component_id: switch.gpio
  fields:
    pin:
      value: 12
      locked: true
    inverted:
      value: false
      locked: true
    id: relay1
    name: Acenx SOP04-US Relay1
- id: relay2
  component_id: switch.gpio
  fields:
    pin:
      value: 14
      locked: true
    inverted:
      value: false
      locked: true
    id: relay2
    name: Acenx SOP04-US Relay2
source:
  type: esphome-devices
  remote_id: Acenx-SOP04-US
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Acenx-SOP04-US/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: e0338729cd9b45e17a23c4583ed758d92d8c31d18d482f05c67ed88cf12c97fe
