id: tuya_smart_plug_20a
name: Tuya Smart Plug 16/20A with Power Monitoring
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: generic-bk7231n-qfn32-tuya
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tuya-Smart-Plug-20A/tuya-smart-plug-20.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tuya-Smart-Plug-20A/hardware-closeup.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Tuya-Smart-Plug-20A/programming.jpg
tags:
- relay
- compact
pins:
- gpio: 6
  available: false
  occupied_by: sensor.hlw8012
- gpio: 7
  available: false
  occupied_by: sensor.hlw8012
- gpio: 8
  available: false
  occupied_by: sensor.hlw8012
- gpio: 24
  available: false
  occupied_by: relay_1
- gpio: 26
  available: false
  occupied_by: button_1
docs_url: https://devices.esphome.io/devices/Tuya-Smart-Plug-20A/
featured_components:
- id: button_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 26
        mode:
          input: true
          pullup: true
        inverted: true
      locked: true
    icon: mdi:radiobox-blank
    filters:
      value:
      - delayed_on: 50ms
      locked: true
    id: button_1
    name: button_1
- id: relay_1
  component_id: output.gpio
  fields:
    pin:
      value: 24
      locked: true
    id: relay_1
- id: sensor_hlw8012_1
  component_id: sensor.hlw8012
  fields:
    model: BL0937
    cf_pin:
      value:
        number: 6
        inverted: true
      locked: true
    cf1_pin:
      value:
        number: 7
        inverted: true
      locked: true
    sel_pin:
      value:
        number: 8
        inverted: true
      locked: true
    voltage_divider: 760
    initial_mode: CURRENT
    update_interval: 15s
    change_mode_every: 4
    id: sensor_hlw8012_1
source:
  type: esphome-devices
  remote_id: Tuya-Smart-Plug-20A
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Tuya-Smart-Plug-20A/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 986d64fb1c916b99c96ba6a495ab182349d853cf185e4bdd68864fd9750bd3e8
