id: ultrapro_wfd4001_light_switch
name: UltraPro WFD4001 Light Switch
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: bk72xx
  board: wb3s
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/UltraPro-WFD4001-Light-Switch/ultrapro-wfd4001-light-switch-v1.1.14.jpg
docs_url: https://devices.esphome.io/devices/UltraPro-WFD4001-Light-Switch/
featured_components:
- id: blue_led
  component_id: light.status_led
  fields:
    disabled_by_default: true
    restore_mode: RESTORE_DEFAULT_OFF
    output: output_blue_led
    id: blue_led
    name: Blue LED
- id: output_blue_led
  component_id: output.libretiny_pwm
  fields:
    pin:
      value: PWM4
      locked: true
    id: output_blue_led
- id: relay
  component_id: switch.gpio
  fields:
    pin:
      value: PWM5
      locked: true
    restore_mode: RESTORE_DEFAULT_OFF
    device_class: switch
    id: relay
    name: None
featured_bundles:
- id: blue_led_setup
  name: Blue LED (full setup)
  component_ids:
  - output_blue_led
  - blue_led
source:
  type: esphome-devices
  remote_id: UltraPro-WFD4001-Light-Switch
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/UltraPro-WFD4001-Light-Switch/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 8984419f25e434a178253c9b33c9fc4d9251a2d63a9be8936e734370fedb88a3
