id: athom_smart_plug_pg03_us16a
name: Athom Smart Plug PG03-US16A
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp8285
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/Athom-Smart-Plug-PG03-US16A/athom_PG03-US16A.webp
tags:
- relay
- compact
pins:
- gpio: 3
  available: false
  occupied_by: Athom Smart Plug Power Button
- gpio: 4
  available: false
  occupied_by: sensor.hlw8012
- gpio: 5
  available: false
  occupied_by: sensor.hlw8012
- gpio: 12
  available: false
  occupied_by: sensor.hlw8012
- gpio: 13
  available: false
  occupied_by: Athom Smart Plug Status LED
- gpio: 14
  available: false
  occupied_by: Athom Smart Plug
docs_url: https://devices.esphome.io/devices/Athom-Smart-Plug-PG03-US16A/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 3
        mode: INPUT_PULLUP
        inverted: true
      locked: true
    disabled_by_default: true
    id: binary_sensor_gpio_1
    name: Athom Smart Plug Power Button
- id: blue_led
  component_id: light.status_led
  fields:
    icon: mdi:led-outline
    disabled_by_default: true
    pin:
      value:
        inverted: true
        number: 13
      locked: true
    id: blue_led
    name: Athom Smart Plug Status LED
- id: sensor_uptime_1
  component_id: sensor.uptime
  fields:
    icon: mdi:clock-outline
    disabled_by_default: true
    id: sensor_uptime_1
    name: Athom Smart Plug Uptime
- id: sensor_hlw8012_1
  component_id: sensor.hlw8012
  fields:
    sel_pin:
      value:
        number: 12
        inverted: true
      locked: true
    cf_pin:
      value: 4
      locked: true
    cf1_pin:
      value: 5
      locked: true
    voltage_divider: 780
    change_mode_every: 1
    update_interval: 10s
    id: sensor_hlw8012_1
- id: sensor_wifi_signal_1
  component_id: sensor.wifi_signal
  fields:
    update_interval: 60s
    id: sensor_wifi_signal_1
    name: Athom Smart Plug Wifi Signal
- id: relay
  component_id: switch.gpio
  fields:
    icon: mdi:power-socket-us
    pin:
      value: 14
      locked: true
    restore_mode: RESTORE_DEFAULT_OFF
    id: relay
    name: Athom Smart Plug
source:
  type: esphome-devices
  remote_id: Athom-Smart-Plug-PG03-US16A
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/Athom-Smart-Plug-PG03-US16A/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 8f90f9dc4b36de25ddf0d432727adf8ab0749afc46910ba3123916d6b10dc4c8
