id: esp_12f_relay_x8
name: ESP-12F_Relay_X8
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp12e
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/ESP-12F-Relay-X8/image.jpg
tags:
- relay
pins:
- gpio: 0
  available: false
  occupied_by: Relay6
- gpio: 2
  available: false
  occupied_by: RelayBoard LED
- gpio: 4
  available: false
  occupied_by: Relay7
- gpio: 5
  available: false
  occupied_by: Relay8
- gpio: 12
  available: false
  occupied_by: Relay3
- gpio: 13
  available: false
  occupied_by: Relay4
- gpio: 14
  available: false
  occupied_by: Relay2
- gpio: 15
  available: false
  occupied_by: Relay5
- gpio: 16
  available: false
  occupied_by: Relay1
docs_url: https://devices.esphome.io/devices/ESP-12F-Relay-X8/
featured_components:
- id: light_status_led_1
  component_id: light.status_led
  fields:
    restore_mode: ALWAYS_ON
    pin:
      value:
        number: 2
        inverted: true
      locked: true
    id: light_status_led_1
    name: RelayBoard LED
- id: relay1
  component_id: switch.gpio
  fields:
    pin:
      value: 16
      locked: true
    id: relay1
    name: Relay1
- id: relay2
  component_id: switch.gpio
  fields:
    pin:
      value: 14
      locked: true
    id: relay2
    name: Relay2
- id: relay3
  component_id: switch.gpio
  fields:
    pin:
      value: 12
      locked: true
    id: relay3
    name: Relay3
- id: relay4
  component_id: switch.gpio
  fields:
    pin:
      value: 13
      locked: true
    id: relay4
    name: Relay4
- id: relay5
  component_id: switch.gpio
  fields:
    pin:
      value: 15
      locked: true
    id: relay5
    name: Relay5
- id: relay6
  component_id: switch.gpio
  fields:
    pin:
      value: 0
      locked: true
    id: relay6
    name: Relay6
- id: relay7
  component_id: switch.gpio
  fields:
    pin:
      value: 4
      locked: true
    id: relay7
    name: Relay7
- id: relay8
  component_id: switch.gpio
  fields:
    pin:
      value: 5
      locked: true
    id: relay8
    name: Relay8
source:
  type: esphome-devices
  remote_id: ESP-12F-Relay-X8
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/ESP-12F-Relay-X8/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 89f7ad4ee95b07037594153379b206e5592e765559416e4e0ca75b4724fec2a5
