id: m5stack_core2_v1_1
name: M5Stack Core2 V1.1
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp32
  board: esp32dev
  variant: esp32
  framework: arduino
hardware:
  connectivity:
  - wifi
  - bluetooth
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/M5Stack-Core2-V1.1/M5Core2V1.1.png
pins:
- gpio: 18
  available: false
  occupied_by: spi
- gpio: 21
  available: false
  occupied_by: bus_a
- gpio: 22
  available: false
  occupied_by: bus_a
- gpio: 23
  available: false
  occupied_by: spi
- gpio: 38
  available: false
  occupied_by: spi
- gpio: 39
  available: false
  occupied_by: touchscreen.ft63x6
docs_url: https://devices.esphome.io/devices/M5Stack-Core2-V1.1/
product_url: https://docs.m5stack.com/en/core/Core2%20v1.1
featured_components:
- id: spi_bus
  component_id: spi
  fields:
    clk_pin:
      value: 18
      locked: true
    mosi_pin:
      value: 23
      locked: true
    miso_pin:
      value: 38
      locked: true
- id: bus_a
  component_id: i2c
  fields:
    sda:
      value: 21
      locked: true
    scl:
      value: 22
      locked: true
    scan: true
    id:
      value: bus_a
      locked: true
- id: onboard_psram
  component_id: psram
  name: PSRAM
  fields:
    mode: quad
    speed: 80MHz
- id: binary_sensor_touchscreen_1
  component_id: binary_sensor.touchscreen
  fields:
    x_min: 10
    x_max: 120
    y_min: 240
    y_max: 280
    use_raw: true
    id: binary_sensor_touchscreen_1
    name: Button A
- id: binary_sensor_touchscreen_2
  component_id: binary_sensor.touchscreen
  fields:
    x_min: 130
    x_max: 200
    y_min: 240
    y_max: 280
    use_raw: true
    id: binary_sensor_touchscreen_2
    name: Button B
- id: binary_sensor_touchscreen_3
  component_id: binary_sensor.touchscreen
  fields:
    x_min: 230
    x_max: 310
    y_min: 240
    y_max: 280
    use_raw: true
    id: binary_sensor_touchscreen_3
    name: Button C
- id: display_mipi_spi_1
  component_id: display.mipi_spi
  fields:
    model: M5CORE2
    show_test_card: true
    id: display_mipi_spi_1
  requires:
  - onboard_psram
  - spi_bus
- id: sensor_mpu6886_1
  component_id: sensor.mpu6886
  fields:
    address: 104
    update_interval: 1s
    id: sensor_mpu6886_1
  requires:
  - bus_a
- id: touchscreen_ft63x6_1
  component_id: touchscreen.ft63x6
  fields:
    interrupt_pin:
      value: 39
      locked: true
    id: touchscreen_ft63x6_1
  requires:
  - bus_a
source:
  type: esphome-devices
  remote_id: M5Stack-Core2-V1.1
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/M5Stack-Core2-V1.1/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: f37b7c06e4e7b664c56bd6ac923f8a0176c069d14051653168dc2448a0237a5d
