id: qiachip_smart_switch
name: QIACHIP Smart Switch
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp01_1m
  logger_hardware_uart: UART1
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/QIACHIP-Smart-Switch/top.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/QIACHIP-Smart-Switch/inside-1.jpg
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/QIACHIP-Smart-Switch/inside-2.jpg
tags:
- relay
pins:
- gpio: 4
  available: false
  occupied_by: QIACHIP Test
docs_url: https://devices.esphome.io/devices/QIACHIP-Smart-Switch/
featured_components:
- id: relay
  component_id: switch.gpio
  fields:
    pin:
      value: 4
      locked: true
    inverted:
      value: true
      locked: true
    id: relay
    name: QIACHIP Test
source:
  type: esphome-devices
  remote_id: QIACHIP-Smart-Switch
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/QIACHIP-Smart-Switch/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 3929d7a1c3a0c227272585fdd5637bb5a03b1a1df6fb7a2960d4a903d35aa60e
