id: currysmarter_16a_v1_1_plug
name: CurrySmarter 16A v1.1 Plug
description: Imported from devices.esphome.io — see linked docs for community notes.
esphome:
  platform: esp8266
  board: esp8285
hardware:
  connectivity:
  - wifi
images:
- https://raw.githubusercontent.com/esphome/devices.esphome.io/main/src/docs/devices/CurrySmarter-16A-v1.1-Plug/currysmarter.jpg
tags:
- relay
- compact
pins:
- gpio: 3
  available: false
  occupied_by: sensor.hlw8012
- gpio: 4
  available: false
  occupied_by: Button
- gpio: 12
  available: false
  occupied_by: Relay
- gpio: 13
  available: false
  occupied_by: sensor.hlw8012
- gpio: 14
  available: false
  occupied_by: sensor.hlw8012
docs_url: https://devices.esphome.io/devices/CurrySmarter-16A-v1.1-Plug/
featured_components:
- id: binary_sensor_gpio_1
  component_id: binary_sensor.gpio
  fields:
    pin:
      value:
        number: 4
        mode: INPUT_PULLUP
        inverted: true
      locked: true
    disabled_by_default: true
    internal: true
    id: binary_sensor_gpio_1
    name: Button
- id: sensor_hlw8012_1
  component_id: sensor.hlw8012
  fields:
    model: BL0937
    voltage_divider: 1670
    sel_pin:
      value:
        number: 3
        inverted: true
      locked: true
    cf_pin:
      value: 13
      locked: true
    cf1_pin:
      value: 14
      locked: true
    update_interval: 10s
    id: sensor_hlw8012_1
- id: signal_strength
  component_id: sensor.wifi_signal
  fields:
    update_interval: 60s
    internal: true
    id: signal_strength
    name: WiFi Strength
- id: relay
  component_id: switch.gpio
  fields:
    pin:
      value: 12
      locked: true
    id: relay
    name: Relay
source:
  type: esphome-devices
  remote_id: CurrySmarter-16A-v1.1-Plug
  upstream_url: https://github.com/esphome/devices.esphome.io/blob/main/src/docs/devices/CurrySmarter-16A-v1.1-Plug/index.md
  upstream_revision: cdaade7889f0c6892197672dfd971a73245bafcf
  content_hash: 614c43f54990e3ee6dbfc8cfff8fa805c4d29303935192560ed8de7f1f4fc67f
